import { t } from "@transifex/native";
import * as icons from "~/modules/categories/icons";

export const culture = {
  culture: {
    name: () => t("Culture"),
    icon: icons.theatre,
    synonyms: [
      "cultural_center",
      "Concert Hall",
      "Cultural Center",
      "Jazz Club",
      "200-2300-0022",
      "Kultur und Soziales",
    ],
  },

  museum: {
    name: () => t("Museum"),
    icon: icons.museum,
    parents: ["culture", "leisure", "tourism", "education"],
    synonyms: [
      "tourism=museum",
      "museum",
      "museum",
      "Museum",
      "Art Museum",
      "History Museum",
      "Planetarium",
      "Science Museum",
      "Observatory",
      "Historic Site",
      "Science Museum",
      "Children's Museum",
      "History Museum",
      "Art Museum",
      "300-3100-0026",
      "300-3100-0027",
      "300-3100-0028",
      "300-3100-0029",
      "300-3100-0000",
      "Musée",
      "Museum",
    ],
  },

  library: {
    name: () => t("Library"),
    icon: icons.library,
    parents: ["culture"],
    synonyms: [
      "amenity=library",
      "library",
      "library",
      "Library",
      "Other library",
      "800-8300-0000",
      "800-8300-0175",
      "Bibliothek",
      "Bibliothek",
    ],
  },

  arts_center: {
    name: () => t("Arts center"),
    icon: icons.artGallery,
    parents: ["culture"],
    synonyms: [
      "amenity=arts_centre",
      "cultural_center",
      "Exhibit",
      "Art Studio",
      "arts_centre",
      "Gallery",
      "Convention or Exhibition Centre",
      "300-3000-0024",
      "800-8400-0176",
    ],
  },

  public_art: {
    name: () => t("Artwork"),
    icon: icons.artGallery,
    parents: ["culture"],
    synonyms: [
      "tourism=artwork",
      "Public Art",
      "Outdoor Sculpture",
      "Street Art",
      "Sculpture Garden",
      "artwork",
    ],
  },

  art_gallery: {
    name: () => t("Art Gallery"),
    icon: icons.artGallery,
    parents: ["culture"],
    synonyms: [
      "tourism=gallery",
      "art_gallery",
      "art_gallery",
      "Art Gallery",
      "gallery",
      "Museum oder Galerie",
    ],
  },

  place_of_worship: {
    name: () => t("Place Of Worship"),
    icon: icons.placeOfWorship,
    parents: ["culture"],
    synonyms: [
      "amenity=place_of_worship",
      "synagogue",
      "hindu_temple",
      "mosque",
      "church",
      "place_of_worship",
      "cemetery",
      "place_of_worship",
      "Cemetery",
      "Spiritual Center",
      "Buddhist Temple",
      "Cemevi",
      "Church",
      "Confucian Temple",
      "Hindu Temple",
      "Kingdom Hall",
      "Monastery",
      "Mosque",
      "Prayer Room",
      "Shrine",
      "Synagogue",
      "Temple",
      "Terreiro",
      "Religious School",
      "Religious Place",
      "Church",
      "Temple",
      "Synagogue",
      "Ashram",
      "Mosque",
      "Place of Worship",
      "Gurdwara",
      "300-3200-0000",
      "300-3200-0030",
      "300-3200-0031",
      "300-3200-0032",
      "300-3200-0033",
      "300-3200-0034",
      "300-3200-0309",
      "300-3200-0375",
      "Spiritualité",
      "Friedhof",
    ],
  },

  theater: {
    name: () => t("Theater"),
    icon: icons.theatre,
    parents: ["culture"],
    synonyms: [
      "amenity=theatre",
      "performing_arts_theater",
      "opera_house",
      "Amphitheater",
      "Performing Arts Venue",
      "Indie Theater",
      "Theater",
      "Opera House",
      "College Theater",
      "theatre",
      "Performing Arts Centre",
      "Theatre",
      "Music & Culture",
      "200-2200-0000",
      "200-2200-0020",
      "200-2200-0000",
      "Konzerthalle oder Oper oder Theatersaal",
    ],
  },
} as const;
