import { t } from "@transifex/native";
import * as icons from "../icons";

export const food = {
  food: {
    name: () => t("Food & Drinks"),
    icon: icons.restaurant,
    priority: 20,
    synonyms: [
      "food",
      "meal_delivery",
      "catering_service",
      "College Cafeteria",
      "Corporate Cafeteria",
      "Ski Lodge",
      "Kuruyemişçi",
      "Takeaway and/or Delivery",
      "Catering & Food Services",
      "Food Production",
      "Banqueting Hall",
      "100-1000-0003",
      "700-7200-0253",
      "700-7200-0258",
      "700-7400-0139",
      "Restaurant oder Café oder Bar",
    ],
  },

  restaurant: {
    name: () => t("Restaurant"),
    icon: icons.restaurant,
    parents: ["food"],
    synonyms: [
      "amenity=restaurant",
      "restaurant",
      "restaurant",
      "Food",
      "Diner",
      "Fondue Restaurant",
      "German Restaurant",
      "Apple Wine Pub",
      "Bavarian Restaurant",
      "Bratwurst Joint",
      "Currywurst Joint",
      "Franconian Restaurant",
      "German Pop-Up Restaurant",
      "Palatine Restaurant",
      "Rhenisch Restaurant",
      "Schnitzel Restaurant",
      "Silesian Restaurant",
      "Swabian Restaurant",
      "Gluten-free Restaurant",
      "Greek Restaurant",
      "Magirio",
      "Meze Restaurant",
      "Modern Greek Restaurant",
      "Ouzeri",
      "Patsa Restaurant",
      "Bougatsa Shop",
      "Cretan Restaurant",
      "Fish Taverna",
      "Grilled Meat Restaurant",
      "French Restaurant",
      "Alsatian Restaurant",
      "Auvergne Restaurant",
      "Basque Restaurant",
      "Brasserie",
      "Breton Restaurant",
      "Burgundian Restaurant",
      "Catalan Restaurant",
      "Ch'ti Restaurant",
      "Corsican Restaurant",
      "Estaminet",
      "Labour Canteen",
      "Lyonese Bouchon",
      "Norman Restaurant",
      "Provençal Restaurant",
      "Savoyard Restaurant",
      "Southwestern French Restaurant",
      "Cafeteria",
      "Creperie",
      "Dumpling Restaurant",
      "Eastern European Restaurant",
      "Belarusian Restaurant",
      "Bosnian Restaurant",
      "Romanian Restaurant",
      "Tatar Restaurant",
      "English Restaurant",
      "Falafel Restaurant",
      "Bulgarian Restaurant",
      "Dutch Restaurant",
      "Czech Restaurant",
      "Comfort Food Restaurant",
      "Cajun / Creole Restaurant",
      "Caribbean Restaurant",
      "Cuban Restaurant",
      "Caucasian Restaurant",
      "Bistro",
      "Buffet",
      "Breakfast Spot",
      "Afghan Restaurant",
      "African Restaurant",
      "Ethiopian Restaurant",
      "American Restaurant",
      "New American Restaurant",
      "Asian Restaurant",
      "Burmese Restaurant",
      "Cambodian Restaurant",
      "Chinese Restaurant",
      "Anhui Restaurant",
      "Beijing Restaurant",
      "Cantonese Restaurant",
      "Cha Chaan Teng",
      "Chinese Aristocrat Restaurant",
      "Chinese Breakfast Place",
      "Dim Sum Restaurant",
      "Dongbei Restaurant",
      "Fujian Restaurant",
      "Guizhou Restaurant",
      "Hainan Restaurant",
      "Hakka Restaurant",
      "Henan Restaurant",
      "Hong Kong Restaurant",
      "Huaiyang Restaurant",
      "Hubei Restaurant",
      "Hunan Restaurant",
      "Imperial Restaurant",
      "Jiangsu Restaurant",
      "Jiangxi Restaurant",
      "Macanese Restaurant",
      "Manchu Restaurant",
      "Peking Duck Restaurant",
      "Shaanxi Restaurant",
      "Shandong Restaurant",
      "Shanghai Restaurant",
      "Shanxi Restaurant",
      "Szechuan Restaurant",
      "Taiwanese Restaurant",
      "Tianjin Restaurant",
      "Xinjiang Restaurant",
      "Yunnan Restaurant",
      "Zhejiang Restaurant",
      "Filipino Restaurant",
      "Himalayan Restaurant",
      "Hotpot Restaurant",
      "Indonesian Restaurant",
      "Acehnese Restaurant",
      "Balinese Restaurant",
      "Betawinese Restaurant",
      "Indonesian Meatball Place",
      "Javanese Restaurant",
      "Manadonese Restaurant",
      "Padangnese Restaurant",
      "Sundanese Restaurant",
      "Japanese Restaurant",
      "Donburi Restaurant",
      "Japanese Curry Restaurant",
      "Kaiseki BistroRestaurant",
      "Kushikatsu Restaurant",
      "Monjayaki Restaurant",
      "Nabe Restaurant",
      "Okonomiyaki Restaurant",
      "Ramen Restaurant",
      "Shabu-Shabu Restaurant",
      "Soba Restaurant",
      "Sukiyaki Restaurant",
      "Sushi Restaurant",
      "Takoyaki Place",
      "Tempura Restaurant",
      "Tonkatsu Restaurant",
      "Udon Restaurant",
      "Unagi Restaurant",
      "Wagashi Place",
      "Yakitori Restaurant",
      "Yoshoku Restaurant",
      "Korean Restaurant",
      "Bossam/Jokbal Restaurant",
      "Bunsik Restaurant",
      "Gukbap Restaurant",
      "Janguh Restaurant",
      "Samgyetang Restaurant",
      "Malay Restaurant",
      "Mongolian Restaurant",
      "Noodle House",
      "Satay Restaurant",
      "Thai Restaurant",
      "Som Tum Restaurant",
      "Tibetan Restaurant",
      "Vietnamese Restaurant",
      "Australian Restaurant",
      "Austrian Restaurant",
      "BBQ Joint",
      "Belgian Restaurant",
      "Tsipouro Restaurant",
      "Halal Restaurant",
      "Hawaiian Restaurant",
      "Hungarian Restaurant",
      "Indian Restaurant",
      "Andhra Restaurant",
      "Awadhi Restaurant",
      "Bengali Restaurant",
      "Chaat Place",
      "Chettinad Restaurant",
      "Dhaba",
      "Dosa Place",
      "Goan Restaurant",
      "Gujarati Restaurant",
      "Hyderabadi Restaurant",
      "Indian Chinese Restaurant",
      "Indian Sweet Shop",
      "Irani Cafe",
      "Jain Restaurant",
      "Karnataka Restaurant",
      "Kerala Restaurant",
      "Maharashtrian Restaurant",
      "Mughlai Restaurant",
      "Multicuisine Indian Restaurant",
      "North Indian Restaurant",
      "Northeast Indian Restaurant",
      "Parsi Restaurant",
      "Punjabi Restaurant",
      "Rajasthani Restaurant",
      "South Indian Restaurant",
      "Udupi Restaurant",
      "Italian Restaurant",
      "Abruzzo Restaurant",
      "Agriturismo",
      "Aosta Restaurant",
      "Basilicata Restaurant",
      "Calabria Restaurant",
      "Campanian Restaurant",
      "Emilia Restaurant",
      "Friuli Restaurant",
      "Ligurian Restaurant",
      "Lombard Restaurant",
      "Malga",
      "Marche Restaurant",
      "Molise Restaurant",
      "Piadineria",
      "Piedmontese Restaurant",
      "Puglia Restaurant",
      "Romagna Restaurant",
      "Roman Restaurant",
      "Sardinian Restaurant",
      "Sicilian Restaurant",
      "South Tyrolean Restaurant",
      "Trattoria/Osteria",
      "Trentino Restaurant",
      "Tuscan Restaurant",
      "Umbrian Restaurant",
      "Veneto Restaurant",
      "Jewish Restaurant",
      "Kosher Restaurant",
      "Kebab Restaurant",
      "Latin American Restaurant",
      "Arepa Restaurant",
      "Empanada Restaurant",
      "Salvadoran Restaurant",
      "South American Restaurant",
      "Argentinian Restaurant",
      "Brazilian Restaurant",
      "Acai House",
      "Baiano Restaurant",
      "Central Brazilian Restaurant",
      "Churrascaria",
      "Empada House",
      "Goiano Restaurant",
      "Mineiro Restaurant",
      "Northeastern Brazilian Restaurant",
      "Northern Brazilian Restaurant",
      "Pastelaria",
      "Southeastern Brazilian Restaurant",
      "Southern Brazilian Restaurant",
      "Tapiocaria",
      "Colombian Restaurant",
      "Peruvian Restaurant",
      "Venezuelan Restaurant",
      "Mac & Cheese Joint",
      "Mediterranean Restaurant",
      "Moroccan Restaurant",
      "Mexican Restaurant",
      "Botanero",
      "Burrito Place",
      "Taco Place",
      "Tex-Mex Restaurant",
      "Yucatecan Restaurant",
      "Middle Eastern Restaurant",
      "Israeli Restaurant",
      "Kurdish Restaurant",
      "Lebanese Restaurant",
      "Persian Restaurant",
      "Ash and Haleem Place",
      "Dizi Place",
      "Gilaki Restaurant",
      "Jegaraki",
      "Tabbakhi",
      "Modern European Restaurant",
      "Molecular Gastronomy Restaurant",
      "Pakistani Restaurant",
      "Polish Restaurant",
      "Portuguese Restaurant",
      "Poutine Place",
      "Restaurant",
      "Russian Restaurant",
      "Blini House",
      "Pelmeni House",
      "Salad Place",
      "Sandwich Place",
      "Scandinavian Restaurant",
      "Scottish Restaurant",
      "Seafood Restaurant",
      "Slovak Restaurant",
      "Snack Place",
      "Soup Place",
      "Southern / Soul Food Restaurant",
      "Spanish Restaurant",
      "Paella Restaurant",
      "Tapas Restaurant",
      "Sri Lankan Restaurant",
      "Steakhouse",
      "Swiss Restaurant",
      "Theme Restaurant",
      "Truck Stop",
      "Turkish Restaurant",
      "Borek Place",
      "Cigkofte Place",
      "Doner Restaurant",
      "Doner Restaurant",
      "Gozleme Place",
      "Kofte Place",
      "Kokoreç Restaurant",
      "Kumpir Restaurant",
      "Kumru Restaurant",
      "Manti Place",
      "Meyhane",
      "Pide Place",
      "Pilavcı",
      "Söğüş Place",
      "Tantuni Restaurant",
      "Turkish Home Cooking Restaurant",
      "Çöp Şiş Place",
      "Ukrainian Restaurant",
      "Varenyky restaurant",
      "West-Ukrainian Restaurant",
      "Vegetarian / Vegan Restaurant",
      "Hawker Centre",
      "Restaurant",
      "Casual Dining",
      "Fine Dining",
      "Taqueria",
      "Delicatessen",
      "Bistro",
      "Fast Food",
      "Winery",
      "100-1000-0230",
      "100-1000-0000",
      "100-1000-0001",
      "100-1000-0002",
      "100-1000-0005",
      "100-1000-0006",
      "100-1000-0008",
      "100-1000-0009",
      "300-3000-0065",
      "Restaurant",
      "Restaurant",
    ],
  },

  canteen: {
    name: () => t("Canteen"),
    icon: icons.restaurant,
    parents: ["food"],
    synonyms: ["amenity=canteen"],
  },

  coffee: {
    name: () => t("Cafe"),
    icon: icons.cafe,
    parents: ["food"],
    synonyms: [
      "amenity=cafe",
      "cafe",
      "internet_cafe",
      "Café",
      "Coffee Shop",
      "Kafenio",
      "Corporate Coffee Shop",
      "Pet Café",
      "Turkish Coffeehouse",
      "Internet Cafe",
      "Coffee Shop",
      "Coffee & Tea",
      "Internet Cafe",
      "Transport Cafe/Services",
      "100-1100-0010",
      "100-1100-0000",
      "700-7400-0285",
      "700-7900-0132",
      "100-1000-0007",
    ],
  },

  pub: {
    name: () => t("Bar"),
    icon: icons.bar,
    parents: ["food"],
    synonyms: [
      "amenity=pub",
      "bar",
      "bar",
      "Irish Pub",
      "Pub",
      "Apres Ski Bar",
    ],
  },

  fastfood: {
    name: () => t("Fast Food"),
    icon: icons.fastFood,
    parents: ["food"],
    synonyms: [
      "amenity=fast_food",
      "meal_takeaway",
      "fast_food_restaurant",
      "Burger Joint",
      "Fast Food Restaurant",
      "Fish & Chips Shop",
      "Food Court",
      "Food Stand",
      "Food Truck",
      "Fried Chicken Joint",
      "Friterie",
      "Gastropub",
      "Hot Dog Joint",
      "Juice Bar",
      "Pizza Place",
      "Wings Joint",
      "Street Food Gathering",
      "fast_food",
      "amenity=food_court",
    ],
  },

  bar: {
    name: () => t("Bar"),
    icon: icons.bar,
    parents: ["food", "leisure"],
    synonyms: [
      "amenity=bar",
      "Nightlife Spot",
      "Bar",
      "Beach Bar",
      "Beer Bar",
      "Champagne Bar",
      "Cocktail Bar",
      "Gay Bar",
      "Hookah Bar",
      "Hotel Bar",
      "Sake Bar",
      "Speakeasy",
      "Sports Bar",
      "Tiki Bar",
      "Whisky Bar",
      "Brewery",
      "Lounge",
      "Wine Bar",
      "Music Venue",
      "Jazz Club",
      "Piano Bar",
      "Rock Club",
      "Music Festival",
      "Karaoke Bar",
      "Karaoke Box",
      "Nightlife & Entertainment",
      "Bar or Pub",
      "Night Club",
      "Dance Hall or Studio",
      "Karaoke",
      "Cocktail Lounge",
      "Brewery",
      "Distillery",
      "200-2000-0000",
      "200-2000-0011",
      "200-2000-0012",
      "200-2000-0013",
      "200-2000-0014",
      "200-2000-0368",
      "300-3000-0350",
      "300-3000-0351",
      "Nuit",
      "Club",
    ],
  },

  icecream: {
    name: () => t("Ice Cream Shop"),
    icon: icons.iceCream,
    parents: ["food"],
    synonyms: [
      "amenity=ice_cream",
      "Frozen Yogurt Shop",
      "Ice Cream Shop",
      "ice_cream",
    ],
  },

  biergarten: {
    name: () => t("Beer Garden"),
    icon: icons.beer,
    parents: ["food"],
    synonyms: ["amenity=biergarten", "Beer Garden"],
  },

  drinkingwater: {
    name: () => t("Drinking Water"),
    icon: icons.drinkingWater,
    parents: ["food"],
    synonyms: ["amenity=drinking_water", "drinking_water"],
  },
} as const;
