import { t } from "@transifex/native";
import * as icons from "~/modules/categories/icons";

export const leisure = {
  leisure: {
    name: () => t("Leisure"),
    icon: icons.theatre,
    priority: 40,
    synonyms: [
      "spa",
      "circus",
      "Circus",
      "Comedy Club",
      "General Entertainment",
      "Laser Tag",
      "Pachinko Parlor",
      "Pool Hall",
      "Racecourse",
      "Racetrack",
      "Roller Rink",
      "Salsa Club",
      "Samba",
      "Event School",
      "Event",
      "Festival",
      "Line / Queue",
      "Other Event",
      "Parade",
      "Event Space",
      "Outdoor Event Space",
      "Circus School",
      "Entertainment Service",
      "Arcade",
      "Gaming Cafe",
      "Resort",
      "Paintball Field",
      "Skate Park",
      "Skating Rink",
      "Rest Area",
      "Fishing Spot",
      "Gun Rang",
      "Other Great Outdoors",
      "Roof Deck",
      "Betting Shop",
      "Live Entertainment or Music",
      "Billiards",
      "Pool or Snooker",
      "Amusement Arcade",
      "Lottery Ticket Sales",
      "Recreation Centre",
      "Entertainment & Recreation",
      "Wellness Centre & Services",
      "Clubhouse",
      "200-2000-0015",
      "200-2000-0017",
      "200-2000-0018",
      "550-5510-0206",
      "700-7200-0270",
      "700-7400-0292",
      "800-8700-0296",
      "200-2000-0016",
      "Loisir",
      "Bien-être",
      "leisure=*",
    ],
  },

  outdoor_seating: {
    name: () => t("Outdoor Seating"),
    icon: icons.highwayRestArea,
    parents: ["leisure"],
    synonyms: ["leisure=outdoor_seating"],
  },

  dog_park: {
    name: () => t("Dog Park"),
    icon: icons.dogPark,
    parents: ["leisure"],
    synonyms: ["leisure=dog_park", "Dog park", "Dog Run"],
  },

  shower: {
    name: () => t("Shower"),
    icon: icons.toilet,
    parents: ["accommodation", "leisure", "public_transfer"],
    synonyms: ["amenity=shower", "shower"],
  },

  picnic_table: {
    name: () => t("Picnic table"),
    icon: icons.highwayRestArea,
    parents: ["leisure", "tourism"],
    synonyms: ["leisure=picnic_table"],
  },

  allotments: {
    name: () => t("Allotments"),
    icon: icons.village,
    parents: ["leisure"],
    synonyms: ["landuse=allotments"],
  },

  bbq: {
    name: () => t("Barbecue"),
    icon: icons.bbq,
    parents: ["tourism", "leisure"],
    synonyms: ["amenity=bbq"],
  },

  cinema: {
    name: () => t("Cinema"),
    icon: icons.cinema,
    parents: ["leisure"],
    synonyms: [
      "amenity=cinema",
      "movie_theater",
      "movie_theater",
      "Multiplex",
      "Movie Theater",
      "Drive-in Theater",
      "Indie Movie Theater",
      "Film Studio",
      "Cinema",
      "200-2100-0019",
      "Kino",
    ],
  },

  brothel: {
    name: () => t("Brothel"),
    icon: icons.heart,
    parents: ["leisure"],
    synonyms: ["amenity=brothel", "Adult Entertainment", "200-2000-0306"],
  },

  massage: {
    name: () => t("Massage Studio"),
    icon: icons.hospital,
    parents: ["leisure"],
    synonyms: ["shop=massage", "spa", "Bath House", "Massage Studio", "Spa"],
  },

  playground: {
    name: () => t("Playground / Play equipment"),
    icon: icons.playground,
    parents: ["leisure"],
    synonyms: [
      "leisure=playground",
      "recreation_center",
      "College Rec Center",
      "Indoor Play Area",
      "Playground",
      "Recreation Center",
      "playground=*",
    ],
  },

  zoo: {
    name: () => t("Zoo"),
    icon: icons.zoo,
    parents: ["leisure"],
    synonyms: [
      "tourism=zoo",
      "aquarium",
      "zoo",
      "Aquarium",
      "Zoo",
      "Zoo Exhibit",
      "Wild Animal Park",
      "Wildlife Sanctuary",
      "Aquarium",
      "Animal Park",
      "550-5520-0209",
      "550-5520-0210",
      "550-5520-0211",
      "550-5520-0228",
      "550-5520-0208",
    ],
  },

  casino: {
    name: () => t("Casino"),
    icon: icons.casino,
    parents: ["leisure"],
    synonyms: [
      "amenity=casino",
      "casino",
      "casino",
      "Casino",
      "200-2300-0000",
      "200-2300-0021",
    ],
  },

  stripclub: {
    name: () => t("Strip Club"),
    icon: icons.heart,
    parents: ["leisure"],
    synonyms: ["amenity=stripclub", "Strip Club"],
  },

  park: {
    name: () => t("Park/Garden"),
    icon: icons.park,
    parents: ["leisure"],
    synonyms: [
      "amenity=park",
      "leisure=park",
      "park",
      "national_park",
      "park",
      "Botanical Garden",
      "Garden",
      "Water Park",
      "National Park",
      "Park",
      "Park or Recreation Ground",
      "Outdoor Recreation",
      "landuse=recreation_ground",
      "Garden",
      "Ranger Station",
      "550-5510-0202",
      "550-5510-0204",
      "Botanischer Garten",
      "Park oder Friedhof",
      "leisure=garden",
    ],
  },

  water_ramp: {
    name: () => t("Water Ramp"),
    icon: icons.slipway,
    parents: ["leisure"],
    synonyms: ["water_ramp"],
  },

  sauna: {
    name: () => t("Sauna"),
    icon: icons.hotSpring,
    parents: ["leisure"],
    synonyms: ["leisure=sauna", "Sauna / Steam Room"],
  },

  nightclub: {
    name: () => t("Night Club"),
    icon: icons.nightclub,
    parents: ["leisure"],
    synonyms: [
      "amenity=nightclub",
      "night_club",
      "night_club",
      "Country Dance Club",
      "Dance Studio",
      "Dive Bar",
      "Nightclub",
      "Other Nightlife",
      "Ballroom",
    ],
  },

  communitycentre: {
    name: () => t("Community Center"),
    icon: icons.circle, // TODO: find proper icon, there's a custom one
    parents: ["leisure"],
    synonyms: [
      "amenity=community_centre",
      "city_hall",
      "Community College",
      "Club House",
      "Community Center",
      "Convention Center",
      "Meeting Room",
      "City Hall",
      "Social Club",
      "Wedding Hall",
      "community_centre",
      "Civic or Community Center",
      "Fair or Convention Facility",
      "Collective Community",
      "800-8100-0169",
      "800-8400-0000",
      "900-9200-0299",
      "Kongresshalle",
      "Kultursaal",
      "Turn-und Festhallen",
    ],
  },
} as const;
