import { t } from "@transifex/native";
import * as icons from "../icons";

export const other = {
  other: {
    name: () => t("Other"),
    icon: icons.circle,
    hide: true,
    synonyms: [
      "establishment",
      "electrician",
      "general_contractor",
      "moving_company",
      "painter",
      "plumber",
      "roofing_contractor",
      "storage",
      "Farm",
      "Field",
      "Fountain",
      "Plaza",
      "Reservoir",
      "River",
      "Stables",
      "Island",
      "Lake",
      "Mountain",
      "Forest",
      "Waterfront",
      "Well",
      "Trail",
      "Tree",
      "Other Repair Shop",
      "Astrologer",
      "Pawn Shop",
      "Pop-Up Shop",
      "Recycling Facility",
      "Supplement Shop",
      "Moving Target",
      "Home (private)",
      "Building",
      "Gun Shop",
      "misc",
      "800-8700-0000",
      "900-9100-0215",
      "900-9100-0216",
    ],
  },

  youth_organization: {
    name: () => t("Youth Organization"),
    icon: icons.embassy,
    parents: ["other"],
    synonyms: ["Youth Organizations"],
  },

  tax_advisor: {
    name: () => t("Tax advisor"),
    // TODO: add proper icon
    icon: icons.building,
    parents: ["other"],
    synonyms: ["office=tax_advisor", "Tax Services", "700-7400-0150"],
  },

  recycling: {
    name: () => t("Waste/Recycling"),
    icon: icons.recycling,
    parents: ["other"],
    synonyms: [
      "Recycling Facility",
      "Recycling- Sammelstelle",
      "amenity=recycling",
      "amenity=waste_basket",
      "amenity=waste_disposal",
    ],
  },

  vending_machine: {
    name: () => t("Vending Machine"),
    icon: icons.circle, // TODO: find proper icon
    parents: ["other", "public_transfer", "leisure"],
    synonyms: ["amenity=vending_machine"],
  },

  house: {
    name: () => t("Real Estate Agency"),
    icon: icons.home,
    parents: ["other"],
    synonyms: [
      "office=estate_agent",
      "real_estate_agency",
      "real_estate_agency",
      "Housing Development",
      "Real Estate Office",
      "estate_agent",
      "Real Estate and Brokers",
      "Flat Rental Service",
      "Property Management",
      "Estate Agency",
      "700-7200-0273",
      "700-7200-0324",
      "700-7200-0344",
      "700-7400-0145",
    ],
  },

  veterinary: {
    name: () => t("Veterinarian"),
    icon: icons.veterinary,
    parents: ["other"],
    synonyms: [
      "amenity=veterinary",
      "veterinary_care",
      "veterinarian",
      "Veterinarian",
      "Pet Servic",
      "Veterinary Medicine",
    ],
  },

  association: {
    name: () => t("Association"),
    icon: icons.embassy,
    parents: ["other"],
    synonyms: [
      "office=association",
      "association_or_organization",
      "Organisation or Society",
      "700-7200-0269",
    ],
  },

  industry: {
    name: () => t("Industry"),
    icon: icons.industry,
    parents: ["other"],
    synonyms: [
      "Distribution Center",
      "Factory",
      "Industrial Estate",
      "Power Plant",
      "Waste Facility",
      "Storage Facility",
      "Shipping Store",
      "Manufacturing",
      "Mining",
      "Repair & Maintenance Services",
      "Storage",
      "Industrial Estate",
      "700-7200-0265",
      "700-7200-0266",
      "700-7200-0275",
      "700-7400-0148",
      "900-9200-0218",
    ],
  },

  ngo: {
    name: () => t("Non-Government Organisation"),
    icon: icons.embassy,
    parents: ["other"],
    synonyms: ["office=ngo", "Non-Profit"],
  },

  insurance: {
    name: () => t("Insurance Agency"),
    icon: icons.suitcase,
    parents: ["other"],
    synonyms: [
      "office=insurance",
      "insurance_agency",
      "insurance_agency",
      "unemployment_office",
      "Insurance Office",
    ],
  },

  lawyer: {
    name: () => t("Legal service"),
    icon: icons.building,
    parents: ["other"],
    synonyms: [
      "office=lawyer",
      "lawyer",
      "Lawyer",
      "Financial or Legal Service",
      "Solicitors",
      "Legal Services",
      "700-7400-0138",
      "700-7400-0327",
    ],
  },

  company: {
    name: () => t("Corporate Office"),
    icon: icons.suitcase,
    parents: ["other"],
    synonyms: [
      "office=company",
      "corporate_office",
      "Professional & Other Places",
      "Office",
      "Advertising Agency",
      "Corporate Amenity",
      "Tech Startup",
      "Coworking Space",
      "Conference Room",
      "Research Station",
      "Design Studio",
      "Recording Studio",
      "Event Service",
      "Laboratory",
      "Rental Service",
      "Radio Station",
      "TV Station",
      "Locksmiths & Security Systems Services",
      "Engineering & Scientific Services",
      "Customer Care Centre",
      "Communications & Media",
      "Telephone Service",
      "Commercial Services",
      "Advertising",
      "Marketing",
      "PR & Market Research",
      "Construction",
      "Investigative & Detective Services",
      "Landscaping Services",
      "Management & Consulting Services",
      "Rental & Leasing",
      "Printing & Publishing",
      "Specialty Trade Contractors",
      "Translation & Interpreter Services",
      "B2B Services",
      "Restaurant Commercial Services",
      "Aviation Services",
      "Interior & Exterior Design",
      "Financial Investment Firm",
      "Business Facility",
      "Business Services",
      "Removers",
      "Utilities",
      "Waste Removal & Sanitation",
      "Bill Payment Service",
      "Cleaning Services",
      "Marriage & Match-making Service",
      "Recycling Centre",
      "Plumbers",
      "Offices",
      "Business Area",
      "700-7200-0263",
      "700-7200-0256",
      "700-7200-0255",
      "700-7100-0000",
      "700-7100-0134",
      "700-7200-0000",
      "700-7200-0254",
      "700-7200-0262",
      "700-7200-0264",
      "700-7200-0274",
      "700-7200-0276",
      "700-7200-0277",
      "700-7200-0279",
      "700-7200-0328",
      "700-7200-0329",
      "700-7200-0330",
      "700-7200-0345",
      "700-7250-0136",
      "700-7400-0141",
      "700-7400-0143",
      "700-7400-0151",
      "700-7400-0152",
      "700-7400-0282",
      "700-7400-0287",
      "700-7400-0288",
      "700-7400-0352",
      "700-7400-0366",
      "800-8700-0297",
      "900-9300-0335",
      "700-7200-0252",
      "700-7200-0257",
      "700-7200-0260",
      "700-7200-0342",
      "700-7400-0000",
      "700-7400-0290",
      "Commerce",
      "office=*",
    ],
  },
} as const;
