import { t } from "@transifex/native";
import * as icons from "../icons";

export const shopping = {
  shopping: {
    name: () => t("Shopping"),
    icon: icons.grocery,
    synonyms: [
      "store",
      "store",
      "cheese_shop",
      "perfume_store",
      "copy_shop",
      "luggage_store",
      "Shop & Service",
      "Big Box Store",
      "Construction & Landscaping",
      "Fireworks Store",
      "Dairy Store",
      "Duty-free Shop",
      "Baby Store",
      "Miscellaneous Shop",
      "shopping",
      "General Merchandise",
      "600-6900-0000",
      "600-6900-0249",
      "600-6900-0099",
      "Geschäfte",
      "shop=*",
    ],
    priority: 10,
  },

  bicycle_repair: {
    name: () => t("Bicycle Repair Station"),
    icon: icons.bicycle,
    parents: ["shopping"],
    synonyms: [
      "amenity=bicycle_repair_station",
      "Bicycle Repair & Maintenance",
    ],
  },

  cemetery: {
    name: () => t("Cemetery"),
    icon: icons.cemetery,
    parents: ["shopping"],
    synonyms: ["Cemetery", "landuse=cemetery"],
  },

  supermarket: {
    name: () => t("Supermarket"),
    icon: icons.grocery,
    parents: ["shopping"],
    synonyms: [
      "shop=supermarket",
      "grocery_or_supermarket",
      "supermarket",
      "grocery_store",
      "Food & Drink Shop",
      "Food Service",
      "Supermarket",
      "Turşucu",
      "600-6300-0066",
    ],
  },

  confectionery: {
    name: () => t("Confectionery"),
    icon: icons.confectionery,
    parents: ["shopping"],
    synonyms: [
      "shop=confectionery",
      "Dessert Shop",
      "Cupcake Shop",
      "Pastry Shop",
      "Pie Shop",
      "Donut Shop",
      "Candy Store",
      "Chocolate Shop",
      "confectionery",
      "Sweet Shop",
      "600-6300-0245",
    ],
  },

  erotic: {
    name: () => t("Adult Shop"),
    icon: icons.heart,
    parents: ["shopping"],
    synonyms: [
      "shop=erotic",
      "Adult Boutique",
      "Erotic Museum",
      "Adult/Sex Shop",
      "600-6900-0305",
    ],
  },

  funeral_home: {
    name: () => t("funeral Home"),
    icon: icons.cemetery,
    parents: ["shopping"],
    synonyms: [
      "shop=funeral_directors",
      "funeral_home",
      "funeral_home",
      "Funeral Home",
      "funeral_directors",
      "Funeral Home",
      "Crematorium",
      "700-7400-0142",
      "800-8700-0166",
      "800-8700-0167",
    ],
  },

  mall: {
    name: () => t("Mall"),
    icon: icons.shop,
    parents: ["shopping"],
    synonyms: [
      "shop=mall",
      "shopping_mall",
      "shopping_center",
      "Shopping Mall",
      "Shopping Plaza",
      "Mall or Shopping Centre",
      "Shopping Centre",
      "Mall",
      "Shopping Center",
      "600-6100-0062",
      "Einkaufszentrum",
    ],
  },

  music: {
    name: () => t("Record Store"),
    icon: icons.music,
    parents: ["shopping"],
    synonyms: [
      "shop=music",
      "Music Store",
      "Record Shop",
      "Vinyl",
      "CD & Video Sales",
      "600-6900-0105",
    ],
  },

  organic_food: {
    name: () => t("Organic Grocery"),
    icon: icons.grocery,
    parents: ["shopping"],
    synonyms: [
      "shop=organic",
      "Health Food Store",
      "Organic Grocery",
      "organic",
    ],
  },

  pet_store: {
    name: () => t("Pet Store"),
    icon: icons.veterinary,
    parents: ["shopping"],
    synonyms: [
      "shop=pet",
      "pet_store",
      "pet_supply_store",
      "Pet Store",
      "pet",
      "Pet Supplies",
      "Pet Care Service",
      "600-6900-0097",
      "700-7400-0293",
    ],
  },

  greengrocer: {
    name: () => t("Greengrocer"),
    icon: icons.grocery,
    parents: ["shopping"],
    synonyms: [
      "shop=greengrocer",
      "green_grocers",
      "Grocery Store",
      "Fruit & Vegetable Store",
    ],
  },

  tobacco: {
    name: () => t("Tobacco Store"),
    icon: icons.grocery,
    parents: ["shopping"],
    synonyms: [
      "shop=tobacco",
      "tobacco_shop",
      "Marijuana Dispensary",
      "Vape Store",
      "Smoke Shop",
    ],
  },

  bicycle_store: {
    name: () => t("Bicycle Store"),
    icon: icons.bicycle,
    parents: ["shopping"],
    synonyms: [
      "shop=bicycle",
      "bicycle_store",
      "Bike Shop",
      "bicycle",
      "Bicycle Service",
      "Bicycle & Accessories Shop",
      "550-5510-0387",
      "600-6900-0246",
      "700-7400-0281",
      "500-5500-0387",
    ],
  },

  computers: {
    name: () => t("Computers"),
    icon: icons.grocery,
    parents: ["shopping"],
    synonyms: [
      "shop=computer",
      "IT Services",
      "computer",
      "Computer Hardware & Software",
      "IT & Office Equipment Services",
      "600-6500-0075",
      "700-7200-0261",
      "office=it",
    ],
  },

  sports_shop: {
    name: () => t("Sports Shop"),
    icon: icons.soccer,
    parents: ["shopping"],
    synonyms: [
      "shop=sports",
      "sporting_goods_store",
      "Board Shop",
      "Sporting Goods Shop",
      "sports",
      "Sporting Goods Store",
      "Running/Walking Shop",
      "Skate Shop",
      "Ski Shop",
      "Snowboard Shop",
      "Surf Shop",
      "Cross-country Ski Shop",
      "600-6900-0094",
      "600-6900-0389",
      "600-6900-0390",
      "600-6900-0391",
      "600-6900-0392",
      "600-6900-0393",
      "600-6900-0397",
      "800-8600-0196",
      "Sport",
    ],
  },

  hiking: {
    name: () => t("Outdoor Supply"),
    icon: icons.mountain,
    parents: ["shopping"],
    synonyms: [
      "shop=outdoor",
      "Dive Shop",
      "Ski Shop",
      "Outdoor Supply Store",
      "Hunting Supply",
      "outdoor",
      "Outdoor Services",
      "Hunting/Fishing Shop",
      "Camping/Hiking Shop",
      "Canoe/Kayak Shop",
      "BMX Shop",
      "Tack Shop",
      "550-5510-0379",
      "600-6900-0388",
      "600-6900-0395",
      "600-6900-0396",
      "600-6900-0394",
      "600-6900-0398",
    ],
  },

  kiosk: {
    name: () => t("Kiosk"),
    icon: icons.grocery,
    parents: ["shopping"],
    synonyms: [
      "shop=kiosk",
      "Lottery Retailer",
      "Self-Service Kiosk",
      "700-7400-0291",
    ],
  },

  mobile_phones: {
    name: () => t("Phone Store"),
    icon: icons.mobilePhone,
    parents: ["shopping"],
    synonyms: [
      "shop=mobile_phone",
      "shop=telecommunication",
      "cell_phone_store",
      "Mobile Phone Shop",
      "mobile_phone",
      "Mobile Phone Retailer",
      "Mobile Phone Service & Repair",
      "600-6500-0073",
      "600-6500-0074",
    ],
  },

  newsagent: {
    name: () => t("Newsstand"),
    icon: icons.shop,
    parents: ["shopping"],
    synonyms: ["shop=newsagent", "Newsstand"],
  },

  tailor: {
    name: () => t("Tailor"),
    icon: icons.clothingStore,
    parents: ["shopping"],
    synonyms: [
      "shop=tailor",
      "Tailor Shop",
      "Tailoring & Alteration",
      "700-7400-0149",
    ],
  },

  tea_shop: {
    name: () => t("Tea"),
    icon: icons.teahouse,
    parents: ["shopping"],
    synonyms: [
      "shop=tea",
      "tea_house",
      "Bubble Tea Shop",
      "Tea Room",
      "tea",
      "Tea Room",
      "100-1100-0331",
    ],
  },

  textiles: {
    name: () => t("Textiles"),
    icon: icons.clothingStore,
    parents: ["shopping"],
    synonyms: ["shop=fabric", "Fabric Shop", "fabric"],
  },

  video_store: {
    name: () => t("Video Store"),
    icon: icons.cinema,
    parents: ["shopping"],
    synonyms: [
      "shop=video",
      "movie_rental",
      "music_store",
      "movie_rental_store",
      "Video Store",
      "video",
      "Video & Game Rental",
      "600-6900-0106",
    ],
  },

  art_shop: {
    name: () => t("Arts & Crafts"),
    icon: icons.gift,
    parents: ["shopping"],
    synonyms: ["shop=art", "Arts & Crafts Store"],
  },

  car_repair: {
    name: () => t("Car Repair"),
    icon: icons.carRepair,
    parents: ["shopping"],
    synonyms: [
      "shop=car_repair",
      "car_repair",
      "car_wash",
      "Auto Garage",
      "Auto Workshop",
      "Motorcycle Shop",
      "Car Wash",
      "Motorcycle Accessories",
      "Motorcycle Service & Maintenance",
      "Towing Service",
      "Car Repair or Service",
      "Car Washing & Detailing",
      "Car Repair",
      "Auto Parts",
      "Vehicle Emissions Testing",
      "Tyre Repair",
      "Truck Repair",
      "Van Repair",
      "Roadside Assistance",
      "Automotive Services",
      "Truck Washing",
      "600-6900-0248",
      "700-7200-0268",
      "700-7200-0278",
      "700-7850-0000",
      "700-7850-0121",
      "700-7850-0122",
      "700-7850-0123",
      "700-7850-0124",
      "700-7850-0125",
      "700-7850-0126",
      "700-7850-0127",
      "700-7850-0128",
      "700-7850-0129",
      "700-7900-0323",
    ],
  },

  variety_store: {
    name: () => t("Discount Store"),
    icon: icons.shop,
    parents: ["shopping"],
    synonyms: [
      "shop=variety_store",
      "Discount Store",
      "Outlet Mall",
      "Outlet Store",
      "Stoop Sale",
      "Speciality Store",
      "Discount Store",
      "Variety Store",
      "600-6900-0096",
      "600-6900-0100",
      "600-6900-0102",
    ],
  },

  photography: {
    name: () => t("Photography"),
    icon: icons.attraction,
    parents: ["shopping"],
    synonyms: [
      "shop=photo",
      "photo_lab",
      "Camera Store",
      "Photography Lab",
      "Photography Studio",
      "photo",
      "Photographic Services",
      "700-7400-0144",
      "Spectacle",
    ],
  },

  diy: {
    name: () => t("Hobby Shop"),
    icon: icons.shop,
    parents: ["shopping"],
    synonyms: [
      "shop=doityourself",
      "home_improvement_store",
      "Hobby Shop",
      "Knitting Store",
      "doityourself",
      "Hardware Shop or DIY Centre",
      "Handicraft Supplies",
      "600-6600-0077",
      "600-6900-0307",
    ],
  },

  beverages: {
    name: () => t("Beverage Store"),
    icon: icons.alcoholShop,
    parents: ["shopping"],
    synonyms: ["shop=beverages"],
  },

  beautysalon: {
    name: () => t("Beauty Salon"),
    icon: icons.hairdresser,
    parents: ["shopping"],
    synonyms: [
      "shop=beauty",
      "beauty_salon",
      "beauty_salon",
      "Health & Beauty Service",
      "Nail Salon",
      "Piercing Parlor",
      "Tanning Salon",
      "Tattoo Parlor",
      "tattoo",
      "shop=tattoo",
      "beauty",
      "Hair and Beauty",
      "Hair & Beauty",
      "Barber",
      "Nail Salon",
      "Hair Salon",
      "Body Piercing & Tattoos",
      "Wedding & Bridal Services",
      "Tanning Salon",
      "600-6900-0104",
      "600-6950-0000",
      "600-6950-0399",
      "600-6950-0400",
      "600-6950-0401",
      "700-7400-0283",
      "700-7400-0284",
      "700-7400-0343",
      "amenity=tanning_salon",
    ],
  },

  tools: {
    name: () => t("Hardware Store"),
    icon: icons.hardware,
    parents: ["shopping"],
    synonyms: [
      "shop=hardware",
      "hardware_store",
      "locksmith",
      "Hardware Store",
      "Locksmith",
      "hardware",
      "Hardware",
      "Home & Garden",
      "Timber Merchants & Supplies",
      "Power Equipment Dealer",
      "Paint & Decorating Supplies",
      "600-6600-0084",
      "600-6600-0310",
      "600-6600-0319",
      "600-6600-0000",
    ],
  },

  deli: {
    name: () => t("Deli"),
    icon: icons.restaurantSushi,
    parents: ["shopping"],
    synonyms: [
      "shop=deli",
      "Deli / Bodega",
      "Souvlaki Shop",
      "Fishing Store",
      "Gourmet Shop",
      "Herbs & Spices Store",
      "Cheese Shop",
      "Smoothie Shop",
      "deli",
      "Specialty Food & Beverage",
      "Specialty Food Store",
      "600-6300-0064",
      "600-6300-0067",
    ],
  },

  travel_agency: {
    name: () => t("Travel Agency"),
    icon: icons.airport,
    parents: ["shopping"],
    synonyms: [
      "shop=travel_agency",
      "travel_agency",
      "travel_agency",
      "Travel Agency",
      "Travel & Transport",
      "General Travel",
      "Travel Agency & Tickets",
      "700-7400-0133",
      "Reisebüro",
    ],
  },

  stationery: {
    name: () => t("Stationery"),
    icon: icons.circle, // TODO: find proper icon
    parents: ["shopping"],
    synonyms: [
      "shop=stationery",
      "Paper / Office Supplies Store",
      "Stationery Store",
      "Office Supplies & Services",
      "600-6900-0095",
    ],
  },

  copyshop: {
    name: () => t("Copy Shop"),
    icon: icons.grocery,
    parents: ["shopping"],
    synonyms: ["shop=copyshop", "copy_shop", "Print Shop"],
  },

  interior_decoration: {
    name: () => t("Interior Design Shop"),
    icon: icons.shop,
    parents: ["shopping"],
    synonyms: [
      "shop=interior_decoration",
      "Frame Store",
      "art",
      "Home Speciality Store",
      "Flooring & Carpet",
      "Glaziers/Window Fitters",
      "600-6600-0078",
      "600-6600-0079",
      "600-6600-0083",
    ],
  },

  "2nd_hand": {
    name: () => t("Thrift Shop"),
    icon: icons.grocery,
    parents: ["shopping"],
    synonyms: [
      "shop=second_hand",
      "Thrift / Vintage Store",
      "second_hand",
      "Second-hand Shop",
      "600-6900-0251",
    ],
  },

  toys: {
    name: () => t("Toy Store"),
    icon: icons.gaming,
    parents: ["shopping"],
    synonyms: [
      "shop=toys",
      "toy_store",
      "Toy / Game Store",
      "Video Game Store",
      "Toy Shop",
      "600-6900-0358",
    ],
  },

  laundry: {
    name: () => t("Laundry Service"),
    icon: icons.laundry,
    parents: ["shopping"],
    synonyms: [
      "shop=laundry",
      "laundry",
      "laundry",
      "Laundromat",
      "Laundry Service",
      "Dry Cleaning & Laundry",
      "700-7400-0137",
    ],
  },

  butcher: {
    name: () => t("Butcher"),
    icon: icons.grocery,
    parents: ["shopping", "food"],
    synonyms: [
      "shop=butcher",
      "butcher_shop",
      "Butcher",
      "Sausage Shop",
      "Butcher's",
      "600-6300-0363",
    ],
  },

  bread: {
    name: () => t("Bakery"),
    icon: icons.bakery,
    parents: ["shopping", "food"],
    synonyms: [
      "shop=bakery",
      "bakery",
      "bakery",
      "Bagel Shop",
      "Bakery",
      "bakery",
      "Baker's",
      "600-6300-0244",
    ],
  },

  alcohol: {
    name: () => t("Liquor Store"),
    icon: icons.alcoholShop,
    parents: ["shopping"],
    synonyms: [
      "shop=alcohol",
      "liquor_store",
      "wine_store",
      "Winery",
      "Beer Store",
      "Wine Shop",
      "Liquor Store",
      "Distillery",
      "Wine & Spirits",
      "600-6300-0068",
    ],
  },

  garden_center: {
    name: () => t("Garden Center"),
    icon: icons.gardenCentre,
    parents: ["shopping"],
    synonyms: [
      "shop=garden_centre",
      "Garden Center",
      "garden_centre",
      "Garden Centre",
      "600-6600-0082",
    ],
  },

  antiques: {
    name: () => t("Antique Shop"),
    icon: icons.grocery,
    parents: ["shopping"],
    synonyms: ["shop=antiques", "antique_furniture_store", "Antique Shop"],
  },

  market: {
    name: () => t("Market"),
    icon: icons.grocery,
    parents: ["shopping"],
    synonyms: [
      "amenity=marketplace",
      "market",
      "bazaar",
      "seafood_market",
      "Farmers Market",
      "Christmas Market",
      "Fish Market",
      "Market",
      "Flea Market",
      "Night Market",
      "Street Fair",
      "Fair",
      "Floating Market",
      "Market Stall with Food",
      "Market",
      "100-1000-0004",
      "600-6900-0247",
    ],
  },

  gifts: {
    name: () => t("Souvenir Shop"),
    icon: icons.gift,
    parents: ["shopping"],
    synonyms: [
      "shop=gift",
      "Gift Shop",
      "Souvenir Shop",
      "gift",
      "Gifts",
      "Antiques & Art",
      "600-6900-0103",
    ],
  },

  flowers: {
    name: () => t("Florist"),
    icon: icons.florist,
    parents: ["shopping"],
    synonyms: [
      "shop=florist",
      "florist",
      "florist",
      "Flower Shop",
      "Florist",
      "600-6900-0355",
    ],
  },

  dry_cleaning: {
    name: () => t("Dry Cleaner"),
    icon: icons.laundry,
    parents: ["shopping"],
    synonyms: ["shop=dry_cleaning", "Dry Cleaner"],
  },

  department_store: {
    name: () => t("Department Store"),
    icon: icons.grocery,
    parents: ["shopping"],
    synonyms: [
      "shop=department_store",
      "department_store",
      "department_store",
      "Warehouse",
      "Department Store",
      "Warehouse Store",
      "Department Store",
      "Warehouse or Wholesaler",
      "600-6200-0063",
      "600-6900-0098",
    ],
  },

  convenience_store: {
    name: () => t("Convencience Store"),
    icon: icons.convenience,
    parents: ["shopping"],
    synonyms: [
      "shop=convenience",
      "convenience_store",
      "chocolate_shop",
      "Convenience Store",
      "convenience",
      "Convenience Store",
      "Other Convenience Store",
      "Dairy Products",
      "600-6000-0061",
      "600-6000-0000",
      "600-6300-0364",
    ],
  },

  books: {
    name: () => t("Library"),
    icon: icons.library,
    parents: ["shopping"],
    synonyms: [
      "shop=books",
      "book_store",
      "librairie_papeterie",
      "College Bookstore",
      "College Library",
      "Bookstore",
      "Comic Shop",
      "Used Bookstore",
      "Other Book Shop",
      "Book Shop",
      "600-6700-0000",
      "600-6700-0087",
    ],
  },

  barber: {
    name: () => t("Barber"),
    icon: icons.hairdresser,
    parents: ["shopping"],
    synonyms: [
      "shop=hairdresser",
      "hair_care",
      "hair_salon",
      "Salon / Barbershop",
      "hairdresser",
    ],
  },

  electronics: {
    name: () => t("Electronics"),
    icon: icons.gaming,
    parents: ["shopping"],
    synonyms: [
      "shop=electronics",
      "electronics_store",
      "appliance_store",
      "Electronics Store",
      "Watch Shop",
      "Consumer Electronics Store",
      "Entertainment Electronics",
      "Electronics",
      "Large Domestic Appliances",
      "Repair Services",
      "Electrical Repair",
      "600-6500-0072",
      "600-6500-0076",
      "600-6500-0333",
      "600-6600-0085",
      "700-7400-0146",
      "700-7400-0365",
    ],
  },

  instruments: {
    name: () => t("Musical Instruments Store"),
    icon: icons.music,
    parents: ["shopping"],
    synonyms: ["shop=musical_instrument", "musical_instrument"],
  },

  jewelry: {
    name: () => t("Jewelry Store"),
    icon: icons.jewelryStore,
    parents: ["shopping"],
    synonyms: [
      "shop=jewelry",
      "jewelry_store",
      "jewelry_store",
      "Jewelry Store",
      "Flowers & Jewelry",
      "Jeweller",
      "600-6900-0101",
      "600-6900-0356",
    ],
  },

  shoes: {
    name: () => t("Shoe Store"),
    icon: icons.shoe,
    parents: ["shopping"],
    synonyms: [
      "shop=shoes",
      "shoe_store",
      "boot_store",
      "Shoe Store",
      "Shoe Repair",
      "Shoes & Footwear",
      "600-6800-0092",
    ],
  },

  car_dealer: {
    name: () => t("Car Dealer"),
    icon: icons.car,
    parents: ["shopping"],
    synonyms: [
      "shop=car",
      "car_dealer",
      "car_dealer",
      "Auto Dealership",
      "Automotive Shop",
      "car_shop",
      "New Car Dealership",
      "Used Car Dealership",
      "Motorcycle Dealership",
      "Truck Sales & Service",
      "Truck Dealership",
      "700-7800-0118",
      "700-7800-0119",
      "700-7800-0120",
      "700-7900-0000",
      "700-7900-0130",
    ],
  },

  clothes: {
    name: () => t("Clothing Store"),
    icon: icons.clothingStore,
    parents: ["shopping"],
    synonyms: [
      "shop=clothes",
      "clothing_store",
      "clothing_store",
      "Batik Shop",
      "Bridal Shop",
      "Clothing Store",
      "Clothing Store",
      "Accessories Store",
      "Boutique",
      "Kids Store",
      "Lingerie Store",
      "Men's Store",
      "Women's Store",
      "Costume Shop",
      "Leather Goods Store",
      "Clothing & Accessories",
      "Men's Clothing",
      "Women's Clothing",
      "Children's Clothing",
      "Specialty Clothing Store",
      "600-6800-0000",
      "600-6800-0089",
      "600-6800-0090",
      "600-6800-0091",
      "600-6800-0093",
    ],
  },

  furniture: {
    name: () => t("Furniture Store"),
    icon: icons.furniture,
    parents: ["shopping"],
    synonyms: [
      "shop=furniture",
      "furniture_store",
      "home_goods_store",
      "Furniture / Home Store",
      "Lighting Store",
      "Kitchen Supply Store",
      "Mattress Store",
      "Carpet Store",
      "Furniture & Home Accessories",
      "600-6600-0080",
    ],
  },

  chemist: {
    name: () => t("Drugstore"),
    icon: icons.pharmacy,
    parents: ["shopping"],
    synonyms: [
      "shop=chemist",
      "Cosmetics Shop",
      "Drugstore",
      "Chemist's",
      "600-6400-0069",
    ],
  },
} as const;
