import { t } from "@transifex/native";
import * as icons from "~/modules/categories/icons";

export const sport = {
  sport: {
    name: () => t("Sports"),
    icon: icons.soccer,
    synonyms: [
      "bowling_alley",
      "bowling_alley",
      "Bowling Alley",
      "Disc Golf",
      "Go Kart Track",
      "Mini Golf",
      "Bowling Green",
      "Golf Course",
      "Martial Arts Dojo",
      "Cycle Studio",
      "sport",
      "Public Sports Facility",
      "Ice Skating Rink",
      "Tennis Club",
      "Bowling Alley",
      "Indoor Skiing",
      "Shooting Gallery",
      "Squash Facility",
      "Indoor Sports",
      "Golf Course",
      "Golf Practice Range",
      "Sports Activities",
      "800-8600-0000",
      "800-8600-0191",
      "550-5510-0203",
      "800-8600-0181",
      "800-8600-0183",
      "800-8600-0184",
      "800-8600-0185",
      "800-8600-0188",
      "800-8600-0190",
      "800-8600-0192",
      "800-8600-0193",
      "800-8600-0194",
      "800-8600-0197",
    ],
  },

  sports_center: {
    name: () => t("Sports Center"),
    icon: icons.soccer,
    parents: ["sport"],
    synonyms: [
      "leisure=sports_centre",
      "leisure=sports_hall",
      "leisure=fitness_centre",
      "gym",
      "sports_complex",
      "College Gym",
      "College Rec Center",
      "Athletics & Sports",
      "Basketball Court",
      "Gym / Fitness Center",
      "Sports Facility or Venue",
      "fitness_center",
      "Fitness or Health Club",
      "Boxing Gym",
      "Climbing Gym",
      "Gymnastics Gym",
      "Gym",
      "Outdoor Gym",
      "Pilates Studio",
      "Yoga Studio",
      "Squash Court",
      "Volleyball Court",
      "Sports Club",
      "Rock Climbing Spot",
      "Ski Area",
      "Ski Chairlift",
      "Ski Trail",
      "Skydiving Drop Zone",
      "sports_centre",
      "Public Sports Facility",
      "Ice Skating Rink",
      "Tennis Club",
      "Bowling Alley",
      "Indoor Skiing",
      "Shooting Gallery",
      "Squash Facility",
      "Indoor Sports",
      "Golf Course",
      "Golf Practice Range",
      "Basketball",
      "Badminton",
      "Rugby",
      "Bike Park",
      "BMX Track",
      "550-5510-0203",
      "800-8600-0181",
      "800-8600-0183",
      "800-8600-0184",
      "800-8600-0185",
      "800-8600-0188",
      "800-8600-0190",
      "800-8600-0192",
      "800-8600-0193",
      "800-8600-0194",
      "800-8600-0199",
      "800-8600-0200",
      "800-8600-0314",
      "800-8600-0376",
      "800-8600-0377",
      "Sporthalle",
    ],
  },

  stadium: {
    name: () => t("Stadium"),
    icon: icons.stadium,
    parents: ["sport"],
    synonyms: [
      "leisure=stadium",
      "stadium",
      "stadium",
      "Stadium",
      "Baseball Stadium",
      "Basketball Stadium",
      "Cricket Ground",
      "Football Stadium",
      "Hockey Arena",
      "Rugby Stadium",
      "Soccer Stadium",
      "Tennis Stadium",
      "Track Stadium",
      "College Stadium",
      "College Baseball Diamond",
      "College Basketball Court",
      "College Cricket Pitch",
      "College Hockey Rink",
      "College Track",
      "Curling Ice",
      "Golf Driving Range",
      "Track",
      "Hockey Field",
      "Hockey Rink",
      "Sports Complex or Stadium",
      "Ice Hockey",
      "Racquetball Court",
      "Racetrack",
      "Running Track",
      "800-8600-0180",
      "800-8600-0186",
      "800-8600-0187",
      "800-8600-0195",
      "800-8600-0381",
      "Eisstadion",
      "Sportstadion",
    ],
  },

  soccer: {
    name: () => t("Playing Field"),
    icon: icons.soccer,
    parents: ["sport"],
    synonyms: [
      "leisure=pitch",
      "College Football Field",
      "College Soccer Field",
      "Outdoors & Recreation",
      "Soccer Field",
      "College Tennis Court",
      "Badminton Court",
      "Tennis Court",
      "Baseball Field",
      "pitch",
      "Football pitch",
      "800-8600-0189",
    ],
  },

  swimming: {
    name: () => t("Swimming Pool"),
    icon: icons.swimming,
    parents: ["sport"],
    synonyms: [
      "amenity=swimming_pool",
      "leisure=swimming_pool",
      "public_swimming_pool",
      "Gym Pool",
      "Bathing Area",
      "Pool",
      "Hotel Pool",
      "Swim School",
      "Dive Spot",
      "swimming_pool",
      "Water Park",
      "Swimming Pool",
      "Diving Centre",
      "550-5520-0357",
      "800-8600-0182",
      "800-8600-0316",
      "Schwimmbad",
    ],
  },
} as const;
