export const horizontalKeys = new Set([
  'payment',
  'internet_access',
  'diet',
  'health',
  'stay',
  'audience',
  'location',
  'look',
  'access',
  'handrail',
  'restrooms',
  'access',
  'internet',
  'means_of_transport',
  'amenities',
  'emergency',
])
