export const pathsToConsumedTagKeys: [string, RegExp][] = [
  ['building_object.type', /^building$/],
  ['look.$1', /^building:(colour|material)|height$/],
  ['building_object.$1', /^building:([\w_]+)$/],
  ['building_object.$1_level', /^(min|max)_level$/],
  ['payment.$1', /^payment:([\w_]+)$/],
  ['payment.$1.$2', /^payment:([\w_]+):([\w_]+)$/],
  ['payment.description.$1', /^description:payment:([\w_]+)$/],
  ['payment.description', /^description:payment$/],
  ['payment.fee', /^fee$/],
  ['payment.charge', /^charge$/],
  ['payment.charge.$1', /^charge:([\w_]+)$/],
  ['payment.charge.$1', /^([\w_]+):charge$/],
  ['diet.$1', /^diet:([\w_]+)$/],
  ['diet.cuisine', /^cuisine$/],
  ['stay.$1', /^(.*)_?seating$/],
  ['stay.takeaway', /^takeaway$/],
  ['stay.delivery', /^delivery$/],
  ['stay.offered', /^delivery$/],
  ['stay.partner', /^delivery:partner$/],
  ['stay.smoking', /^smoking$/],
  ['stay.air_conditioning', /^air_conditioning$/],
  ['internet.access', /^internet_access$/],
  ['internet.$1', /^internet_access:([\w_]+)$/],
  ['ramp.$1', /^ramp:([\w_]+)$/],
  ['handrail.$1', /^handrail:([\w_]+)$/],
  ['changing_table.$1', /^changing_table:([\w_]+)$/],
  ['entrance.door', /^door$/],
  ['entrance.automatic_door', /^automatic_door$/],
  ['entrance.door:$1', /^door:([\w_]+)$/],
  ['entrance.$1.door.automatic', /^automatic_door:([\w_]+)$/],
  ['entrance.step_count', /^step_count$/],
  ['entrance.step_height', /^wheelchair:step_height$/],
  ['entrance.width', /^wheelchair:entrance_width$/],
  ['$1', /^access:([\w_]+)$/],
  ['centralkey', /^centralkey$/],
  ['health.healthcare', /^healthcare$/],
  ['health.speciality', /^healthcare:speciality$/],
  ['health.dispensing', /^dispensing$/],
  ['capacity.$1', /^capacity:([\w_]+)$/],
  [
    'audience.$1',
    /^(unisex|male|female|child|gay|lgbtq|men|women|gay|lgbtq|queer|community_centre:for)$/,
  ],
  [
    'audience.$1.$2',
    /^(unisex|male|female|child|gay|lgbtq|men|women|gay|lgbtq|queer):(.*)$/,
  ],
  ['audience.$1', /^(social_facility|community_centre):for$/],
  ['toilets.$1', /^toilets:([\w_]+)$/],
  ['payment.fee:urinal', /^fee:urinal$/],
  ['information.tactile_writing.$1.$2', /^tactile_writing:([\w_]+):([\w_]+)$/],
  ['information.speech_output.$1', /^speech_output:([\w_]+)$/],
  ['information.speech_input.$1', /^speech_input:([\w_]+)$/],
  ['information.braille', /^braille$/],
  ['socket.$1.count', /^socket:([\w_]+)$/],
  ['socket.$1.$2', /^socket:([\w_]+):([\w_]+)$/],
  ['sidewalk.sidewalk:$1', /^sidewalk:([\w_]+)$/],
  ['sidewalk.sidewalk:$1.$2', /^sidewalk:([\w_]+):([\w_]+)$/],
  ['crossing.1', /^crossing$/],
  ['crossing.$1', /^crossing:([\w_]+)$/],
  ['description.$1', /^description:([\w_]+)$/],
  ['location.indoor', /^indoor$/],
  ['location.level', /^level$/],
  ['location.level_ref', /^level:ref$/],
  ['$1', /(.*)/],
]
