// flow-typed signature: 1bf75b0a1c5dd6955bff8edea5ecd4e2
// flow-typed version: <<STUB>>/babel_v^6.23.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel/lib/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel/index' {
  declare module.exports: $Exports<'babel'>;
}
declare module 'babel/index.js' {
  declare module.exports: $Exports<'babel'>;
}
declare module 'babel/lib/cli.js' {
  declare module.exports: $Exports<'babel/lib/cli'>;
}
