// flow-typed signature: d4cc76d12fb8099aa42b4067c552169d
// flow-typed version: <<STUB>>/babel-plugin-ttag_v^1.1.0-0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-ttag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-ttag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-ttag/dist/config' {
  declare module.exports: any;
}

declare module 'babel-plugin-ttag/dist/context' {
  declare module.exports: any;
}

declare module 'babel-plugin-ttag/dist/defaults' {
  declare module.exports: any;
}

declare module 'babel-plugin-ttag/dist/errors' {
  declare module.exports: any;
}

declare module 'babel-plugin-ttag/dist/extract' {
  declare module.exports: any;
}

declare module 'babel-plugin-ttag/dist/extractors/gettext' {
  declare module.exports: any;
}

declare module 'babel-plugin-ttag/dist/extractors/jsxtag-gettext' {
  declare module.exports: any;
}

declare module 'babel-plugin-ttag/dist/extractors/ngettext' {
  declare module.exports: any;
}

declare module 'babel-plugin-ttag/dist/extractors/tag-gettext' {
  declare module.exports: any;
}

declare module 'babel-plugin-ttag/dist/gettext-context' {
  declare module.exports: any;
}

declare module 'babel-plugin-ttag/dist/plugin' {
  declare module.exports: any;
}

declare module 'babel-plugin-ttag/dist/po-helpers' {
  declare module.exports: any;
}

declare module 'babel-plugin-ttag/dist/resolve' {
  declare module.exports: any;
}

declare module 'babel-plugin-ttag/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-ttag/dist/config.js' {
  declare module.exports: $Exports<'babel-plugin-ttag/dist/config'>;
}
declare module 'babel-plugin-ttag/dist/context.js' {
  declare module.exports: $Exports<'babel-plugin-ttag/dist/context'>;
}
declare module 'babel-plugin-ttag/dist/defaults.js' {
  declare module.exports: $Exports<'babel-plugin-ttag/dist/defaults'>;
}
declare module 'babel-plugin-ttag/dist/errors.js' {
  declare module.exports: $Exports<'babel-plugin-ttag/dist/errors'>;
}
declare module 'babel-plugin-ttag/dist/extract.js' {
  declare module.exports: $Exports<'babel-plugin-ttag/dist/extract'>;
}
declare module 'babel-plugin-ttag/dist/extractors/gettext.js' {
  declare module.exports: $Exports<'babel-plugin-ttag/dist/extractors/gettext'>;
}
declare module 'babel-plugin-ttag/dist/extractors/jsxtag-gettext.js' {
  declare module.exports: $Exports<'babel-plugin-ttag/dist/extractors/jsxtag-gettext'>;
}
declare module 'babel-plugin-ttag/dist/extractors/ngettext.js' {
  declare module.exports: $Exports<'babel-plugin-ttag/dist/extractors/ngettext'>;
}
declare module 'babel-plugin-ttag/dist/extractors/tag-gettext.js' {
  declare module.exports: $Exports<'babel-plugin-ttag/dist/extractors/tag-gettext'>;
}
declare module 'babel-plugin-ttag/dist/gettext-context.js' {
  declare module.exports: $Exports<'babel-plugin-ttag/dist/gettext-context'>;
}
declare module 'babel-plugin-ttag/dist/plugin.js' {
  declare module.exports: $Exports<'babel-plugin-ttag/dist/plugin'>;
}
declare module 'babel-plugin-ttag/dist/po-helpers.js' {
  declare module.exports: $Exports<'babel-plugin-ttag/dist/po-helpers'>;
}
declare module 'babel-plugin-ttag/dist/resolve.js' {
  declare module.exports: $Exports<'babel-plugin-ttag/dist/resolve'>;
}
declare module 'babel-plugin-ttag/dist/utils.js' {
  declare module.exports: $Exports<'babel-plugin-ttag/dist/utils'>;
}
