// flow-typed signature: efd3657ce652e413a04ee8d8377c791f
// flow-typed version: <<STUB>>/browser-image-resizer_v^1.2.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browser-image-resizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browser-image-resizer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browser-image-resizer/build/exif' {
  declare module.exports: any;
}

declare module 'browser-image-resizer/build/index' {
  declare module.exports: any;
}

declare module 'browser-image-resizer/src/exif' {
  declare module.exports: any;
}

declare module 'browser-image-resizer/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browser-image-resizer/build/exif.js' {
  declare module.exports: $Exports<'browser-image-resizer/build/exif'>;
}
declare module 'browser-image-resizer/build/index.js' {
  declare module.exports: $Exports<'browser-image-resizer/build/index'>;
}
declare module 'browser-image-resizer/src/exif.js' {
  declare module.exports: $Exports<'browser-image-resizer/src/exif'>;
}
declare module 'browser-image-resizer/src/index.js' {
  declare module.exports: $Exports<'browser-image-resizer/src/index'>;
}
