// flow-typed signature: 299bc8a38fda52852567b8881a77c2ad
// flow-typed version: <<STUB>>/browserstack-local_v^1.3.3/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browserstack-local'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browserstack-local' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browserstack-local/lib/Local' {
  declare module.exports: any;
}

declare module 'browserstack-local/lib/LocalBinary' {
  declare module.exports: any;
}

declare module 'browserstack-local/lib/LocalError' {
  declare module.exports: any;
}

declare module 'browserstack-local/node-example' {
  declare module.exports: any;
}

declare module 'browserstack-local/test/local' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browserstack-local/index' {
  declare module.exports: $Exports<'browserstack-local'>;
}
declare module 'browserstack-local/index.js' {
  declare module.exports: $Exports<'browserstack-local'>;
}
declare module 'browserstack-local/lib/Local.js' {
  declare module.exports: $Exports<'browserstack-local/lib/Local'>;
}
declare module 'browserstack-local/lib/LocalBinary.js' {
  declare module.exports: $Exports<'browserstack-local/lib/LocalBinary'>;
}
declare module 'browserstack-local/lib/LocalError.js' {
  declare module.exports: $Exports<'browserstack-local/lib/LocalError'>;
}
declare module 'browserstack-local/node-example.js' {
  declare module.exports: $Exports<'browserstack-local/node-example'>;
}
declare module 'browserstack-local/test/local.js' {
  declare module.exports: $Exports<'browserstack-local/test/local'>;
}
