// flow-typed signature: a6e6fcbfc12c20dfdf04c8916a98ec07
// flow-typed version: <<STUB>>/c-3po_v0.7.3/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'c-3po'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'c-3po' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'c-3po/dist/c3po' {
  declare module.exports: any;
}

declare module 'c-3po/dist/c3po.min' {
  declare module.exports: any;
}

declare module 'c-3po/dist/config' {
  declare module.exports: any;
}

declare module 'c-3po/dist/index' {
  declare module.exports: any;
}

declare module 'c-3po/dist/loader' {
  declare module.exports: any;
}

declare module 'c-3po/dist/mock' {
  declare module.exports: any;
}

declare module 'c-3po/dist/react-utils' {
  declare module.exports: any;
}

declare module 'c-3po/dist/utils' {
  declare module.exports: any;
}

declare module 'c-3po/dist/validation' {
  declare module.exports: any;
}

declare module 'c-3po/loader' {
  declare module.exports: any;
}

declare module 'c-3po/src/config' {
  declare module.exports: any;
}

declare module 'c-3po/src/index' {
  declare module.exports: any;
}

declare module 'c-3po/src/loader' {
  declare module.exports: any;
}

declare module 'c-3po/src/mock' {
  declare module.exports: any;
}

declare module 'c-3po/src/utils' {
  declare module.exports: any;
}

declare module 'c-3po/src/validation' {
  declare module.exports: any;
}

declare module 'c-3po/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'c-3po/dist/c3po.js' {
  declare module.exports: $Exports<'c-3po/dist/c3po'>;
}
declare module 'c-3po/dist/c3po.min.js' {
  declare module.exports: $Exports<'c-3po/dist/c3po.min'>;
}
declare module 'c-3po/dist/config.js' {
  declare module.exports: $Exports<'c-3po/dist/config'>;
}
declare module 'c-3po/dist/index.js' {
  declare module.exports: $Exports<'c-3po/dist/index'>;
}
declare module 'c-3po/dist/loader.js' {
  declare module.exports: $Exports<'c-3po/dist/loader'>;
}
declare module 'c-3po/dist/mock.js' {
  declare module.exports: $Exports<'c-3po/dist/mock'>;
}
declare module 'c-3po/dist/react-utils.js' {
  declare module.exports: $Exports<'c-3po/dist/react-utils'>;
}
declare module 'c-3po/dist/utils.js' {
  declare module.exports: $Exports<'c-3po/dist/utils'>;
}
declare module 'c-3po/dist/validation.js' {
  declare module.exports: $Exports<'c-3po/dist/validation'>;
}
declare module 'c-3po/loader.js' {
  declare module.exports: $Exports<'c-3po/loader'>;
}
declare module 'c-3po/src/config.js' {
  declare module.exports: $Exports<'c-3po/src/config'>;
}
declare module 'c-3po/src/index.js' {
  declare module.exports: $Exports<'c-3po/src/index'>;
}
declare module 'c-3po/src/loader.js' {
  declare module.exports: $Exports<'c-3po/src/loader'>;
}
declare module 'c-3po/src/mock.js' {
  declare module.exports: $Exports<'c-3po/src/mock'>;
}
declare module 'c-3po/src/utils.js' {
  declare module.exports: $Exports<'c-3po/src/utils'>;
}
declare module 'c-3po/src/validation.js' {
  declare module.exports: $Exports<'c-3po/src/validation'>;
}
declare module 'c-3po/webpack.config.js' {
  declare module.exports: $Exports<'c-3po/webpack.config'>;
}
