// flow-typed signature: 5006f71c91b5ecfd497123f2dd54d96c
// flow-typed version: <<STUB>>/cheerio_v^0.19.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cheerio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cheerio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cheerio/lib/api/attributes' {
  declare module.exports: any;
}

declare module 'cheerio/lib/api/css' {
  declare module.exports: any;
}

declare module 'cheerio/lib/api/forms' {
  declare module.exports: any;
}

declare module 'cheerio/lib/api/manipulation' {
  declare module.exports: any;
}

declare module 'cheerio/lib/api/traversing' {
  declare module.exports: any;
}

declare module 'cheerio/lib/cheerio' {
  declare module.exports: any;
}

declare module 'cheerio/lib/parse' {
  declare module.exports: any;
}

declare module 'cheerio/lib/static' {
  declare module.exports: any;
}

declare module 'cheerio/lib/utils' {
  declare module.exports: any;
}

declare module 'cheerio/test/api/attributes' {
  declare module.exports: any;
}

declare module 'cheerio/test/api/css' {
  declare module.exports: any;
}

declare module 'cheerio/test/api/forms' {
  declare module.exports: any;
}

declare module 'cheerio/test/api/manipulation' {
  declare module.exports: any;
}

declare module 'cheerio/test/api/traversing' {
  declare module.exports: any;
}

declare module 'cheerio/test/api/utils' {
  declare module.exports: any;
}

declare module 'cheerio/test/cheerio' {
  declare module.exports: any;
}

declare module 'cheerio/test/fixtures' {
  declare module.exports: any;
}

declare module 'cheerio/test/parse' {
  declare module.exports: any;
}

declare module 'cheerio/test/xml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cheerio/index' {
  declare module.exports: $Exports<'cheerio'>;
}
declare module 'cheerio/index.js' {
  declare module.exports: $Exports<'cheerio'>;
}
declare module 'cheerio/lib/api/attributes.js' {
  declare module.exports: $Exports<'cheerio/lib/api/attributes'>;
}
declare module 'cheerio/lib/api/css.js' {
  declare module.exports: $Exports<'cheerio/lib/api/css'>;
}
declare module 'cheerio/lib/api/forms.js' {
  declare module.exports: $Exports<'cheerio/lib/api/forms'>;
}
declare module 'cheerio/lib/api/manipulation.js' {
  declare module.exports: $Exports<'cheerio/lib/api/manipulation'>;
}
declare module 'cheerio/lib/api/traversing.js' {
  declare module.exports: $Exports<'cheerio/lib/api/traversing'>;
}
declare module 'cheerio/lib/cheerio.js' {
  declare module.exports: $Exports<'cheerio/lib/cheerio'>;
}
declare module 'cheerio/lib/parse.js' {
  declare module.exports: $Exports<'cheerio/lib/parse'>;
}
declare module 'cheerio/lib/static.js' {
  declare module.exports: $Exports<'cheerio/lib/static'>;
}
declare module 'cheerio/lib/utils.js' {
  declare module.exports: $Exports<'cheerio/lib/utils'>;
}
declare module 'cheerio/test/api/attributes.js' {
  declare module.exports: $Exports<'cheerio/test/api/attributes'>;
}
declare module 'cheerio/test/api/css.js' {
  declare module.exports: $Exports<'cheerio/test/api/css'>;
}
declare module 'cheerio/test/api/forms.js' {
  declare module.exports: $Exports<'cheerio/test/api/forms'>;
}
declare module 'cheerio/test/api/manipulation.js' {
  declare module.exports: $Exports<'cheerio/test/api/manipulation'>;
}
declare module 'cheerio/test/api/traversing.js' {
  declare module.exports: $Exports<'cheerio/test/api/traversing'>;
}
declare module 'cheerio/test/api/utils.js' {
  declare module.exports: $Exports<'cheerio/test/api/utils'>;
}
declare module 'cheerio/test/cheerio.js' {
  declare module.exports: $Exports<'cheerio/test/cheerio'>;
}
declare module 'cheerio/test/fixtures.js' {
  declare module.exports: $Exports<'cheerio/test/fixtures'>;
}
declare module 'cheerio/test/parse.js' {
  declare module.exports: $Exports<'cheerio/test/parse'>;
}
declare module 'cheerio/test/xml.js' {
  declare module.exports: $Exports<'cheerio/test/xml'>;
}
