// flow-typed signature: bb405e52aabfc6b2826d683588cc85db
// flow-typed version: <<STUB>>/cordova-plugin-geolocation_v^4.0.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-plugin-geolocation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-plugin-geolocation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova-plugin-geolocation/src/windows/GeolocationProxy' {
  declare module.exports: any;
}

declare module 'cordova-plugin-geolocation/tests/tests' {
  declare module.exports: any;
}

declare module 'cordova-plugin-geolocation/www/android/geolocation' {
  declare module.exports: any;
}

declare module 'cordova-plugin-geolocation/www/Coordinates' {
  declare module.exports: any;
}

declare module 'cordova-plugin-geolocation/www/geolocation' {
  declare module.exports: any;
}

declare module 'cordova-plugin-geolocation/www/Position' {
  declare module.exports: any;
}

declare module 'cordova-plugin-geolocation/www/PositionError' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova-plugin-geolocation/src/windows/GeolocationProxy.js' {
  declare module.exports: $Exports<'cordova-plugin-geolocation/src/windows/GeolocationProxy'>;
}
declare module 'cordova-plugin-geolocation/tests/tests.js' {
  declare module.exports: $Exports<'cordova-plugin-geolocation/tests/tests'>;
}
declare module 'cordova-plugin-geolocation/www/android/geolocation.js' {
  declare module.exports: $Exports<'cordova-plugin-geolocation/www/android/geolocation'>;
}
declare module 'cordova-plugin-geolocation/www/Coordinates.js' {
  declare module.exports: $Exports<'cordova-plugin-geolocation/www/Coordinates'>;
}
declare module 'cordova-plugin-geolocation/www/geolocation.js' {
  declare module.exports: $Exports<'cordova-plugin-geolocation/www/geolocation'>;
}
declare module 'cordova-plugin-geolocation/www/Position.js' {
  declare module.exports: $Exports<'cordova-plugin-geolocation/www/Position'>;
}
declare module 'cordova-plugin-geolocation/www/PositionError.js' {
  declare module.exports: $Exports<'cordova-plugin-geolocation/www/PositionError'>;
}
