// flow-typed signature: 79057d5289b131f9c911d74f4f7a0efa
// flow-typed version: <<STUB>>/cordova-plugin-whitelist_v~1.3.3/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-plugin-whitelist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-plugin-whitelist' {
  declare module.exports: any;
}
