// flow-typed signature: cdf79eb0b26068e7fc2875200b5ae4cd
// flow-typed version: <<STUB>>/cordova-plugin-advanced-http_v^1.11.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-plugin-advanced-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-plugin-advanced-http' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova-plugin-advanced-http/src/browser/cordova-http-plugin' {
  declare module.exports: any;
}

declare module 'cordova-plugin-advanced-http/www/advanced-http' {
  declare module.exports: any;
}

declare module 'cordova-plugin-advanced-http/www/angular-integration' {
  declare module.exports: any;
}

declare module 'cordova-plugin-advanced-http/www/cookie-handler' {
  declare module.exports: any;
}

declare module 'cordova-plugin-advanced-http/www/helpers' {
  declare module.exports: any;
}

declare module 'cordova-plugin-advanced-http/www/local-storage-store' {
  declare module.exports: any;
}

declare module 'cordova-plugin-advanced-http/www/lodash' {
  declare module.exports: any;
}

declare module 'cordova-plugin-advanced-http/www/messages' {
  declare module.exports: any;
}

declare module 'cordova-plugin-advanced-http/www/umd-tough-cookie' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova-plugin-advanced-http/src/browser/cordova-http-plugin.js' {
  declare module.exports: $Exports<'cordova-plugin-advanced-http/src/browser/cordova-http-plugin'>;
}
declare module 'cordova-plugin-advanced-http/www/advanced-http.js' {
  declare module.exports: $Exports<'cordova-plugin-advanced-http/www/advanced-http'>;
}
declare module 'cordova-plugin-advanced-http/www/angular-integration.js' {
  declare module.exports: $Exports<'cordova-plugin-advanced-http/www/angular-integration'>;
}
declare module 'cordova-plugin-advanced-http/www/cookie-handler.js' {
  declare module.exports: $Exports<'cordova-plugin-advanced-http/www/cookie-handler'>;
}
declare module 'cordova-plugin-advanced-http/www/helpers.js' {
  declare module.exports: $Exports<'cordova-plugin-advanced-http/www/helpers'>;
}
declare module 'cordova-plugin-advanced-http/www/local-storage-store.js' {
  declare module.exports: $Exports<'cordova-plugin-advanced-http/www/local-storage-store'>;
}
declare module 'cordova-plugin-advanced-http/www/lodash.js' {
  declare module.exports: $Exports<'cordova-plugin-advanced-http/www/lodash'>;
}
declare module 'cordova-plugin-advanced-http/www/messages.js' {
  declare module.exports: $Exports<'cordova-plugin-advanced-http/www/messages'>;
}
declare module 'cordova-plugin-advanced-http/www/umd-tough-cookie.js' {
  declare module.exports: $Exports<'cordova-plugin-advanced-http/www/umd-tough-cookie'>;
}
