// flow-typed signature: 58471e5f925ec7910c8fd456aaf813e2
// flow-typed version: <<STUB>>/cordova-plugin-wkwebview-engine_v~1.1.4/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-plugin-wkwebview-engine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-plugin-wkwebview-engine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova-plugin-wkwebview-engine/src/www/ios/ios-wkwebview-exec' {
  declare module.exports: any;
}

declare module 'cordova-plugin-wkwebview-engine/src/www/ios/ios-wkwebview' {
  declare module.exports: any;
}

declare module 'cordova-plugin-wkwebview-engine/tests/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova-plugin-wkwebview-engine/src/www/ios/ios-wkwebview-exec.js' {
  declare module.exports: $Exports<'cordova-plugin-wkwebview-engine/src/www/ios/ios-wkwebview-exec'>;
}
declare module 'cordova-plugin-wkwebview-engine/src/www/ios/ios-wkwebview.js' {
  declare module.exports: $Exports<'cordova-plugin-wkwebview-engine/src/www/ios/ios-wkwebview'>;
}
declare module 'cordova-plugin-wkwebview-engine/tests/tests.js' {
  declare module.exports: $Exports<'cordova-plugin-wkwebview-engine/tests/tests'>;
}
