// flow-typed signature: 5ab391a0022285a3b988cef88c713f04
// flow-typed version: <<STUB>>/cordova-plugin-device_v^2.0.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-plugin-device'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-plugin-device' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova-plugin-device/src/browser/DeviceProxy' {
  declare module.exports: any;
}

declare module 'cordova-plugin-device/src/windows/DeviceProxy' {
  declare module.exports: any;
}

declare module 'cordova-plugin-device/tests/tests' {
  declare module.exports: any;
}

declare module 'cordova-plugin-device/www/device' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova-plugin-device/src/browser/DeviceProxy.js' {
  declare module.exports: $Exports<'cordova-plugin-device/src/browser/DeviceProxy'>;
}
declare module 'cordova-plugin-device/src/windows/DeviceProxy.js' {
  declare module.exports: $Exports<'cordova-plugin-device/src/windows/DeviceProxy'>;
}
declare module 'cordova-plugin-device/tests/tests.js' {
  declare module.exports: $Exports<'cordova-plugin-device/tests/tests'>;
}
declare module 'cordova-plugin-device/www/device.js' {
  declare module.exports: $Exports<'cordova-plugin-device/www/device'>;
}
