// flow-typed signature: b57526b581429e6f75293582025d56d8
// flow-typed version: <<STUB>>/cordova-version-sync_v^1.0.3/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-version-sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-version-sync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'cordova-version-sync/index' {
  declare module.exports: $Exports<'cordova-version-sync'>;
}
declare module 'cordova-version-sync/index.js' {
  declare module.exports: $Exports<'cordova-version-sync'>;
}
