// flow-typed signature: ba5984eb99bfb58545e7a348c81e01ae
// flow-typed version: <<STUB>>/cordova_v^8.1.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova/cordova' {
  declare module.exports: any;
}

declare module 'cordova/src/cli' {
  declare module.exports: any;
}

declare module 'cordova/src/help' {
  declare module.exports: any;
}

declare module 'cordova/src/telemetry' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova/cordova.js' {
  declare module.exports: $Exports<'cordova/cordova'>;
}
declare module 'cordova/src/cli.js' {
  declare module.exports: $Exports<'cordova/src/cli'>;
}
declare module 'cordova/src/help.js' {
  declare module.exports: $Exports<'cordova/src/help'>;
}
declare module 'cordova/src/telemetry.js' {
  declare module.exports: $Exports<'cordova/src/telemetry'>;
}
