// flow-typed signature: 166c739162fe0a84eda44660244e14c4
// flow-typed version: <<STUB>>/cordova-plugin-file_v^6.0.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-plugin-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-plugin-file' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova-plugin-file/src/browser/FileProxy' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/src/windows/FileProxy' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/tests/tests' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/android/FileSystem' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/browser/FileSystem' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/browser/isChrome' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/browser/Preparing' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/DirectoryEntry' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/DirectoryReader' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/Entry' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/File' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/FileEntry' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/FileError' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/FileReader' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/FileSystem' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/fileSystemPaths' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/fileSystems-roots' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/fileSystems' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/FileUploadOptions' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/FileUploadResult' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/FileWriter' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/Flags' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/ios/FileSystem' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/LocalFileSystem' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/Metadata' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/osx/FileSystem' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/ProgressEvent' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/requestFileSystem' {
  declare module.exports: any;
}

declare module 'cordova-plugin-file/www/resolveLocalFileSystemURI' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova-plugin-file/src/browser/FileProxy.js' {
  declare module.exports: $Exports<'cordova-plugin-file/src/browser/FileProxy'>;
}
declare module 'cordova-plugin-file/src/windows/FileProxy.js' {
  declare module.exports: $Exports<'cordova-plugin-file/src/windows/FileProxy'>;
}
declare module 'cordova-plugin-file/tests/tests.js' {
  declare module.exports: $Exports<'cordova-plugin-file/tests/tests'>;
}
declare module 'cordova-plugin-file/www/android/FileSystem.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/android/FileSystem'>;
}
declare module 'cordova-plugin-file/www/browser/FileSystem.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/browser/FileSystem'>;
}
declare module 'cordova-plugin-file/www/browser/isChrome.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/browser/isChrome'>;
}
declare module 'cordova-plugin-file/www/browser/Preparing.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/browser/Preparing'>;
}
declare module 'cordova-plugin-file/www/DirectoryEntry.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/DirectoryEntry'>;
}
declare module 'cordova-plugin-file/www/DirectoryReader.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/DirectoryReader'>;
}
declare module 'cordova-plugin-file/www/Entry.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/Entry'>;
}
declare module 'cordova-plugin-file/www/File.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/File'>;
}
declare module 'cordova-plugin-file/www/FileEntry.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/FileEntry'>;
}
declare module 'cordova-plugin-file/www/FileError.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/FileError'>;
}
declare module 'cordova-plugin-file/www/FileReader.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/FileReader'>;
}
declare module 'cordova-plugin-file/www/FileSystem.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/FileSystem'>;
}
declare module 'cordova-plugin-file/www/fileSystemPaths.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/fileSystemPaths'>;
}
declare module 'cordova-plugin-file/www/fileSystems-roots.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/fileSystems-roots'>;
}
declare module 'cordova-plugin-file/www/fileSystems.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/fileSystems'>;
}
declare module 'cordova-plugin-file/www/FileUploadOptions.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/FileUploadOptions'>;
}
declare module 'cordova-plugin-file/www/FileUploadResult.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/FileUploadResult'>;
}
declare module 'cordova-plugin-file/www/FileWriter.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/FileWriter'>;
}
declare module 'cordova-plugin-file/www/Flags.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/Flags'>;
}
declare module 'cordova-plugin-file/www/ios/FileSystem.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/ios/FileSystem'>;
}
declare module 'cordova-plugin-file/www/LocalFileSystem.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/LocalFileSystem'>;
}
declare module 'cordova-plugin-file/www/Metadata.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/Metadata'>;
}
declare module 'cordova-plugin-file/www/osx/FileSystem.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/osx/FileSystem'>;
}
declare module 'cordova-plugin-file/www/ProgressEvent.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/ProgressEvent'>;
}
declare module 'cordova-plugin-file/www/requestFileSystem.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/requestFileSystem'>;
}
declare module 'cordova-plugin-file/www/resolveLocalFileSystemURI.js' {
  declare module.exports: $Exports<'cordova-plugin-file/www/resolveLocalFileSystemURI'>;
}
