// flow-typed signature: 718900a548c5c96c49a20be25723d032
// flow-typed version: <<STUB>>/cordova-plugin-statusbar_v~2.3.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-plugin-statusbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-plugin-statusbar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova-plugin-statusbar/src/browser/StatusBarProxy' {
  declare module.exports: any;
}

declare module 'cordova-plugin-statusbar/src/windows/StatusBarProxy' {
  declare module.exports: any;
}

declare module 'cordova-plugin-statusbar/tests/tests' {
  declare module.exports: any;
}

declare module 'cordova-plugin-statusbar/www/statusbar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova-plugin-statusbar/src/browser/StatusBarProxy.js' {
  declare module.exports: $Exports<'cordova-plugin-statusbar/src/browser/StatusBarProxy'>;
}
declare module 'cordova-plugin-statusbar/src/windows/StatusBarProxy.js' {
  declare module.exports: $Exports<'cordova-plugin-statusbar/src/windows/StatusBarProxy'>;
}
declare module 'cordova-plugin-statusbar/tests/tests.js' {
  declare module.exports: $Exports<'cordova-plugin-statusbar/tests/tests'>;
}
declare module 'cordova-plugin-statusbar/www/statusbar.js' {
  declare module.exports: $Exports<'cordova-plugin-statusbar/www/statusbar'>;
}
