// flow-typed signature: c02e2123df0e5a435a4571a81fe07347
// flow-typed version: <<STUB>>/cordova-ios_v^4.5.4/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-ios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-ios' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova-ios/bin/lib/create' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/project/www/js/index' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/Api' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/build' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/check_reqs' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/clean' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/copy-www-build-step' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/plugman/pluginHandlers' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/Podfile' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/PodsJson' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/prepare' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/projectFile' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/run' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/spawn' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/lib/versions' {
  declare module.exports: any;
}

declare module 'cordova-ios/bin/templates/scripts/cordova/loggingHelper' {
  declare module.exports: any;
}

declare module 'cordova-ios/cordova-js-src/exec' {
  declare module.exports: any;
}

declare module 'cordova-ios/cordova-js-src/platform' {
  declare module.exports: any;
}

declare module 'cordova-ios/cordova-js-src/plugin/ios/console' {
  declare module.exports: any;
}

declare module 'cordova-ios/cordova-js-src/plugin/ios/logger' {
  declare module.exports: any;
}

declare module 'cordova-ios/CordovaLib/cordova' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/scripts/killsim' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/create.spec' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/Api.spec' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/build.spec' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-json/empty' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-json/single-2xanyany' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-json/typical-universal' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-json/varied-device' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-map/empty-map' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-map/single-2xanyany-map' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-map/typical-universal-map' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-map/varied-device-map' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/fixtures/org.test.plugins.dummyplugin/www/dummyplugin' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/fixtures/sample-cocoapod-plugin-no-spec-overlapping-dependency/www/test' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/fixtures/sample-cordova-plugin-with-spec/www/test' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/lib/list-devices.spec' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/lib/list-emulator-images.spec' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/lib/run.spec' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/Plugman/common.spec' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/Plugman/pluginHandler.spec' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/Podfile.spec' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/PodsJson.spec' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/prepare.spec' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/preparePlatform.spec' {
  declare module.exports: any;
}

declare module 'cordova-ios/tests/spec/unit/projectFile.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova-ios/bin/lib/create.js' {
  declare module.exports: $Exports<'cordova-ios/bin/lib/create'>;
}
declare module 'cordova-ios/bin/templates/project/www/js/index.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/project/www/js/index'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/Api.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/Api'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/build.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/build'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/check_reqs.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/check_reqs'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/clean.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/clean'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/copy-www-build-step.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/copy-www-build-step'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/plugman/pluginHandlers.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/plugman/pluginHandlers'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/Podfile.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/Podfile'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/PodsJson.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/PodsJson'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/prepare.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/prepare'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/projectFile.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/projectFile'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/run.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/run'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/spawn.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/spawn'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/lib/versions.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/lib/versions'>;
}
declare module 'cordova-ios/bin/templates/scripts/cordova/loggingHelper.js' {
  declare module.exports: $Exports<'cordova-ios/bin/templates/scripts/cordova/loggingHelper'>;
}
declare module 'cordova-ios/cordova-js-src/exec.js' {
  declare module.exports: $Exports<'cordova-ios/cordova-js-src/exec'>;
}
declare module 'cordova-ios/cordova-js-src/platform.js' {
  declare module.exports: $Exports<'cordova-ios/cordova-js-src/platform'>;
}
declare module 'cordova-ios/cordova-js-src/plugin/ios/console.js' {
  declare module.exports: $Exports<'cordova-ios/cordova-js-src/plugin/ios/console'>;
}
declare module 'cordova-ios/cordova-js-src/plugin/ios/logger.js' {
  declare module.exports: $Exports<'cordova-ios/cordova-js-src/plugin/ios/logger'>;
}
declare module 'cordova-ios/CordovaLib/cordova.js' {
  declare module.exports: $Exports<'cordova-ios/CordovaLib/cordova'>;
}
declare module 'cordova-ios/tests/scripts/killsim.js' {
  declare module.exports: $Exports<'cordova-ios/tests/scripts/killsim'>;
}
declare module 'cordova-ios/tests/spec/create.spec.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/create.spec'>;
}
declare module 'cordova-ios/tests/spec/unit/Api.spec.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/Api.spec'>;
}
declare module 'cordova-ios/tests/spec/unit/build.spec.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/build.spec'>;
}
declare module 'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-json/empty.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-json/empty'>;
}
declare module 'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-json/single-2xanyany.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-json/single-2xanyany'>;
}
declare module 'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-json/typical-universal.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-json/typical-universal'>;
}
declare module 'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-json/varied-device.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-json/varied-device'>;
}
declare module 'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-map/empty-map.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-map/empty-map'>;
}
declare module 'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-map/single-2xanyany-map.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-map/single-2xanyany-map'>;
}
declare module 'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-map/typical-universal-map.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-map/typical-universal-map'>;
}
declare module 'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-map/varied-device-map.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/fixtures/launch-storyboard-support/contents-map/varied-device-map'>;
}
declare module 'cordova-ios/tests/spec/unit/fixtures/org.test.plugins.dummyplugin/www/dummyplugin.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/fixtures/org.test.plugins.dummyplugin/www/dummyplugin'>;
}
declare module 'cordova-ios/tests/spec/unit/fixtures/sample-cocoapod-plugin-no-spec-overlapping-dependency/www/test.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/fixtures/sample-cocoapod-plugin-no-spec-overlapping-dependency/www/test'>;
}
declare module 'cordova-ios/tests/spec/unit/fixtures/sample-cordova-plugin-with-spec/www/test.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/fixtures/sample-cordova-plugin-with-spec/www/test'>;
}
declare module 'cordova-ios/tests/spec/unit/lib/list-devices.spec.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/lib/list-devices.spec'>;
}
declare module 'cordova-ios/tests/spec/unit/lib/list-emulator-images.spec.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/lib/list-emulator-images.spec'>;
}
declare module 'cordova-ios/tests/spec/unit/lib/run.spec.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/lib/run.spec'>;
}
declare module 'cordova-ios/tests/spec/unit/Plugman/common.spec.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/Plugman/common.spec'>;
}
declare module 'cordova-ios/tests/spec/unit/Plugman/pluginHandler.spec.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/Plugman/pluginHandler.spec'>;
}
declare module 'cordova-ios/tests/spec/unit/Podfile.spec.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/Podfile.spec'>;
}
declare module 'cordova-ios/tests/spec/unit/PodsJson.spec.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/PodsJson.spec'>;
}
declare module 'cordova-ios/tests/spec/unit/prepare.spec.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/prepare.spec'>;
}
declare module 'cordova-ios/tests/spec/unit/preparePlatform.spec.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/preparePlatform.spec'>;
}
declare module 'cordova-ios/tests/spec/unit/projectFile.spec.js' {
  declare module.exports: $Exports<'cordova-ios/tests/spec/unit/projectFile.spec'>;
}
