// flow-typed signature: ed6e2d5803a52fc5c5ae9184dd53b66d
// flow-typed version: <<STUB>>/cordova-android_v^7.1.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cordova-android'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cordova-android' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cordova-android/bin/lib/create' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/Api' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/Adb' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/android_sdk' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/AndroidManifest' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/AndroidProject' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/AndroidStudio' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/build' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/builders/builders' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/builders/GenericBuilder' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/builders/GradleBuilder' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/builders/StudioBuilder' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/check_reqs' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/device' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/emulator' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/log' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/pluginHandlers' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/prepare' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/retry' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/lib/run' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/cordova/loggingHelper' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/project/assets/www/cordova' {
  declare module.exports: any;
}

declare module 'cordova-android/bin/templates/project/assets/www/js/index' {
  declare module.exports: any;
}

declare module 'cordova-android/cordova-js-src/android/nativeapiprovider' {
  declare module.exports: any;
}

declare module 'cordova-android/cordova-js-src/android/promptbasednativeapi' {
  declare module.exports: any;
}

declare module 'cordova-android/cordova-js-src/exec' {
  declare module.exports: any;
}

declare module 'cordova-android/cordova-js-src/platform' {
  declare module.exports: any;
}

declare module 'cordova-android/cordova-js-src/plugin/android/app' {
  declare module.exports: any;
}

declare module 'cordova-android/spec/e2e/helpers/projectActions' {
  declare module.exports: any;
}

declare module 'cordova-android/spec/e2e/plugin.spec' {
  declare module.exports: any;
}

declare module 'cordova-android/spec/fixtures/org.test.plugins.dummyplugin/www/dummyplugin' {
  declare module.exports: any;
}

declare module 'cordova-android/spec/unit/android_sdk.spec' {
  declare module.exports: any;
}

declare module 'cordova-android/spec/unit/AndroidProject.spec' {
  declare module.exports: any;
}

declare module 'cordova-android/spec/unit/AndroidStudio.spec' {
  declare module.exports: any;
}

declare module 'cordova-android/spec/unit/Api.spec' {
  declare module.exports: any;
}

declare module 'cordova-android/spec/unit/builders/GradleBuilder.spec' {
  declare module.exports: any;
}

declare module 'cordova-android/spec/unit/check_reqs.spec' {
  declare module.exports: any;
}

declare module 'cordova-android/spec/unit/create.spec' {
  declare module.exports: any;
}

declare module 'cordova-android/spec/unit/emulator.spec' {
  declare module.exports: any;
}

declare module 'cordova-android/spec/unit/pluginHandlers/common.spec' {
  declare module.exports: any;
}

declare module 'cordova-android/spec/unit/pluginHandlers/handlers.spec' {
  declare module.exports: any;
}

declare module 'cordova-android/spec/unit/run.spec' {
  declare module.exports: any;
}

declare module 'cordova-android/test/app/src/main/assets/www/cordova_plugins' {
  declare module.exports: any;
}

declare module 'cordova-android/test/app/src/main/assets/www/cordova' {
  declare module.exports: any;
}

declare module 'cordova-android/test/app/src/main/assets/www/main' {
  declare module.exports: any;
}

declare module 'cordova-android/test/run_java_unit_tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cordova-android/bin/lib/create.js' {
  declare module.exports: $Exports<'cordova-android/bin/lib/create'>;
}
declare module 'cordova-android/bin/templates/cordova/Api.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/Api'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/Adb.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/Adb'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/android_sdk.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/android_sdk'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/AndroidManifest.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/AndroidManifest'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/AndroidProject.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/AndroidProject'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/AndroidStudio.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/AndroidStudio'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/build.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/build'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/builders/builders.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/builders/builders'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/builders/GenericBuilder.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/builders/GenericBuilder'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/builders/GradleBuilder.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/builders/GradleBuilder'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/builders/StudioBuilder.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/builders/StudioBuilder'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/check_reqs.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/check_reqs'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/device.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/device'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/emulator.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/emulator'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/log.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/log'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/pluginHandlers.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/pluginHandlers'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/prepare.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/prepare'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/retry.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/retry'>;
}
declare module 'cordova-android/bin/templates/cordova/lib/run.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/lib/run'>;
}
declare module 'cordova-android/bin/templates/cordova/loggingHelper.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/cordova/loggingHelper'>;
}
declare module 'cordova-android/bin/templates/project/assets/www/cordova.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/project/assets/www/cordova'>;
}
declare module 'cordova-android/bin/templates/project/assets/www/js/index.js' {
  declare module.exports: $Exports<'cordova-android/bin/templates/project/assets/www/js/index'>;
}
declare module 'cordova-android/cordova-js-src/android/nativeapiprovider.js' {
  declare module.exports: $Exports<'cordova-android/cordova-js-src/android/nativeapiprovider'>;
}
declare module 'cordova-android/cordova-js-src/android/promptbasednativeapi.js' {
  declare module.exports: $Exports<'cordova-android/cordova-js-src/android/promptbasednativeapi'>;
}
declare module 'cordova-android/cordova-js-src/exec.js' {
  declare module.exports: $Exports<'cordova-android/cordova-js-src/exec'>;
}
declare module 'cordova-android/cordova-js-src/platform.js' {
  declare module.exports: $Exports<'cordova-android/cordova-js-src/platform'>;
}
declare module 'cordova-android/cordova-js-src/plugin/android/app.js' {
  declare module.exports: $Exports<'cordova-android/cordova-js-src/plugin/android/app'>;
}
declare module 'cordova-android/spec/e2e/helpers/projectActions.js' {
  declare module.exports: $Exports<'cordova-android/spec/e2e/helpers/projectActions'>;
}
declare module 'cordova-android/spec/e2e/plugin.spec.js' {
  declare module.exports: $Exports<'cordova-android/spec/e2e/plugin.spec'>;
}
declare module 'cordova-android/spec/fixtures/org.test.plugins.dummyplugin/www/dummyplugin.js' {
  declare module.exports: $Exports<'cordova-android/spec/fixtures/org.test.plugins.dummyplugin/www/dummyplugin'>;
}
declare module 'cordova-android/spec/unit/android_sdk.spec.js' {
  declare module.exports: $Exports<'cordova-android/spec/unit/android_sdk.spec'>;
}
declare module 'cordova-android/spec/unit/AndroidProject.spec.js' {
  declare module.exports: $Exports<'cordova-android/spec/unit/AndroidProject.spec'>;
}
declare module 'cordova-android/spec/unit/AndroidStudio.spec.js' {
  declare module.exports: $Exports<'cordova-android/spec/unit/AndroidStudio.spec'>;
}
declare module 'cordova-android/spec/unit/Api.spec.js' {
  declare module.exports: $Exports<'cordova-android/spec/unit/Api.spec'>;
}
declare module 'cordova-android/spec/unit/builders/GradleBuilder.spec.js' {
  declare module.exports: $Exports<'cordova-android/spec/unit/builders/GradleBuilder.spec'>;
}
declare module 'cordova-android/spec/unit/check_reqs.spec.js' {
  declare module.exports: $Exports<'cordova-android/spec/unit/check_reqs.spec'>;
}
declare module 'cordova-android/spec/unit/create.spec.js' {
  declare module.exports: $Exports<'cordova-android/spec/unit/create.spec'>;
}
declare module 'cordova-android/spec/unit/emulator.spec.js' {
  declare module.exports: $Exports<'cordova-android/spec/unit/emulator.spec'>;
}
declare module 'cordova-android/spec/unit/pluginHandlers/common.spec.js' {
  declare module.exports: $Exports<'cordova-android/spec/unit/pluginHandlers/common.spec'>;
}
declare module 'cordova-android/spec/unit/pluginHandlers/handlers.spec.js' {
  declare module.exports: $Exports<'cordova-android/spec/unit/pluginHandlers/handlers.spec'>;
}
declare module 'cordova-android/spec/unit/run.spec.js' {
  declare module.exports: $Exports<'cordova-android/spec/unit/run.spec'>;
}
declare module 'cordova-android/test/app/src/main/assets/www/cordova_plugins.js' {
  declare module.exports: $Exports<'cordova-android/test/app/src/main/assets/www/cordova_plugins'>;
}
declare module 'cordova-android/test/app/src/main/assets/www/cordova.js' {
  declare module.exports: $Exports<'cordova-android/test/app/src/main/assets/www/cordova'>;
}
declare module 'cordova-android/test/app/src/main/assets/www/main.js' {
  declare module.exports: $Exports<'cordova-android/test/app/src/main/assets/www/main'>;
}
declare module 'cordova-android/test/run_java_unit_tests.js' {
  declare module.exports: $Exports<'cordova-android/test/run_java_unit_tests'>;
}
