// flow-typed signature: 1a6f0701f3a07f1a97c472dd371f526c
// flow-typed version: <<STUB>>/csp-parse_v0.0.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csp-parse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csp-parse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csp-parse/test/parse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csp-parse/index' {
  declare module.exports: $Exports<'csp-parse'>;
}
declare module 'csp-parse/index.js' {
  declare module.exports: $Exports<'csp-parse'>;
}
declare module 'csp-parse/test/parse.js' {
  declare module.exports: $Exports<'csp-parse/test/parse'>;
}
