// flow-typed signature: 227033198bc18e6f923cdff24648ef98
// flow-typed version: <<STUB>>/dotenv-cli_v^1.4.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dotenv-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dotenv-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dotenv-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dotenv-cli/cli.js' {
  declare module.exports: $Exports<'dotenv-cli/cli'>;
}
