// flow-typed signature: 5cbb9eeae9c56f0afbb0d4d2855e47bb
// flow-typed version: <<STUB>>/elementtree_v^0.1.7/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'elementtree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'elementtree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'elementtree/lib/constants' {
  declare module.exports: any;
}

declare module 'elementtree/lib/elementpath' {
  declare module.exports: any;
}

declare module 'elementtree/lib/elementtree' {
  declare module.exports: any;
}

declare module 'elementtree/lib/errors' {
  declare module.exports: any;
}

declare module 'elementtree/lib/parser' {
  declare module.exports: any;
}

declare module 'elementtree/lib/parsers/index' {
  declare module.exports: any;
}

declare module 'elementtree/lib/parsers/sax' {
  declare module.exports: any;
}

declare module 'elementtree/lib/sprintf' {
  declare module.exports: any;
}

declare module 'elementtree/lib/treebuilder' {
  declare module.exports: any;
}

declare module 'elementtree/lib/utils' {
  declare module.exports: any;
}

declare module 'elementtree/tests/test-simple' {
  declare module.exports: any;
}

// Filename aliases
declare module 'elementtree/lib/constants.js' {
  declare module.exports: $Exports<'elementtree/lib/constants'>;
}
declare module 'elementtree/lib/elementpath.js' {
  declare module.exports: $Exports<'elementtree/lib/elementpath'>;
}
declare module 'elementtree/lib/elementtree.js' {
  declare module.exports: $Exports<'elementtree/lib/elementtree'>;
}
declare module 'elementtree/lib/errors.js' {
  declare module.exports: $Exports<'elementtree/lib/errors'>;
}
declare module 'elementtree/lib/parser.js' {
  declare module.exports: $Exports<'elementtree/lib/parser'>;
}
declare module 'elementtree/lib/parsers/index.js' {
  declare module.exports: $Exports<'elementtree/lib/parsers/index'>;
}
declare module 'elementtree/lib/parsers/sax.js' {
  declare module.exports: $Exports<'elementtree/lib/parsers/sax'>;
}
declare module 'elementtree/lib/sprintf.js' {
  declare module.exports: $Exports<'elementtree/lib/sprintf'>;
}
declare module 'elementtree/lib/treebuilder.js' {
  declare module.exports: $Exports<'elementtree/lib/treebuilder'>;
}
declare module 'elementtree/lib/utils.js' {
  declare module.exports: $Exports<'elementtree/lib/utils'>;
}
declare module 'elementtree/tests/test-simple.js' {
  declare module.exports: $Exports<'elementtree/tests/test-simple'>;
}
