// flow-typed signature: ef0f9024386c78bc584427afccc0aa1d
// flow-typed version: <<STUB>>/es6-symbol_v^3.1.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-symbol'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-symbol' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'es6-symbol/implement' {
  declare module.exports: any;
}

declare module 'es6-symbol/is-implemented' {
  declare module.exports: any;
}

declare module 'es6-symbol/is-native-implemented' {
  declare module.exports: any;
}

declare module 'es6-symbol/is-symbol' {
  declare module.exports: any;
}

declare module 'es6-symbol/polyfill' {
  declare module.exports: any;
}

declare module 'es6-symbol/test/implement' {
  declare module.exports: any;
}

declare module 'es6-symbol/test/index' {
  declare module.exports: any;
}

declare module 'es6-symbol/test/is-implemented' {
  declare module.exports: any;
}

declare module 'es6-symbol/test/is-native-implemented' {
  declare module.exports: any;
}

declare module 'es6-symbol/test/is-symbol' {
  declare module.exports: any;
}

declare module 'es6-symbol/test/polyfill' {
  declare module.exports: any;
}

declare module 'es6-symbol/test/validate-symbol' {
  declare module.exports: any;
}

declare module 'es6-symbol/validate-symbol' {
  declare module.exports: any;
}

// Filename aliases
declare module 'es6-symbol/implement.js' {
  declare module.exports: $Exports<'es6-symbol/implement'>;
}
declare module 'es6-symbol/index' {
  declare module.exports: $Exports<'es6-symbol'>;
}
declare module 'es6-symbol/index.js' {
  declare module.exports: $Exports<'es6-symbol'>;
}
declare module 'es6-symbol/is-implemented.js' {
  declare module.exports: $Exports<'es6-symbol/is-implemented'>;
}
declare module 'es6-symbol/is-native-implemented.js' {
  declare module.exports: $Exports<'es6-symbol/is-native-implemented'>;
}
declare module 'es6-symbol/is-symbol.js' {
  declare module.exports: $Exports<'es6-symbol/is-symbol'>;
}
declare module 'es6-symbol/polyfill.js' {
  declare module.exports: $Exports<'es6-symbol/polyfill'>;
}
declare module 'es6-symbol/test/implement.js' {
  declare module.exports: $Exports<'es6-symbol/test/implement'>;
}
declare module 'es6-symbol/test/index.js' {
  declare module.exports: $Exports<'es6-symbol/test/index'>;
}
declare module 'es6-symbol/test/is-implemented.js' {
  declare module.exports: $Exports<'es6-symbol/test/is-implemented'>;
}
declare module 'es6-symbol/test/is-native-implemented.js' {
  declare module.exports: $Exports<'es6-symbol/test/is-native-implemented'>;
}
declare module 'es6-symbol/test/is-symbol.js' {
  declare module.exports: $Exports<'es6-symbol/test/is-symbol'>;
}
declare module 'es6-symbol/test/polyfill.js' {
  declare module.exports: $Exports<'es6-symbol/test/polyfill'>;
}
declare module 'es6-symbol/test/validate-symbol.js' {
  declare module.exports: $Exports<'es6-symbol/test/validate-symbol'>;
}
declare module 'es6-symbol/validate-symbol.js' {
  declare module.exports: $Exports<'es6-symbol/validate-symbol'>;
}
