// flow-typed signature: fc4728afdc1aa3501797dab9ee6ca86b
// flow-typed version: <<STUB>>/es6-set_v^0.1.5/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-set'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-set' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'es6-set/ext/copy' {
  declare module.exports: any;
}

declare module 'es6-set/ext/every' {
  declare module.exports: any;
}

declare module 'es6-set/ext/filter' {
  declare module.exports: any;
}

declare module 'es6-set/ext/get-first' {
  declare module.exports: any;
}

declare module 'es6-set/ext/get-last' {
  declare module.exports: any;
}

declare module 'es6-set/ext/some' {
  declare module.exports: any;
}

declare module 'es6-set/implement' {
  declare module.exports: any;
}

declare module 'es6-set/is-implemented' {
  declare module.exports: any;
}

declare module 'es6-set/is-native-implemented' {
  declare module.exports: any;
}

declare module 'es6-set/is-set' {
  declare module.exports: any;
}

declare module 'es6-set/lib/iterator' {
  declare module.exports: any;
}

declare module 'es6-set/lib/primitive-iterator' {
  declare module.exports: any;
}

declare module 'es6-set/polyfill' {
  declare module.exports: any;
}

declare module 'es6-set/primitive/index' {
  declare module.exports: any;
}

declare module 'es6-set/test/ext/copy' {
  declare module.exports: any;
}

declare module 'es6-set/test/ext/every' {
  declare module.exports: any;
}

declare module 'es6-set/test/ext/filter' {
  declare module.exports: any;
}

declare module 'es6-set/test/ext/get-first' {
  declare module.exports: any;
}

declare module 'es6-set/test/ext/get-last' {
  declare module.exports: any;
}

declare module 'es6-set/test/ext/some' {
  declare module.exports: any;
}

declare module 'es6-set/test/implement' {
  declare module.exports: any;
}

declare module 'es6-set/test/index' {
  declare module.exports: any;
}

declare module 'es6-set/test/is-implemented' {
  declare module.exports: any;
}

declare module 'es6-set/test/is-native-implemented' {
  declare module.exports: any;
}

declare module 'es6-set/test/is-set' {
  declare module.exports: any;
}

declare module 'es6-set/test/lib/iterator' {
  declare module.exports: any;
}

declare module 'es6-set/test/lib/primitive-iterator' {
  declare module.exports: any;
}

declare module 'es6-set/test/polyfill' {
  declare module.exports: any;
}

declare module 'es6-set/test/primitive/index' {
  declare module.exports: any;
}

declare module 'es6-set/test/valid-set' {
  declare module.exports: any;
}

declare module 'es6-set/valid-set' {
  declare module.exports: any;
}

// Filename aliases
declare module 'es6-set/ext/copy.js' {
  declare module.exports: $Exports<'es6-set/ext/copy'>;
}
declare module 'es6-set/ext/every.js' {
  declare module.exports: $Exports<'es6-set/ext/every'>;
}
declare module 'es6-set/ext/filter.js' {
  declare module.exports: $Exports<'es6-set/ext/filter'>;
}
declare module 'es6-set/ext/get-first.js' {
  declare module.exports: $Exports<'es6-set/ext/get-first'>;
}
declare module 'es6-set/ext/get-last.js' {
  declare module.exports: $Exports<'es6-set/ext/get-last'>;
}
declare module 'es6-set/ext/some.js' {
  declare module.exports: $Exports<'es6-set/ext/some'>;
}
declare module 'es6-set/implement.js' {
  declare module.exports: $Exports<'es6-set/implement'>;
}
declare module 'es6-set/index' {
  declare module.exports: $Exports<'es6-set'>;
}
declare module 'es6-set/index.js' {
  declare module.exports: $Exports<'es6-set'>;
}
declare module 'es6-set/is-implemented.js' {
  declare module.exports: $Exports<'es6-set/is-implemented'>;
}
declare module 'es6-set/is-native-implemented.js' {
  declare module.exports: $Exports<'es6-set/is-native-implemented'>;
}
declare module 'es6-set/is-set.js' {
  declare module.exports: $Exports<'es6-set/is-set'>;
}
declare module 'es6-set/lib/iterator.js' {
  declare module.exports: $Exports<'es6-set/lib/iterator'>;
}
declare module 'es6-set/lib/primitive-iterator.js' {
  declare module.exports: $Exports<'es6-set/lib/primitive-iterator'>;
}
declare module 'es6-set/polyfill.js' {
  declare module.exports: $Exports<'es6-set/polyfill'>;
}
declare module 'es6-set/primitive/index.js' {
  declare module.exports: $Exports<'es6-set/primitive/index'>;
}
declare module 'es6-set/test/ext/copy.js' {
  declare module.exports: $Exports<'es6-set/test/ext/copy'>;
}
declare module 'es6-set/test/ext/every.js' {
  declare module.exports: $Exports<'es6-set/test/ext/every'>;
}
declare module 'es6-set/test/ext/filter.js' {
  declare module.exports: $Exports<'es6-set/test/ext/filter'>;
}
declare module 'es6-set/test/ext/get-first.js' {
  declare module.exports: $Exports<'es6-set/test/ext/get-first'>;
}
declare module 'es6-set/test/ext/get-last.js' {
  declare module.exports: $Exports<'es6-set/test/ext/get-last'>;
}
declare module 'es6-set/test/ext/some.js' {
  declare module.exports: $Exports<'es6-set/test/ext/some'>;
}
declare module 'es6-set/test/implement.js' {
  declare module.exports: $Exports<'es6-set/test/implement'>;
}
declare module 'es6-set/test/index.js' {
  declare module.exports: $Exports<'es6-set/test/index'>;
}
declare module 'es6-set/test/is-implemented.js' {
  declare module.exports: $Exports<'es6-set/test/is-implemented'>;
}
declare module 'es6-set/test/is-native-implemented.js' {
  declare module.exports: $Exports<'es6-set/test/is-native-implemented'>;
}
declare module 'es6-set/test/is-set.js' {
  declare module.exports: $Exports<'es6-set/test/is-set'>;
}
declare module 'es6-set/test/lib/iterator.js' {
  declare module.exports: $Exports<'es6-set/test/lib/iterator'>;
}
declare module 'es6-set/test/lib/primitive-iterator.js' {
  declare module.exports: $Exports<'es6-set/test/lib/primitive-iterator'>;
}
declare module 'es6-set/test/polyfill.js' {
  declare module.exports: $Exports<'es6-set/test/polyfill'>;
}
declare module 'es6-set/test/primitive/index.js' {
  declare module.exports: $Exports<'es6-set/test/primitive/index'>;
}
declare module 'es6-set/test/valid-set.js' {
  declare module.exports: $Exports<'es6-set/test/valid-set'>;
}
declare module 'es6-set/valid-set.js' {
  declare module.exports: $Exports<'es6-set/valid-set'>;
}
