// flow-typed signature: c512b09e68bba1fe757443abe13aa472
// flow-typed version: <<STUB>>/eslint-plugin-webdriverio_v^1.0.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-webdriverio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-webdriverio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-plugin-webdriverio/index' {
  declare module.exports: $Exports<'eslint-plugin-webdriverio'>;
}
declare module 'eslint-plugin-webdriverio/index.js' {
  declare module.exports: $Exports<'eslint-plugin-webdriverio'>;
}
