// flow-typed signature: babb623a23f7632f86e7675c136b27b3
// flow-typed version: <<STUB>>/esri-leaflet_v^2.1.4/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esri-leaflet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esri-leaflet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esri-leaflet/dist/esri-leaflet-debug' {
  declare module.exports: any;
}

declare module 'esri-leaflet/dist/esri-leaflet' {
  declare module.exports: any;
}

declare module 'esri-leaflet/karma.conf' {
  declare module.exports: any;
}

declare module 'esri-leaflet/profiles/base' {
  declare module.exports: any;
}

declare module 'esri-leaflet/profiles/debug' {
  declare module.exports: any;
}

declare module 'esri-leaflet/profiles/production' {
  declare module.exports: any;
}

declare module 'esri-leaflet/site/build/js/esri-leaflet-src' {
  declare module.exports: any;
}

declare module 'esri-leaflet/site/build/js/script' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/EsriLeaflet' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Layers/BasemapLayer' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Layers/DynamicMapLayer' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Layers/FeatureLayer/FeatureLayer' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Layers/FeatureLayer/FeatureManager' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Layers/ImageMapLayer' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Layers/RasterLayer' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Layers/TiledMapLayer' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Options' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Request' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Services/FeatureLayerService' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Services/ImageService' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Services/MapService' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Services/Service' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Support' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Tasks/Find' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Tasks/Identify' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Tasks/IdentifyFeatures' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Tasks/IdentifyImage' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Tasks/Query' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Tasks/Task' {
  declare module.exports: any;
}

declare module 'esri-leaflet/src/Util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esri-leaflet/dist/esri-leaflet-debug.js' {
  declare module.exports: $Exports<'esri-leaflet/dist/esri-leaflet-debug'>;
}
declare module 'esri-leaflet/dist/esri-leaflet.js' {
  declare module.exports: $Exports<'esri-leaflet/dist/esri-leaflet'>;
}
declare module 'esri-leaflet/karma.conf.js' {
  declare module.exports: $Exports<'esri-leaflet/karma.conf'>;
}
declare module 'esri-leaflet/profiles/base.js' {
  declare module.exports: $Exports<'esri-leaflet/profiles/base'>;
}
declare module 'esri-leaflet/profiles/debug.js' {
  declare module.exports: $Exports<'esri-leaflet/profiles/debug'>;
}
declare module 'esri-leaflet/profiles/production.js' {
  declare module.exports: $Exports<'esri-leaflet/profiles/production'>;
}
declare module 'esri-leaflet/site/build/js/esri-leaflet-src.js' {
  declare module.exports: $Exports<'esri-leaflet/site/build/js/esri-leaflet-src'>;
}
declare module 'esri-leaflet/site/build/js/script.js' {
  declare module.exports: $Exports<'esri-leaflet/site/build/js/script'>;
}
declare module 'esri-leaflet/src/EsriLeaflet.js' {
  declare module.exports: $Exports<'esri-leaflet/src/EsriLeaflet'>;
}
declare module 'esri-leaflet/src/Layers/BasemapLayer.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Layers/BasemapLayer'>;
}
declare module 'esri-leaflet/src/Layers/DynamicMapLayer.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Layers/DynamicMapLayer'>;
}
declare module 'esri-leaflet/src/Layers/FeatureLayer/FeatureLayer.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Layers/FeatureLayer/FeatureLayer'>;
}
declare module 'esri-leaflet/src/Layers/FeatureLayer/FeatureManager.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Layers/FeatureLayer/FeatureManager'>;
}
declare module 'esri-leaflet/src/Layers/ImageMapLayer.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Layers/ImageMapLayer'>;
}
declare module 'esri-leaflet/src/Layers/RasterLayer.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Layers/RasterLayer'>;
}
declare module 'esri-leaflet/src/Layers/TiledMapLayer.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Layers/TiledMapLayer'>;
}
declare module 'esri-leaflet/src/Options.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Options'>;
}
declare module 'esri-leaflet/src/Request.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Request'>;
}
declare module 'esri-leaflet/src/Services/FeatureLayerService.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Services/FeatureLayerService'>;
}
declare module 'esri-leaflet/src/Services/ImageService.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Services/ImageService'>;
}
declare module 'esri-leaflet/src/Services/MapService.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Services/MapService'>;
}
declare module 'esri-leaflet/src/Services/Service.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Services/Service'>;
}
declare module 'esri-leaflet/src/Support.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Support'>;
}
declare module 'esri-leaflet/src/Tasks/Find.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Tasks/Find'>;
}
declare module 'esri-leaflet/src/Tasks/Identify.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Tasks/Identify'>;
}
declare module 'esri-leaflet/src/Tasks/IdentifyFeatures.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Tasks/IdentifyFeatures'>;
}
declare module 'esri-leaflet/src/Tasks/IdentifyImage.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Tasks/IdentifyImage'>;
}
declare module 'esri-leaflet/src/Tasks/Query.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Tasks/Query'>;
}
declare module 'esri-leaflet/src/Tasks/Task.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Tasks/Task'>;
}
declare module 'esri-leaflet/src/Util.js' {
  declare module.exports: $Exports<'esri-leaflet/src/Util'>;
}
