// flow-typed signature: 876cba5b291aa34e2d1be308800e6c12
// flow-typed version: <<STUB>>/fast-levenshtein_v^2.0.6/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-levenshtein'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-levenshtein' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-levenshtein/levenshtein' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-levenshtein/levenshtein.js' {
  declare module.exports: $Exports<'fast-levenshtein/levenshtein'>;
}
