// flow-typed signature: e97de17fb7ffb84623d09a7f4c26bad7
// flow-typed version: <<STUB>>/focus-trap_v^3.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'focus-trap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'focus-trap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'focus-trap/dist/focus-trap' {
  declare module.exports: any;
}

declare module 'focus-trap/dist/focus-trap.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'focus-trap/dist/focus-trap.js' {
  declare module.exports: $Exports<'focus-trap/dist/focus-trap'>;
}
declare module 'focus-trap/dist/focus-trap.min.js' {
  declare module.exports: $Exports<'focus-trap/dist/focus-trap.min'>;
}
declare module 'focus-trap/index' {
  declare module.exports: $Exports<'focus-trap'>;
}
declare module 'focus-trap/index.js' {
  declare module.exports: $Exports<'focus-trap'>;
}
