// flow-typed signature: 122252754d055d1a4c80eab76c04e298
// flow-typed version: <<STUB>>/focus-within_v^2.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'focus-within'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'focus-within' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'focus-within/index.cjs' {
  declare module.exports: any;
}

declare module 'focus-within/index.es' {
  declare module.exports: any;
}

// Filename aliases
declare module 'focus-within/index.cjs.js' {
  declare module.exports: $Exports<'focus-within/index.cjs'>;
}
declare module 'focus-within/index.es.js' {
  declare module.exports: $Exports<'focus-within/index.es'>;
}
