// flow-typed signature: e98f5ff50d691a494d145b925a5e8093
// flow-typed version: <<STUB>>/focus-visible_v^4.1.5/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'focus-visible'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'focus-visible' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'focus-visible/dist/focus-visible' {
  declare module.exports: any;
}

declare module 'focus-visible/dist/focus-visible.min' {
  declare module.exports: any;
}

declare module 'focus-visible/rollup.config' {
  declare module.exports: any;
}

declare module 'focus-visible/src/focus-visible' {
  declare module.exports: any;
}

declare module 'focus-visible/test/index' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/button' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/change-tabs-always-match' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/change-tabs-sometimes-match' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/contenteditable-textbox' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/contenteditable-true' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/contenteditable' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/helpers/index' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/input-checkbox' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/input-color' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/input-date' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/input-file' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/input-number' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/input-radio-group' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/input-radio' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/input-range' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/input-submit' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/input-text' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/input-time' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/keydown-always-match' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/pointer-turns-off-keyboard' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/programmatic-focus-always' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/programmatic-focus-microtask' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/programmatic-focus' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/select-multiple' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/select-size' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/select' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/svg' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/tabindex-negative-one' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/tabindex-one' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/tabindex-zero' {
  declare module.exports: any;
}

declare module 'focus-visible/test/specs/textarea' {
  declare module.exports: any;
}

// Filename aliases
declare module 'focus-visible/dist/focus-visible.js' {
  declare module.exports: $Exports<'focus-visible/dist/focus-visible'>;
}
declare module 'focus-visible/dist/focus-visible.min.js' {
  declare module.exports: $Exports<'focus-visible/dist/focus-visible.min'>;
}
declare module 'focus-visible/rollup.config.js' {
  declare module.exports: $Exports<'focus-visible/rollup.config'>;
}
declare module 'focus-visible/src/focus-visible.js' {
  declare module.exports: $Exports<'focus-visible/src/focus-visible'>;
}
declare module 'focus-visible/test/index.js' {
  declare module.exports: $Exports<'focus-visible/test/index'>;
}
declare module 'focus-visible/test/specs/button.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/button'>;
}
declare module 'focus-visible/test/specs/change-tabs-always-match.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/change-tabs-always-match'>;
}
declare module 'focus-visible/test/specs/change-tabs-sometimes-match.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/change-tabs-sometimes-match'>;
}
declare module 'focus-visible/test/specs/contenteditable-textbox.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/contenteditable-textbox'>;
}
declare module 'focus-visible/test/specs/contenteditable-true.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/contenteditable-true'>;
}
declare module 'focus-visible/test/specs/contenteditable.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/contenteditable'>;
}
declare module 'focus-visible/test/specs/helpers/index.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/helpers/index'>;
}
declare module 'focus-visible/test/specs/input-checkbox.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/input-checkbox'>;
}
declare module 'focus-visible/test/specs/input-color.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/input-color'>;
}
declare module 'focus-visible/test/specs/input-date.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/input-date'>;
}
declare module 'focus-visible/test/specs/input-file.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/input-file'>;
}
declare module 'focus-visible/test/specs/input-number.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/input-number'>;
}
declare module 'focus-visible/test/specs/input-radio-group.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/input-radio-group'>;
}
declare module 'focus-visible/test/specs/input-radio.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/input-radio'>;
}
declare module 'focus-visible/test/specs/input-range.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/input-range'>;
}
declare module 'focus-visible/test/specs/input-submit.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/input-submit'>;
}
declare module 'focus-visible/test/specs/input-text.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/input-text'>;
}
declare module 'focus-visible/test/specs/input-time.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/input-time'>;
}
declare module 'focus-visible/test/specs/keydown-always-match.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/keydown-always-match'>;
}
declare module 'focus-visible/test/specs/pointer-turns-off-keyboard.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/pointer-turns-off-keyboard'>;
}
declare module 'focus-visible/test/specs/programmatic-focus-always.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/programmatic-focus-always'>;
}
declare module 'focus-visible/test/specs/programmatic-focus-microtask.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/programmatic-focus-microtask'>;
}
declare module 'focus-visible/test/specs/programmatic-focus.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/programmatic-focus'>;
}
declare module 'focus-visible/test/specs/select-multiple.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/select-multiple'>;
}
declare module 'focus-visible/test/specs/select-size.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/select-size'>;
}
declare module 'focus-visible/test/specs/select.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/select'>;
}
declare module 'focus-visible/test/specs/svg.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/svg'>;
}
declare module 'focus-visible/test/specs/tabindex-negative-one.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/tabindex-negative-one'>;
}
declare module 'focus-visible/test/specs/tabindex-one.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/tabindex-one'>;
}
declare module 'focus-visible/test/specs/tabindex-zero.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/tabindex-zero'>;
}
declare module 'focus-visible/test/specs/textarea.js' {
  declare module.exports: $Exports<'focus-visible/test/specs/textarea'>;
}
