// flow-typed signature: dce7a12ce84bc62b7e88741b823e925b
// flow-typed version: <<STUB>>/isomorphic-unfetch_v^2.1.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isomorphic-unfetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isomorphic-unfetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'isomorphic-unfetch/browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'isomorphic-unfetch/browser.js' {
  declare module.exports: $Exports<'isomorphic-unfetch/browser'>;
}
declare module 'isomorphic-unfetch/index' {
  declare module.exports: $Exports<'isomorphic-unfetch'>;
}
declare module 'isomorphic-unfetch/index.js' {
  declare module.exports: $Exports<'isomorphic-unfetch'>;
}
