// flow-typed signature: 843c8c1b4168357673cb2295e845af53
// flow-typed version: <<STUB>>/leaflet.locatecontrol_v^0.60.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet.locatecontrol'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaflet.locatecontrol' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaflet.locatecontrol/demo_mapbox/script' {
  declare module.exports: any;
}

declare module 'leaflet.locatecontrol/demo/script' {
  declare module.exports: any;
}

declare module 'leaflet.locatecontrol/dist/L.Control.Locate.min' {
  declare module.exports: any;
}

declare module 'leaflet.locatecontrol/Gruntfile' {
  declare module.exports: any;
}

declare module 'leaflet.locatecontrol/src/L.Control.Locate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaflet.locatecontrol/demo_mapbox/script.js' {
  declare module.exports: $Exports<'leaflet.locatecontrol/demo_mapbox/script'>;
}
declare module 'leaflet.locatecontrol/demo/script.js' {
  declare module.exports: $Exports<'leaflet.locatecontrol/demo/script'>;
}
declare module 'leaflet.locatecontrol/dist/L.Control.Locate.min.js' {
  declare module.exports: $Exports<'leaflet.locatecontrol/dist/L.Control.Locate.min'>;
}
declare module 'leaflet.locatecontrol/Gruntfile.js' {
  declare module.exports: $Exports<'leaflet.locatecontrol/Gruntfile'>;
}
declare module 'leaflet.locatecontrol/src/L.Control.Locate.js' {
  declare module.exports: $Exports<'leaflet.locatecontrol/src/L.Control.Locate'>;
}
