// flow-typed signature: 00c492844aa89d84b53a34d78ff5214b
// flow-typed version: <<STUB>>/leaflet-tilelayer-geojson_v^1.0.4/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet-tilelayer-geojson'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaflet-tilelayer-geojson' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaflet-tilelayer-geojson/TileLayer.GeoJSON' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaflet-tilelayer-geojson/TileLayer.GeoJSON.js' {
  declare module.exports: $Exports<'leaflet-tilelayer-geojson/TileLayer.GeoJSON'>;
}
