// flow-typed signature: fa03532f82fac82e216cbc2940cc51c4
// flow-typed version: <<STUB>>/leaflet.markercluster_v^1.0.4/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet.markercluster'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaflet.markercluster' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaflet.markercluster/build/hintrc' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/build/rollup-config' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/dist/leaflet.markercluster-src' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/dist/leaflet.markercluster' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/example/geojson-sample' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/example/realworld.10000' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/example/realworld.388' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/example/realworld.50000.1' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/example/realworld.50000.2' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/Jakefile' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/after' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/expect' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/karma.conf' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/sinon' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/AddLayer.MultipleSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/AddLayer.SingleSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/AddLayersSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/animateOptionSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/ChildChangingIconSupportSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/CircleMarkerSupportSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/CircleSupportSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/clearLayersSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/disableClusteringAtZoomSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/DistanceGridSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/eachLayerSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/eventsSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/getBoundsSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/getLayersSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/getVisibleParentSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/LeafletSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/markerMoveSupportSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/nonIntegerZoomSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/NonPointSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/onAddSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/onRemoveSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/PaneSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/QuickHullSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/RefreshSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/RememberOpacity' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/RemoveLayerSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/removeLayersSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/removeOutsideVisibleBoundsSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/singleMarkerModeSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/SpecHelper' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/spiderfySpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/supportNegativeZoomSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/unspiderfySpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/spec/suites/zoomAnimationSpec' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/src/DistanceGrid' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/src/index' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/src/MarkerCluster' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/src/MarkerCluster.QuickHull' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/src/MarkerCluster.Spiderfier' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/src/MarkerClusterGroup' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/src/MarkerClusterGroup.Refresh' {
  declare module.exports: any;
}

declare module 'leaflet.markercluster/src/MarkerOpacity' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaflet.markercluster/build/hintrc.js' {
  declare module.exports: $Exports<'leaflet.markercluster/build/hintrc'>;
}
declare module 'leaflet.markercluster/build/rollup-config.js' {
  declare module.exports: $Exports<'leaflet.markercluster/build/rollup-config'>;
}
declare module 'leaflet.markercluster/dist/leaflet.markercluster-src.js' {
  declare module.exports: $Exports<'leaflet.markercluster/dist/leaflet.markercluster-src'>;
}
declare module 'leaflet.markercluster/dist/leaflet.markercluster.js' {
  declare module.exports: $Exports<'leaflet.markercluster/dist/leaflet.markercluster'>;
}
declare module 'leaflet.markercluster/example/geojson-sample.js' {
  declare module.exports: $Exports<'leaflet.markercluster/example/geojson-sample'>;
}
declare module 'leaflet.markercluster/example/realworld.10000.js' {
  declare module.exports: $Exports<'leaflet.markercluster/example/realworld.10000'>;
}
declare module 'leaflet.markercluster/example/realworld.388.js' {
  declare module.exports: $Exports<'leaflet.markercluster/example/realworld.388'>;
}
declare module 'leaflet.markercluster/example/realworld.50000.1.js' {
  declare module.exports: $Exports<'leaflet.markercluster/example/realworld.50000.1'>;
}
declare module 'leaflet.markercluster/example/realworld.50000.2.js' {
  declare module.exports: $Exports<'leaflet.markercluster/example/realworld.50000.2'>;
}
declare module 'leaflet.markercluster/Jakefile.js' {
  declare module.exports: $Exports<'leaflet.markercluster/Jakefile'>;
}
declare module 'leaflet.markercluster/spec/after.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/after'>;
}
declare module 'leaflet.markercluster/spec/expect.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/expect'>;
}
declare module 'leaflet.markercluster/spec/karma.conf.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/karma.conf'>;
}
declare module 'leaflet.markercluster/spec/sinon.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/sinon'>;
}
declare module 'leaflet.markercluster/spec/suites/AddLayer.MultipleSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/AddLayer.MultipleSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/AddLayer.SingleSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/AddLayer.SingleSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/AddLayersSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/AddLayersSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/animateOptionSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/animateOptionSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/ChildChangingIconSupportSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/ChildChangingIconSupportSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/CircleMarkerSupportSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/CircleMarkerSupportSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/CircleSupportSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/CircleSupportSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/clearLayersSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/clearLayersSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/disableClusteringAtZoomSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/disableClusteringAtZoomSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/DistanceGridSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/DistanceGridSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/eachLayerSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/eachLayerSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/eventsSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/eventsSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/getBoundsSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/getBoundsSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/getLayersSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/getLayersSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/getVisibleParentSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/getVisibleParentSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/LeafletSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/LeafletSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/markerMoveSupportSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/markerMoveSupportSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/nonIntegerZoomSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/nonIntegerZoomSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/NonPointSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/NonPointSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/onAddSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/onAddSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/onRemoveSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/onRemoveSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/PaneSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/PaneSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/QuickHullSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/QuickHullSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/RefreshSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/RefreshSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/RememberOpacity.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/RememberOpacity'>;
}
declare module 'leaflet.markercluster/spec/suites/RemoveLayerSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/RemoveLayerSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/removeLayersSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/removeLayersSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/removeOutsideVisibleBoundsSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/removeOutsideVisibleBoundsSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/singleMarkerModeSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/singleMarkerModeSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/SpecHelper.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/SpecHelper'>;
}
declare module 'leaflet.markercluster/spec/suites/spiderfySpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/spiderfySpec'>;
}
declare module 'leaflet.markercluster/spec/suites/supportNegativeZoomSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/supportNegativeZoomSpec'>;
}
declare module 'leaflet.markercluster/spec/suites/unspiderfySpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/unspiderfySpec'>;
}
declare module 'leaflet.markercluster/spec/suites/zoomAnimationSpec.js' {
  declare module.exports: $Exports<'leaflet.markercluster/spec/suites/zoomAnimationSpec'>;
}
declare module 'leaflet.markercluster/src/DistanceGrid.js' {
  declare module.exports: $Exports<'leaflet.markercluster/src/DistanceGrid'>;
}
declare module 'leaflet.markercluster/src/index.js' {
  declare module.exports: $Exports<'leaflet.markercluster/src/index'>;
}
declare module 'leaflet.markercluster/src/MarkerCluster.js' {
  declare module.exports: $Exports<'leaflet.markercluster/src/MarkerCluster'>;
}
declare module 'leaflet.markercluster/src/MarkerCluster.QuickHull.js' {
  declare module.exports: $Exports<'leaflet.markercluster/src/MarkerCluster.QuickHull'>;
}
declare module 'leaflet.markercluster/src/MarkerCluster.Spiderfier.js' {
  declare module.exports: $Exports<'leaflet.markercluster/src/MarkerCluster.Spiderfier'>;
}
declare module 'leaflet.markercluster/src/MarkerClusterGroup.js' {
  declare module.exports: $Exports<'leaflet.markercluster/src/MarkerClusterGroup'>;
}
declare module 'leaflet.markercluster/src/MarkerClusterGroup.Refresh.js' {
  declare module.exports: $Exports<'leaflet.markercluster/src/MarkerClusterGroup.Refresh'>;
}
declare module 'leaflet.markercluster/src/MarkerOpacity.js' {
  declare module.exports: $Exports<'leaflet.markercluster/src/MarkerOpacity'>;
}
