// flow-typed signature: 3aa2c4dfd1caf383092af161db9127be
// flow-typed version: <<STUB>>/local-storage-fallback_v^4.1.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'local-storage-fallback'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'local-storage-fallback' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'local-storage-fallback/lib/CookieStorage' {
  declare module.exports: any;
}

declare module 'local-storage-fallback/lib/dist.min' {
  declare module.exports: any;
}

declare module 'local-storage-fallback/lib/hasStorage' {
  declare module.exports: any;
}

declare module 'local-storage-fallback/lib/index' {
  declare module.exports: any;
}

declare module 'local-storage-fallback/lib/isSupported' {
  declare module.exports: any;
}

declare module 'local-storage-fallback/lib/MemoryStorage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'local-storage-fallback/lib/CookieStorage.js' {
  declare module.exports: $Exports<'local-storage-fallback/lib/CookieStorage'>;
}
declare module 'local-storage-fallback/lib/dist.min.js' {
  declare module.exports: $Exports<'local-storage-fallback/lib/dist.min'>;
}
declare module 'local-storage-fallback/lib/hasStorage.js' {
  declare module.exports: $Exports<'local-storage-fallback/lib/hasStorage'>;
}
declare module 'local-storage-fallback/lib/index.js' {
  declare module.exports: $Exports<'local-storage-fallback/lib/index'>;
}
declare module 'local-storage-fallback/lib/isSupported.js' {
  declare module.exports: $Exports<'local-storage-fallback/lib/isSupported'>;
}
declare module 'local-storage-fallback/lib/MemoryStorage.js' {
  declare module.exports: $Exports<'local-storage-fallback/lib/MemoryStorage'>;
}
