// flow-typed signature: 9006fa6f2796f1b2f3fec48ba9ba9e9e
// flow-typed version: <<STUB>>/mapbox.js_v^3.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mapbox.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mapbox.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mapbox.js/_docs/generate' {
  declare module.exports: any;
}

declare module 'mapbox.js/docs/assets/csv2geojson' {
  declare module.exports: any;
}

declare module 'mapbox.js/docs/assets/data/flights' {
  declare module.exports: any;
}

declare module 'mapbox.js/docs/assets/data/realworld.388' {
  declare module.exports: any;
}

declare module 'mapbox.js/docs/assets/data/us-states' {
  declare module.exports: any;
}

declare module 'mapbox.js/docs/assets/js/prettify' {
  declare module.exports: any;
}

declare module 'mapbox.js/docs/assets/js/site' {
  declare module.exports: any;
}

declare module 'mapbox.js/docs/assets/leaflet-hash' {
  declare module.exports: any;
}

declare module 'mapbox.js/docs/assets/leaflet-pip' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/config' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/feature_layer' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/feedback' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/format_url' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/geocoder_control' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/geocoder' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/grid_control' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/grid_layer' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/grid' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/index' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/internals' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/leaflet' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/legend_control' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/load_tilejson' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/map' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/mapbox_logo' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/mapbox' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/marker' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/request' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/share_control' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/simplestyle' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/style_layer' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/tile_layer' {
  declare module.exports: any;
}

declare module 'mapbox.js/src/util' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/helper' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/manual/access_token' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/manual/leaflet-hash' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/attribution_control' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/feature_layer' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/format_url' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/geocoder_control' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/geocoder' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/grid_control' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/grid_layer' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/grid' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/legend_control' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/map' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/mapbox_logo' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/marker' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/request' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/security' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/share_control' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/simplestyle' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/style_layer' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/template' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/tile_layer' {
  declare module.exports: any;
}

declare module 'mapbox.js/test/spec/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mapbox.js/_docs/generate.js' {
  declare module.exports: $Exports<'mapbox.js/_docs/generate'>;
}
declare module 'mapbox.js/docs/assets/csv2geojson.js' {
  declare module.exports: $Exports<'mapbox.js/docs/assets/csv2geojson'>;
}
declare module 'mapbox.js/docs/assets/data/flights.js' {
  declare module.exports: $Exports<'mapbox.js/docs/assets/data/flights'>;
}
declare module 'mapbox.js/docs/assets/data/realworld.388.js' {
  declare module.exports: $Exports<'mapbox.js/docs/assets/data/realworld.388'>;
}
declare module 'mapbox.js/docs/assets/data/us-states.js' {
  declare module.exports: $Exports<'mapbox.js/docs/assets/data/us-states'>;
}
declare module 'mapbox.js/docs/assets/js/prettify.js' {
  declare module.exports: $Exports<'mapbox.js/docs/assets/js/prettify'>;
}
declare module 'mapbox.js/docs/assets/js/site.js' {
  declare module.exports: $Exports<'mapbox.js/docs/assets/js/site'>;
}
declare module 'mapbox.js/docs/assets/leaflet-hash.js' {
  declare module.exports: $Exports<'mapbox.js/docs/assets/leaflet-hash'>;
}
declare module 'mapbox.js/docs/assets/leaflet-pip.js' {
  declare module.exports: $Exports<'mapbox.js/docs/assets/leaflet-pip'>;
}
declare module 'mapbox.js/src/config.js' {
  declare module.exports: $Exports<'mapbox.js/src/config'>;
}
declare module 'mapbox.js/src/feature_layer.js' {
  declare module.exports: $Exports<'mapbox.js/src/feature_layer'>;
}
declare module 'mapbox.js/src/feedback.js' {
  declare module.exports: $Exports<'mapbox.js/src/feedback'>;
}
declare module 'mapbox.js/src/format_url.js' {
  declare module.exports: $Exports<'mapbox.js/src/format_url'>;
}
declare module 'mapbox.js/src/geocoder_control.js' {
  declare module.exports: $Exports<'mapbox.js/src/geocoder_control'>;
}
declare module 'mapbox.js/src/geocoder.js' {
  declare module.exports: $Exports<'mapbox.js/src/geocoder'>;
}
declare module 'mapbox.js/src/grid_control.js' {
  declare module.exports: $Exports<'mapbox.js/src/grid_control'>;
}
declare module 'mapbox.js/src/grid_layer.js' {
  declare module.exports: $Exports<'mapbox.js/src/grid_layer'>;
}
declare module 'mapbox.js/src/grid.js' {
  declare module.exports: $Exports<'mapbox.js/src/grid'>;
}
declare module 'mapbox.js/src/index.js' {
  declare module.exports: $Exports<'mapbox.js/src/index'>;
}
declare module 'mapbox.js/src/internals.js' {
  declare module.exports: $Exports<'mapbox.js/src/internals'>;
}
declare module 'mapbox.js/src/leaflet.js' {
  declare module.exports: $Exports<'mapbox.js/src/leaflet'>;
}
declare module 'mapbox.js/src/legend_control.js' {
  declare module.exports: $Exports<'mapbox.js/src/legend_control'>;
}
declare module 'mapbox.js/src/load_tilejson.js' {
  declare module.exports: $Exports<'mapbox.js/src/load_tilejson'>;
}
declare module 'mapbox.js/src/map.js' {
  declare module.exports: $Exports<'mapbox.js/src/map'>;
}
declare module 'mapbox.js/src/mapbox_logo.js' {
  declare module.exports: $Exports<'mapbox.js/src/mapbox_logo'>;
}
declare module 'mapbox.js/src/mapbox.js' {
  declare module.exports: $Exports<'mapbox.js/src/mapbox'>;
}
declare module 'mapbox.js/src/marker.js' {
  declare module.exports: $Exports<'mapbox.js/src/marker'>;
}
declare module 'mapbox.js/src/request.js' {
  declare module.exports: $Exports<'mapbox.js/src/request'>;
}
declare module 'mapbox.js/src/share_control.js' {
  declare module.exports: $Exports<'mapbox.js/src/share_control'>;
}
declare module 'mapbox.js/src/simplestyle.js' {
  declare module.exports: $Exports<'mapbox.js/src/simplestyle'>;
}
declare module 'mapbox.js/src/style_layer.js' {
  declare module.exports: $Exports<'mapbox.js/src/style_layer'>;
}
declare module 'mapbox.js/src/tile_layer.js' {
  declare module.exports: $Exports<'mapbox.js/src/tile_layer'>;
}
declare module 'mapbox.js/src/util.js' {
  declare module.exports: $Exports<'mapbox.js/src/util'>;
}
declare module 'mapbox.js/test/helper.js' {
  declare module.exports: $Exports<'mapbox.js/test/helper'>;
}
declare module 'mapbox.js/test/manual/access_token.js' {
  declare module.exports: $Exports<'mapbox.js/test/manual/access_token'>;
}
declare module 'mapbox.js/test/manual/leaflet-hash.js' {
  declare module.exports: $Exports<'mapbox.js/test/manual/leaflet-hash'>;
}
declare module 'mapbox.js/test/spec/attribution_control.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/attribution_control'>;
}
declare module 'mapbox.js/test/spec/feature_layer.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/feature_layer'>;
}
declare module 'mapbox.js/test/spec/format_url.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/format_url'>;
}
declare module 'mapbox.js/test/spec/geocoder_control.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/geocoder_control'>;
}
declare module 'mapbox.js/test/spec/geocoder.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/geocoder'>;
}
declare module 'mapbox.js/test/spec/grid_control.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/grid_control'>;
}
declare module 'mapbox.js/test/spec/grid_layer.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/grid_layer'>;
}
declare module 'mapbox.js/test/spec/grid.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/grid'>;
}
declare module 'mapbox.js/test/spec/legend_control.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/legend_control'>;
}
declare module 'mapbox.js/test/spec/map.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/map'>;
}
declare module 'mapbox.js/test/spec/mapbox_logo.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/mapbox_logo'>;
}
declare module 'mapbox.js/test/spec/marker.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/marker'>;
}
declare module 'mapbox.js/test/spec/request.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/request'>;
}
declare module 'mapbox.js/test/spec/security.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/security'>;
}
declare module 'mapbox.js/test/spec/share_control.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/share_control'>;
}
declare module 'mapbox.js/test/spec/simplestyle.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/simplestyle'>;
}
declare module 'mapbox.js/test/spec/style_layer.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/style_layer'>;
}
declare module 'mapbox.js/test/spec/template.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/template'>;
}
declare module 'mapbox.js/test/spec/tile_layer.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/tile_layer'>;
}
declare module 'mapbox.js/test/spec/util.js' {
  declare module.exports: $Exports<'mapbox.js/test/spec/util'>;
}
