// flow-typed signature: 696396861e99915bccf36ff4efdffafe
// flow-typed version: <<STUB>>/next-runtime-dotenv_v^1.0.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-runtime-dotenv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-runtime-dotenv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-runtime-dotenv/__tests__/index' {
  declare module.exports: any;
}

declare module 'next-runtime-dotenv/example/next.config' {
  declare module.exports: any;
}

declare module 'next-runtime-dotenv/example/pages/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-runtime-dotenv/__tests__/index.js' {
  declare module.exports: $Exports<'next-runtime-dotenv/__tests__/index'>;
}
declare module 'next-runtime-dotenv/example/next.config.js' {
  declare module.exports: $Exports<'next-runtime-dotenv/example/next.config'>;
}
declare module 'next-runtime-dotenv/example/pages/index.js' {
  declare module.exports: $Exports<'next-runtime-dotenv/example/pages/index'>;
}
declare module 'next-runtime-dotenv/index' {
  declare module.exports: $Exports<'next-runtime-dotenv'>;
}
declare module 'next-runtime-dotenv/index.js' {
  declare module.exports: $Exports<'next-runtime-dotenv'>;
}
