// flow-typed signature: 59e01d61d50ed19b7379c426dbbb7585
// flow-typed version: <<STUB>>/npm_v^2.15.12/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm/bin/npm-cli' {
  declare module.exports: any;
}

declare module 'npm/bin/read-package-json' {
  declare module.exports: any;
}

declare module 'npm/cli' {
  declare module.exports: any;
}

declare module 'npm/html/static/toc' {
  declare module.exports: any;
}

declare module 'npm/lib/access' {
  declare module.exports: any;
}

declare module 'npm/lib/adduser' {
  declare module.exports: any;
}

declare module 'npm/lib/bin' {
  declare module.exports: any;
}

declare module 'npm/lib/bugs' {
  declare module.exports: any;
}

declare module 'npm/lib/build' {
  declare module.exports: any;
}

declare module 'npm/lib/cache' {
  declare module.exports: any;
}

declare module 'npm/lib/cache/add-local-tarball' {
  declare module.exports: any;
}

declare module 'npm/lib/cache/add-local' {
  declare module.exports: any;
}

declare module 'npm/lib/cache/add-named' {
  declare module.exports: any;
}

declare module 'npm/lib/cache/add-remote-git' {
  declare module.exports: any;
}

declare module 'npm/lib/cache/add-remote-tarball' {
  declare module.exports: any;
}

declare module 'npm/lib/cache/cached-package-root' {
  declare module.exports: any;
}

declare module 'npm/lib/cache/caching-client' {
  declare module.exports: any;
}

declare module 'npm/lib/cache/get-stat' {
  declare module.exports: any;
}

declare module 'npm/lib/cache/update-index' {
  declare module.exports: any;
}

declare module 'npm/lib/completion' {
  declare module.exports: any;
}

declare module 'npm/lib/config' {
  declare module.exports: any;
}

declare module 'npm/lib/config/clear-credentials-by-uri' {
  declare module.exports: any;
}

declare module 'npm/lib/config/core' {
  declare module.exports: any;
}

declare module 'npm/lib/config/defaults' {
  declare module.exports: any;
}

declare module 'npm/lib/config/find-prefix' {
  declare module.exports: any;
}

declare module 'npm/lib/config/get-credentials-by-uri' {
  declare module.exports: any;
}

declare module 'npm/lib/config/load-cafile' {
  declare module.exports: any;
}

declare module 'npm/lib/config/load-prefix' {
  declare module.exports: any;
}

declare module 'npm/lib/config/load-uid' {
  declare module.exports: any;
}

declare module 'npm/lib/config/nerf-dart' {
  declare module.exports: any;
}

declare module 'npm/lib/config/set-credentials-by-uri' {
  declare module.exports: any;
}

declare module 'npm/lib/config/set-user' {
  declare module.exports: any;
}

declare module 'npm/lib/dedupe' {
  declare module.exports: any;
}

declare module 'npm/lib/deprecate' {
  declare module.exports: any;
}

declare module 'npm/lib/dist-tag' {
  declare module.exports: any;
}

declare module 'npm/lib/docs' {
  declare module.exports: any;
}

declare module 'npm/lib/edit' {
  declare module.exports: any;
}

declare module 'npm/lib/explore' {
  declare module.exports: any;
}

declare module 'npm/lib/faq' {
  declare module.exports: any;
}

declare module 'npm/lib/get' {
  declare module.exports: any;
}

declare module 'npm/lib/help-search' {
  declare module.exports: any;
}

declare module 'npm/lib/help' {
  declare module.exports: any;
}

declare module 'npm/lib/init' {
  declare module.exports: any;
}

declare module 'npm/lib/install' {
  declare module.exports: any;
}

declare module 'npm/lib/link' {
  declare module.exports: any;
}

declare module 'npm/lib/logout' {
  declare module.exports: any;
}

declare module 'npm/lib/ls' {
  declare module.exports: any;
}

declare module 'npm/lib/npm' {
  declare module.exports: any;
}

declare module 'npm/lib/outdated' {
  declare module.exports: any;
}

declare module 'npm/lib/owner' {
  declare module.exports: any;
}

declare module 'npm/lib/pack' {
  declare module.exports: any;
}

declare module 'npm/lib/ping' {
  declare module.exports: any;
}

declare module 'npm/lib/prefix' {
  declare module.exports: any;
}

declare module 'npm/lib/prune' {
  declare module.exports: any;
}

declare module 'npm/lib/publish' {
  declare module.exports: any;
}

declare module 'npm/lib/rebuild' {
  declare module.exports: any;
}

declare module 'npm/lib/repo' {
  declare module.exports: any;
}

declare module 'npm/lib/restart' {
  declare module.exports: any;
}

declare module 'npm/lib/root' {
  declare module.exports: any;
}

declare module 'npm/lib/run-script' {
  declare module.exports: any;
}

declare module 'npm/lib/search' {
  declare module.exports: any;
}

declare module 'npm/lib/set' {
  declare module.exports: any;
}

declare module 'npm/lib/shrinkwrap' {
  declare module.exports: any;
}

declare module 'npm/lib/star' {
  declare module.exports: any;
}

declare module 'npm/lib/stars' {
  declare module.exports: any;
}

declare module 'npm/lib/start' {
  declare module.exports: any;
}

declare module 'npm/lib/stop' {
  declare module.exports: any;
}

declare module 'npm/lib/substack' {
  declare module.exports: any;
}

declare module 'npm/lib/tag' {
  declare module.exports: any;
}

declare module 'npm/lib/team' {
  declare module.exports: any;
}

declare module 'npm/lib/test' {
  declare module.exports: any;
}

declare module 'npm/lib/unbuild' {
  declare module.exports: any;
}

declare module 'npm/lib/uninstall' {
  declare module.exports: any;
}

declare module 'npm/lib/unpublish' {
  declare module.exports: any;
}

declare module 'npm/lib/update' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/completion/file-completion' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/completion/installed-deep' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/completion/installed-shallow' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/correct-mkdir' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/depr-check' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/error-handler' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/gently-rm' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/get-publish-config' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/git' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/lifecycle' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/link' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/locker' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/map-to-registry' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/read-local-package' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/spawn' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/tar' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/umask' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/warn-deprecated' {
  declare module.exports: any;
}

declare module 'npm/lib/version' {
  declare module.exports: any;
}

declare module 'npm/lib/view' {
  declare module.exports: any;
}

declare module 'npm/lib/visnup' {
  declare module.exports: any;
}

declare module 'npm/lib/whoami' {
  declare module.exports: any;
}

declare module 'npm/lib/xmas' {
  declare module.exports: any;
}

declare module 'npm/scripts/index-build' {
  declare module.exports: any;
}

declare module 'npm/scripts/publish-tag' {
  declare module.exports: any;
}

declare module 'npm/test/common-tap' {
  declare module.exports: any;
}

declare module 'npm/test/fixtures/onload' {
  declare module.exports: any;
}

declare module 'npm/test/packages/npm-test-array-bin/test' {
  declare module.exports: any;
}

declare module 'npm/test/packages/npm-test-blerg/test' {
  declare module.exports: any;
}

declare module 'npm/test/packages/npm-test-blerg3/test' {
  declare module.exports: any;
}

declare module 'npm/test/packages/npm-test-bundled-git/test' {
  declare module.exports: any;
}

declare module 'npm/test/packages/npm-test-dir-bin/test' {
  declare module.exports: any;
}

declare module 'npm/test/packages/npm-test-ignore-nested-nm/test' {
  declare module.exports: any;
}

declare module 'npm/test/packages/npm-test-missing-bindir/test' {
  declare module.exports: any;
}

declare module 'npm/test/packages/npm-test-optional-deps/test' {
  declare module.exports: any;
}

declare module 'npm/test/run' {
  declare module.exports: any;
}

declare module 'npm/test/tap/00-check-mock-dep' {
  declare module.exports: any;
}

declare module 'npm/test/tap/00-config-setup' {
  declare module.exports: any;
}

declare module 'npm/test/tap/00-verify-bundle-deps' {
  declare module.exports: any;
}

declare module 'npm/test/tap/00-verify-ls-ok' {
  declare module.exports: any;
}

declare module 'npm/test/tap/404-parent' {
  declare module.exports: any;
}

declare module 'npm/test/tap/404-private-registry-scoped' {
  declare module.exports: any;
}

declare module 'npm/test/tap/404-private-registry' {
  declare module.exports: any;
}

declare module 'npm/test/tap/access' {
  declare module.exports: any;
}

declare module 'npm/test/tap/add-local' {
  declare module.exports: any;
}

declare module 'npm/test/tap/add-named-update-protocol-port' {
  declare module.exports: any;
}

declare module 'npm/test/tap/add-remote-git-fake-windows' {
  declare module.exports: any;
}

declare module 'npm/test/tap/add-remote-git-file' {
  declare module.exports: any;
}

declare module 'npm/test/tap/add-remote-git-get-resolved' {
  declare module.exports: any;
}

declare module 'npm/test/tap/add-remote-git-shrinkwrap' {
  declare module.exports: any;
}

declare module 'npm/test/tap/add-remote-git' {
  declare module.exports: any;
}

declare module 'npm/test/tap/adduser-always-auth' {
  declare module.exports: any;
}

declare module 'npm/test/tap/adduser-legacy-auth' {
  declare module.exports: any;
}

declare module 'npm/test/tap/bearer-token-check' {
  declare module.exports: any;
}

declare module 'npm/test/tap/bin' {
  declare module.exports: any;
}

declare module 'npm/test/tap/bitbucket-https-url-with-creds-package' {
  declare module.exports: any;
}

declare module 'npm/test/tap/bitbucket-https-url-with-creds' {
  declare module.exports: any;
}

declare module 'npm/test/tap/bitbucket-shortcut-package' {
  declare module.exports: any;
}

declare module 'npm/test/tap/bitbucket-shortcut' {
  declare module.exports: any;
}

declare module 'npm/test/tap/bugs' {
  declare module.exports: any;
}

declare module 'npm/test/tap/build-already-built' {
  declare module.exports: any;
}

declare module 'npm/test/tap/builtin-config' {
  declare module.exports: any;
}

declare module 'npm/test/tap/bundled-dependencies-nonarray' {
  declare module.exports: any;
}

declare module 'npm/test/tap/cache-add-localdir-fallback' {
  declare module.exports: any;
}

declare module 'npm/test/tap/cache-add-unpublished' {
  declare module.exports: any;
}

declare module 'npm/test/tap/cache-shasum-fork' {
  declare module.exports: any;
}

declare module 'npm/test/tap/cache-shasum' {
  declare module.exports: any;
}

declare module 'npm/test/tap/circular-dep' {
  declare module.exports: any;
}

declare module 'npm/test/tap/config-basic' {
  declare module.exports: any;
}

declare module 'npm/test/tap/config-builtin' {
  declare module.exports: any;
}

declare module 'npm/test/tap/config-certfile' {
  declare module.exports: any;
}

declare module 'npm/test/tap/config-credentials' {
  declare module.exports: any;
}

declare module 'npm/test/tap/config-edit' {
  declare module.exports: any;
}

declare module 'npm/test/tap/config-malformed' {
  declare module.exports: any;
}

declare module 'npm/test/tap/config-meta' {
  declare module.exports: any;
}

declare module 'npm/test/tap/config-new-cafile' {
  declare module.exports: any;
}

declare module 'npm/test/tap/config-private' {
  declare module.exports: any;
}

declare module 'npm/test/tap/config-project' {
  declare module.exports: any;
}

declare module 'npm/test/tap/config-save' {
  declare module.exports: any;
}

declare module 'npm/test/tap/correct-mkdir' {
  declare module.exports: any;
}

declare module 'npm/test/tap/dedupe-scoped' {
  declare module.exports: any;
}

declare module 'npm/test/tap/dedupe' {
  declare module.exports: any;
}

declare module 'npm/test/tap/deprecate' {
  declare module.exports: any;
}

declare module 'npm/test/tap/dist-tag' {
  declare module.exports: any;
}

declare module 'npm/test/tap/false-name' {
  declare module.exports: any;
}

declare module 'npm/test/tap/files-and-ignores' {
  declare module.exports: any;
}

declare module 'npm/test/tap/gently-rm-overeager' {
  declare module.exports: any;
}

declare module 'npm/test/tap/gently-rm-symlink' {
  declare module.exports: any;
}

declare module 'npm/test/tap/get' {
  declare module.exports: any;
}

declare module 'npm/test/tap/gist-short-shortcut-package' {
  declare module.exports: any;
}

declare module 'npm/test/tap/gist-short-shortcut' {
  declare module.exports: any;
}

declare module 'npm/test/tap/gist-shortcut-package' {
  declare module.exports: any;
}

declare module 'npm/test/tap/gist-shortcut' {
  declare module.exports: any;
}

declare module 'npm/test/tap/git-cache-locking' {
  declare module.exports: any;
}

declare module 'npm/test/tap/git-cache-no-hooks' {
  declare module.exports: any;
}

declare module 'npm/test/tap/git-dependency-install-link' {
  declare module.exports: any;
}

declare module 'npm/test/tap/git-npmignore' {
  declare module.exports: any;
}

declare module 'npm/test/tap/git-races' {
  declare module.exports: any;
}

declare module 'npm/test/tap/github-shortcut-package' {
  declare module.exports: any;
}

declare module 'npm/test/tap/github-shortcut' {
  declare module.exports: any;
}

declare module 'npm/test/tap/gitlab-shortcut-package' {
  declare module.exports: any;
}

declare module 'npm/test/tap/gitlab-shortcut' {
  declare module.exports: any;
}

declare module 'npm/test/tap/global-prefix-set-in-userconfig' {
  declare module.exports: any;
}

declare module 'npm/test/tap/graceful-restart' {
  declare module.exports: any;
}

declare module 'npm/test/tap/ignore-install-link' {
  declare module.exports: any;
}

declare module 'npm/test/tap/ignore-scripts' {
  declare module.exports: any;
}

declare module 'npm/test/tap/ignore-shrinkwrap' {
  declare module.exports: any;
}

declare module 'npm/test/tap/init-interrupt' {
  declare module.exports: any;
}

declare module 'npm/test/tap/install-at-locally' {
  declare module.exports: any;
}

declare module 'npm/test/tap/install-bad-man' {
  declare module.exports: any;
}

declare module 'npm/test/tap/install-cli-production' {
  declare module.exports: any;
}

declare module 'npm/test/tap/install-cli-unicode' {
  declare module.exports: any;
}

declare module 'npm/test/tap/install-from-local' {
  declare module.exports: any;
}

declare module 'npm/test/tap/install-link-scripts' {
  declare module.exports: any;
}

declare module 'npm/test/tap/install-man' {
  declare module.exports: any;
}

declare module 'npm/test/tap/install-noargs-dev' {
  declare module.exports: any;
}

declare module 'npm/test/tap/install-preferglobal-warnings' {
  declare module.exports: any;
}

declare module 'npm/test/tap/install-save-exact' {
  declare module.exports: any;
}

declare module 'npm/test/tap/install-save-local' {
  declare module.exports: any;
}

declare module 'npm/test/tap/install-save-prefix' {
  declare module.exports: any;
}

declare module 'npm/test/tap/install-scoped-already-installed' {
  declare module.exports: any;
}

declare module 'npm/test/tap/install-scoped-link' {
  declare module.exports: any;
}

declare module 'npm/test/tap/install-scoped-with-peer-dependency' {
  declare module.exports: any;
}

declare module 'npm/test/tap/install-shrinkwrap-equals-ls' {
  declare module.exports: any;
}

declare module 'npm/test/tap/install-with-dev-dep-duplicate' {
  declare module.exports: any;
}

declare module 'npm/test/tap/invalid-cmd-exit-code' {
  declare module.exports: any;
}

declare module 'npm/test/tap/legacy-array-bin' {
  declare module.exports: any;
}

declare module 'npm/test/tap/legacy-bundled-git' {
  declare module.exports: any;
}

declare module 'npm/test/tap/legacy-dir-bin' {
  declare module.exports: any;
}

declare module 'npm/test/tap/legacy-ignore-nested-nm' {
  declare module.exports: any;
}

declare module 'npm/test/tap/legacy-missing-bindir' {
  declare module.exports: any;
}

declare module 'npm/test/tap/legacy-no-auth-leak' {
  declare module.exports: any;
}

declare module 'npm/test/tap/legacy-npm-self-install' {
  declare module.exports: any;
}

declare module 'npm/test/tap/legacy-optional-deps' {
  declare module.exports: any;
}

declare module 'npm/test/tap/legacy-platform-all' {
  declare module.exports: any;
}

declare module 'npm/test/tap/legacy-platform' {
  declare module.exports: any;
}

declare module 'npm/test/tap/legacy-private' {
  declare module.exports: any;
}

declare module 'npm/test/tap/legacy-shrinkwrap' {
  declare module.exports: any;
}

declare module 'npm/test/tap/legacy-test-package' {
  declare module.exports: any;
}

declare module 'npm/test/tap/legacy-url-dep' {
  declare module.exports: any;
}

declare module 'npm/test/tap/lifecycle-path' {
  declare module.exports: any;
}

declare module 'npm/test/tap/lifecycle-signal' {
  declare module.exports: any;
}

declare module 'npm/test/tap/lifecycle' {
  declare module.exports: any;
}

declare module 'npm/test/tap/link' {
  declare module.exports: any;
}

declare module 'npm/test/tap/locker' {
  declare module.exports: any;
}

declare module 'npm/test/tap/logout' {
  declare module.exports: any;
}

declare module 'npm/test/tap/ls-depth-cli' {
  declare module.exports: any;
}

declare module 'npm/test/tap/ls-depth-unmet' {
  declare module.exports: any;
}

declare module 'npm/test/tap/ls-env' {
  declare module.exports: any;
}

declare module 'npm/test/tap/ls-l-depth-0' {
  declare module.exports: any;
}

declare module 'npm/test/tap/ls-no-results' {
  declare module.exports: any;
}

declare module 'npm/test/tap/map-to-registry' {
  declare module.exports: any;
}

declare module 'npm/test/tap/nerf-dart' {
  declare module.exports: any;
}

declare module 'npm/test/tap/nested-extraneous' {
  declare module.exports: any;
}

declare module 'npm/test/tap/noargs-install-config-save' {
  declare module.exports: any;
}

declare module 'npm/test/tap/npm-api-not-loaded-error' {
  declare module.exports: any;
}

declare module 'npm/test/tap/onload' {
  declare module.exports: any;
}

declare module 'npm/test/tap/optional-metadep-rollback-collision' {
  declare module.exports: any;
}

declare module 'npm/test/tap/outdated-color' {
  declare module.exports: any;
}

declare module 'npm/test/tap/outdated-depth-deep' {
  declare module.exports: any;
}

declare module 'npm/test/tap/outdated-depth-integer' {
  declare module.exports: any;
}

declare module 'npm/test/tap/outdated-depth' {
  declare module.exports: any;
}

declare module 'npm/test/tap/outdated-git' {
  declare module.exports: any;
}

declare module 'npm/test/tap/outdated-include-devdependencies' {
  declare module.exports: any;
}

declare module 'npm/test/tap/outdated-json' {
  declare module.exports: any;
}

declare module 'npm/test/tap/outdated-local' {
  declare module.exports: any;
}

declare module 'npm/test/tap/outdated-long' {
  declare module.exports: any;
}

declare module 'npm/test/tap/outdated-new-versions' {
  declare module.exports: any;
}

declare module 'npm/test/tap/outdated-notarget' {
  declare module.exports: any;
}

declare module 'npm/test/tap/outdated-private' {
  declare module.exports: any;
}

declare module 'npm/test/tap/outdated-symlink' {
  declare module.exports: any;
}

declare module 'npm/test/tap/outdated' {
  declare module.exports: any;
}

declare module 'npm/test/tap/owner' {
  declare module.exports: any;
}

declare module 'npm/test/tap/pack-scoped' {
  declare module.exports: any;
}

declare module 'npm/test/tap/peer-deps-invalid' {
  declare module.exports: any;
}

declare module 'npm/test/tap/peer-deps-toplevel' {
  declare module.exports: any;
}

declare module 'npm/test/tap/peer-deps-without-package-json' {
  declare module.exports: any;
}

declare module 'npm/test/tap/peer-deps' {
  declare module.exports: any;
}

declare module 'npm/test/tap/ping' {
  declare module.exports: any;
}

declare module 'npm/test/tap/prepublish' {
  declare module.exports: any;
}

declare module 'npm/test/tap/prune' {
  declare module.exports: any;
}

declare module 'npm/test/tap/publish-access-scoped' {
  declare module.exports: any;
}

declare module 'npm/test/tap/publish-access-unscoped-restricted-fails' {
  declare module.exports: any;
}

declare module 'npm/test/tap/publish-access-unscoped' {
  declare module.exports: any;
}

declare module 'npm/test/tap/publish-config' {
  declare module.exports: any;
}

declare module 'npm/test/tap/publish-invalid-semver-tag' {
  declare module.exports: any;
}

declare module 'npm/test/tap/publish-scoped' {
  declare module.exports: any;
}

declare module 'npm/test/tap/pwd-prefix' {
  declare module.exports: any;
}

declare module 'npm/test/tap/referer' {
  declare module.exports: any;
}

declare module 'npm/test/tap/registry' {
  declare module.exports: any;
}

declare module 'npm/test/tap/repo' {
  declare module.exports: any;
}

declare module 'npm/test/tap/run-script-filter-private' {
  declare module.exports: any;
}

declare module 'npm/test/tap/run-script' {
  declare module.exports: any;
}

declare module 'npm/test/tap/scripts-whitespace-windows' {
  declare module.exports: any;
}

declare module 'npm/test/tap/search' {
  declare module.exports: any;
}

declare module 'npm/test/tap/semver-doc' {
  declare module.exports: any;
}

declare module 'npm/test/tap/semver-tag' {
  declare module.exports: any;
}

declare module 'npm/test/tap/shrinkwrap-dev-dependency' {
  declare module.exports: any;
}

declare module 'npm/test/tap/shrinkwrap-empty-deps' {
  declare module.exports: any;
}

declare module 'npm/test/tap/shrinkwrap-local-dependency' {
  declare module.exports: any;
}

declare module 'npm/test/tap/shrinkwrap-prod-dependency' {
  declare module.exports: any;
}

declare module 'npm/test/tap/shrinkwrap-scoped-auth' {
  declare module.exports: any;
}

declare module 'npm/test/tap/shrinkwrap-shared-dev-dependency' {
  declare module.exports: any;
}

declare module 'npm/test/tap/sorted-package-json' {
  declare module.exports: any;
}

declare module 'npm/test/tap/spawn-enoent-help' {
  declare module.exports: any;
}

declare module 'npm/test/tap/spawn-enoent' {
  declare module.exports: any;
}

declare module 'npm/test/tap/splat-with-only-prerelease-to-latest' {
  declare module.exports: any;
}

declare module 'npm/test/tap/startstop' {
  declare module.exports: any;
}

declare module 'npm/test/tap/tag-version-prefix' {
  declare module.exports: any;
}

declare module 'npm/test/tap/team' {
  declare module.exports: any;
}

declare module 'npm/test/tap/test-run-ls' {
  declare module.exports: any;
}

declare module 'npm/test/tap/umask-lifecycle' {
  declare module.exports: any;
}

declare module 'npm/test/tap/uninstall-package' {
  declare module.exports: any;
}

declare module 'npm/test/tap/unpack-foreign-tarball' {
  declare module.exports: any;
}

declare module 'npm/test/tap/unpublish-config' {
  declare module.exports: any;
}

declare module 'npm/test/tap/update-examples' {
  declare module.exports: any;
}

declare module 'npm/test/tap/update-index' {
  declare module.exports: any;
}

declare module 'npm/test/tap/update-save' {
  declare module.exports: any;
}

declare module 'npm/test/tap/url-dependencies' {
  declare module.exports: any;
}

declare module 'npm/test/tap/version-git-not-clean' {
  declare module.exports: any;
}

declare module 'npm/test/tap/version-lifecycle' {
  declare module.exports: any;
}

declare module 'npm/test/tap/version-message-config' {
  declare module.exports: any;
}

declare module 'npm/test/tap/version-no-git' {
  declare module.exports: any;
}

declare module 'npm/test/tap/version-no-package' {
  declare module.exports: any;
}

declare module 'npm/test/tap/version-no-tags' {
  declare module.exports: any;
}

declare module 'npm/test/tap/version-sub-directory' {
  declare module.exports: any;
}

declare module 'npm/test/tap/version-update-shrinkwrap' {
  declare module.exports: any;
}

declare module 'npm/test/tap/view' {
  declare module.exports: any;
}

declare module 'npm/test/tap/whoami' {
  declare module.exports: any;
}

declare module 'npm/test/tap/zz-cleanup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm/bin/npm-cli.js' {
  declare module.exports: $Exports<'npm/bin/npm-cli'>;
}
declare module 'npm/bin/read-package-json.js' {
  declare module.exports: $Exports<'npm/bin/read-package-json'>;
}
declare module 'npm/cli.js' {
  declare module.exports: $Exports<'npm/cli'>;
}
declare module 'npm/html/static/toc.js' {
  declare module.exports: $Exports<'npm/html/static/toc'>;
}
declare module 'npm/lib/access.js' {
  declare module.exports: $Exports<'npm/lib/access'>;
}
declare module 'npm/lib/adduser.js' {
  declare module.exports: $Exports<'npm/lib/adduser'>;
}
declare module 'npm/lib/bin.js' {
  declare module.exports: $Exports<'npm/lib/bin'>;
}
declare module 'npm/lib/bugs.js' {
  declare module.exports: $Exports<'npm/lib/bugs'>;
}
declare module 'npm/lib/build.js' {
  declare module.exports: $Exports<'npm/lib/build'>;
}
declare module 'npm/lib/cache.js' {
  declare module.exports: $Exports<'npm/lib/cache'>;
}
declare module 'npm/lib/cache/add-local-tarball.js' {
  declare module.exports: $Exports<'npm/lib/cache/add-local-tarball'>;
}
declare module 'npm/lib/cache/add-local.js' {
  declare module.exports: $Exports<'npm/lib/cache/add-local'>;
}
declare module 'npm/lib/cache/add-named.js' {
  declare module.exports: $Exports<'npm/lib/cache/add-named'>;
}
declare module 'npm/lib/cache/add-remote-git.js' {
  declare module.exports: $Exports<'npm/lib/cache/add-remote-git'>;
}
declare module 'npm/lib/cache/add-remote-tarball.js' {
  declare module.exports: $Exports<'npm/lib/cache/add-remote-tarball'>;
}
declare module 'npm/lib/cache/cached-package-root.js' {
  declare module.exports: $Exports<'npm/lib/cache/cached-package-root'>;
}
declare module 'npm/lib/cache/caching-client.js' {
  declare module.exports: $Exports<'npm/lib/cache/caching-client'>;
}
declare module 'npm/lib/cache/get-stat.js' {
  declare module.exports: $Exports<'npm/lib/cache/get-stat'>;
}
declare module 'npm/lib/cache/update-index.js' {
  declare module.exports: $Exports<'npm/lib/cache/update-index'>;
}
declare module 'npm/lib/completion.js' {
  declare module.exports: $Exports<'npm/lib/completion'>;
}
declare module 'npm/lib/config.js' {
  declare module.exports: $Exports<'npm/lib/config'>;
}
declare module 'npm/lib/config/clear-credentials-by-uri.js' {
  declare module.exports: $Exports<'npm/lib/config/clear-credentials-by-uri'>;
}
declare module 'npm/lib/config/core.js' {
  declare module.exports: $Exports<'npm/lib/config/core'>;
}
declare module 'npm/lib/config/defaults.js' {
  declare module.exports: $Exports<'npm/lib/config/defaults'>;
}
declare module 'npm/lib/config/find-prefix.js' {
  declare module.exports: $Exports<'npm/lib/config/find-prefix'>;
}
declare module 'npm/lib/config/get-credentials-by-uri.js' {
  declare module.exports: $Exports<'npm/lib/config/get-credentials-by-uri'>;
}
declare module 'npm/lib/config/load-cafile.js' {
  declare module.exports: $Exports<'npm/lib/config/load-cafile'>;
}
declare module 'npm/lib/config/load-prefix.js' {
  declare module.exports: $Exports<'npm/lib/config/load-prefix'>;
}
declare module 'npm/lib/config/load-uid.js' {
  declare module.exports: $Exports<'npm/lib/config/load-uid'>;
}
declare module 'npm/lib/config/nerf-dart.js' {
  declare module.exports: $Exports<'npm/lib/config/nerf-dart'>;
}
declare module 'npm/lib/config/set-credentials-by-uri.js' {
  declare module.exports: $Exports<'npm/lib/config/set-credentials-by-uri'>;
}
declare module 'npm/lib/config/set-user.js' {
  declare module.exports: $Exports<'npm/lib/config/set-user'>;
}
declare module 'npm/lib/dedupe.js' {
  declare module.exports: $Exports<'npm/lib/dedupe'>;
}
declare module 'npm/lib/deprecate.js' {
  declare module.exports: $Exports<'npm/lib/deprecate'>;
}
declare module 'npm/lib/dist-tag.js' {
  declare module.exports: $Exports<'npm/lib/dist-tag'>;
}
declare module 'npm/lib/docs.js' {
  declare module.exports: $Exports<'npm/lib/docs'>;
}
declare module 'npm/lib/edit.js' {
  declare module.exports: $Exports<'npm/lib/edit'>;
}
declare module 'npm/lib/explore.js' {
  declare module.exports: $Exports<'npm/lib/explore'>;
}
declare module 'npm/lib/faq.js' {
  declare module.exports: $Exports<'npm/lib/faq'>;
}
declare module 'npm/lib/get.js' {
  declare module.exports: $Exports<'npm/lib/get'>;
}
declare module 'npm/lib/help-search.js' {
  declare module.exports: $Exports<'npm/lib/help-search'>;
}
declare module 'npm/lib/help.js' {
  declare module.exports: $Exports<'npm/lib/help'>;
}
declare module 'npm/lib/init.js' {
  declare module.exports: $Exports<'npm/lib/init'>;
}
declare module 'npm/lib/install.js' {
  declare module.exports: $Exports<'npm/lib/install'>;
}
declare module 'npm/lib/link.js' {
  declare module.exports: $Exports<'npm/lib/link'>;
}
declare module 'npm/lib/logout.js' {
  declare module.exports: $Exports<'npm/lib/logout'>;
}
declare module 'npm/lib/ls.js' {
  declare module.exports: $Exports<'npm/lib/ls'>;
}
declare module 'npm/lib/npm.js' {
  declare module.exports: $Exports<'npm/lib/npm'>;
}
declare module 'npm/lib/outdated.js' {
  declare module.exports: $Exports<'npm/lib/outdated'>;
}
declare module 'npm/lib/owner.js' {
  declare module.exports: $Exports<'npm/lib/owner'>;
}
declare module 'npm/lib/pack.js' {
  declare module.exports: $Exports<'npm/lib/pack'>;
}
declare module 'npm/lib/ping.js' {
  declare module.exports: $Exports<'npm/lib/ping'>;
}
declare module 'npm/lib/prefix.js' {
  declare module.exports: $Exports<'npm/lib/prefix'>;
}
declare module 'npm/lib/prune.js' {
  declare module.exports: $Exports<'npm/lib/prune'>;
}
declare module 'npm/lib/publish.js' {
  declare module.exports: $Exports<'npm/lib/publish'>;
}
declare module 'npm/lib/rebuild.js' {
  declare module.exports: $Exports<'npm/lib/rebuild'>;
}
declare module 'npm/lib/repo.js' {
  declare module.exports: $Exports<'npm/lib/repo'>;
}
declare module 'npm/lib/restart.js' {
  declare module.exports: $Exports<'npm/lib/restart'>;
}
declare module 'npm/lib/root.js' {
  declare module.exports: $Exports<'npm/lib/root'>;
}
declare module 'npm/lib/run-script.js' {
  declare module.exports: $Exports<'npm/lib/run-script'>;
}
declare module 'npm/lib/search.js' {
  declare module.exports: $Exports<'npm/lib/search'>;
}
declare module 'npm/lib/set.js' {
  declare module.exports: $Exports<'npm/lib/set'>;
}
declare module 'npm/lib/shrinkwrap.js' {
  declare module.exports: $Exports<'npm/lib/shrinkwrap'>;
}
declare module 'npm/lib/star.js' {
  declare module.exports: $Exports<'npm/lib/star'>;
}
declare module 'npm/lib/stars.js' {
  declare module.exports: $Exports<'npm/lib/stars'>;
}
declare module 'npm/lib/start.js' {
  declare module.exports: $Exports<'npm/lib/start'>;
}
declare module 'npm/lib/stop.js' {
  declare module.exports: $Exports<'npm/lib/stop'>;
}
declare module 'npm/lib/substack.js' {
  declare module.exports: $Exports<'npm/lib/substack'>;
}
declare module 'npm/lib/tag.js' {
  declare module.exports: $Exports<'npm/lib/tag'>;
}
declare module 'npm/lib/team.js' {
  declare module.exports: $Exports<'npm/lib/team'>;
}
declare module 'npm/lib/test.js' {
  declare module.exports: $Exports<'npm/lib/test'>;
}
declare module 'npm/lib/unbuild.js' {
  declare module.exports: $Exports<'npm/lib/unbuild'>;
}
declare module 'npm/lib/uninstall.js' {
  declare module.exports: $Exports<'npm/lib/uninstall'>;
}
declare module 'npm/lib/unpublish.js' {
  declare module.exports: $Exports<'npm/lib/unpublish'>;
}
declare module 'npm/lib/update.js' {
  declare module.exports: $Exports<'npm/lib/update'>;
}
declare module 'npm/lib/utils/completion/file-completion.js' {
  declare module.exports: $Exports<'npm/lib/utils/completion/file-completion'>;
}
declare module 'npm/lib/utils/completion/installed-deep.js' {
  declare module.exports: $Exports<'npm/lib/utils/completion/installed-deep'>;
}
declare module 'npm/lib/utils/completion/installed-shallow.js' {
  declare module.exports: $Exports<'npm/lib/utils/completion/installed-shallow'>;
}
declare module 'npm/lib/utils/correct-mkdir.js' {
  declare module.exports: $Exports<'npm/lib/utils/correct-mkdir'>;
}
declare module 'npm/lib/utils/depr-check.js' {
  declare module.exports: $Exports<'npm/lib/utils/depr-check'>;
}
declare module 'npm/lib/utils/error-handler.js' {
  declare module.exports: $Exports<'npm/lib/utils/error-handler'>;
}
declare module 'npm/lib/utils/gently-rm.js' {
  declare module.exports: $Exports<'npm/lib/utils/gently-rm'>;
}
declare module 'npm/lib/utils/get-publish-config.js' {
  declare module.exports: $Exports<'npm/lib/utils/get-publish-config'>;
}
declare module 'npm/lib/utils/git.js' {
  declare module.exports: $Exports<'npm/lib/utils/git'>;
}
declare module 'npm/lib/utils/lifecycle.js' {
  declare module.exports: $Exports<'npm/lib/utils/lifecycle'>;
}
declare module 'npm/lib/utils/link.js' {
  declare module.exports: $Exports<'npm/lib/utils/link'>;
}
declare module 'npm/lib/utils/locker.js' {
  declare module.exports: $Exports<'npm/lib/utils/locker'>;
}
declare module 'npm/lib/utils/map-to-registry.js' {
  declare module.exports: $Exports<'npm/lib/utils/map-to-registry'>;
}
declare module 'npm/lib/utils/read-local-package.js' {
  declare module.exports: $Exports<'npm/lib/utils/read-local-package'>;
}
declare module 'npm/lib/utils/spawn.js' {
  declare module.exports: $Exports<'npm/lib/utils/spawn'>;
}
declare module 'npm/lib/utils/tar.js' {
  declare module.exports: $Exports<'npm/lib/utils/tar'>;
}
declare module 'npm/lib/utils/umask.js' {
  declare module.exports: $Exports<'npm/lib/utils/umask'>;
}
declare module 'npm/lib/utils/warn-deprecated.js' {
  declare module.exports: $Exports<'npm/lib/utils/warn-deprecated'>;
}
declare module 'npm/lib/version.js' {
  declare module.exports: $Exports<'npm/lib/version'>;
}
declare module 'npm/lib/view.js' {
  declare module.exports: $Exports<'npm/lib/view'>;
}
declare module 'npm/lib/visnup.js' {
  declare module.exports: $Exports<'npm/lib/visnup'>;
}
declare module 'npm/lib/whoami.js' {
  declare module.exports: $Exports<'npm/lib/whoami'>;
}
declare module 'npm/lib/xmas.js' {
  declare module.exports: $Exports<'npm/lib/xmas'>;
}
declare module 'npm/scripts/index-build.js' {
  declare module.exports: $Exports<'npm/scripts/index-build'>;
}
declare module 'npm/scripts/publish-tag.js' {
  declare module.exports: $Exports<'npm/scripts/publish-tag'>;
}
declare module 'npm/test/common-tap.js' {
  declare module.exports: $Exports<'npm/test/common-tap'>;
}
declare module 'npm/test/fixtures/onload.js' {
  declare module.exports: $Exports<'npm/test/fixtures/onload'>;
}
declare module 'npm/test/packages/npm-test-array-bin/test.js' {
  declare module.exports: $Exports<'npm/test/packages/npm-test-array-bin/test'>;
}
declare module 'npm/test/packages/npm-test-blerg/test.js' {
  declare module.exports: $Exports<'npm/test/packages/npm-test-blerg/test'>;
}
declare module 'npm/test/packages/npm-test-blerg3/test.js' {
  declare module.exports: $Exports<'npm/test/packages/npm-test-blerg3/test'>;
}
declare module 'npm/test/packages/npm-test-bundled-git/test.js' {
  declare module.exports: $Exports<'npm/test/packages/npm-test-bundled-git/test'>;
}
declare module 'npm/test/packages/npm-test-dir-bin/test.js' {
  declare module.exports: $Exports<'npm/test/packages/npm-test-dir-bin/test'>;
}
declare module 'npm/test/packages/npm-test-ignore-nested-nm/test.js' {
  declare module.exports: $Exports<'npm/test/packages/npm-test-ignore-nested-nm/test'>;
}
declare module 'npm/test/packages/npm-test-missing-bindir/test.js' {
  declare module.exports: $Exports<'npm/test/packages/npm-test-missing-bindir/test'>;
}
declare module 'npm/test/packages/npm-test-optional-deps/test.js' {
  declare module.exports: $Exports<'npm/test/packages/npm-test-optional-deps/test'>;
}
declare module 'npm/test/run.js' {
  declare module.exports: $Exports<'npm/test/run'>;
}
declare module 'npm/test/tap/00-check-mock-dep.js' {
  declare module.exports: $Exports<'npm/test/tap/00-check-mock-dep'>;
}
declare module 'npm/test/tap/00-config-setup.js' {
  declare module.exports: $Exports<'npm/test/tap/00-config-setup'>;
}
declare module 'npm/test/tap/00-verify-bundle-deps.js' {
  declare module.exports: $Exports<'npm/test/tap/00-verify-bundle-deps'>;
}
declare module 'npm/test/tap/00-verify-ls-ok.js' {
  declare module.exports: $Exports<'npm/test/tap/00-verify-ls-ok'>;
}
declare module 'npm/test/tap/404-parent.js' {
  declare module.exports: $Exports<'npm/test/tap/404-parent'>;
}
declare module 'npm/test/tap/404-private-registry-scoped.js' {
  declare module.exports: $Exports<'npm/test/tap/404-private-registry-scoped'>;
}
declare module 'npm/test/tap/404-private-registry.js' {
  declare module.exports: $Exports<'npm/test/tap/404-private-registry'>;
}
declare module 'npm/test/tap/access.js' {
  declare module.exports: $Exports<'npm/test/tap/access'>;
}
declare module 'npm/test/tap/add-local.js' {
  declare module.exports: $Exports<'npm/test/tap/add-local'>;
}
declare module 'npm/test/tap/add-named-update-protocol-port.js' {
  declare module.exports: $Exports<'npm/test/tap/add-named-update-protocol-port'>;
}
declare module 'npm/test/tap/add-remote-git-fake-windows.js' {
  declare module.exports: $Exports<'npm/test/tap/add-remote-git-fake-windows'>;
}
declare module 'npm/test/tap/add-remote-git-file.js' {
  declare module.exports: $Exports<'npm/test/tap/add-remote-git-file'>;
}
declare module 'npm/test/tap/add-remote-git-get-resolved.js' {
  declare module.exports: $Exports<'npm/test/tap/add-remote-git-get-resolved'>;
}
declare module 'npm/test/tap/add-remote-git-shrinkwrap.js' {
  declare module.exports: $Exports<'npm/test/tap/add-remote-git-shrinkwrap'>;
}
declare module 'npm/test/tap/add-remote-git.js' {
  declare module.exports: $Exports<'npm/test/tap/add-remote-git'>;
}
declare module 'npm/test/tap/adduser-always-auth.js' {
  declare module.exports: $Exports<'npm/test/tap/adduser-always-auth'>;
}
declare module 'npm/test/tap/adduser-legacy-auth.js' {
  declare module.exports: $Exports<'npm/test/tap/adduser-legacy-auth'>;
}
declare module 'npm/test/tap/bearer-token-check.js' {
  declare module.exports: $Exports<'npm/test/tap/bearer-token-check'>;
}
declare module 'npm/test/tap/bin.js' {
  declare module.exports: $Exports<'npm/test/tap/bin'>;
}
declare module 'npm/test/tap/bitbucket-https-url-with-creds-package.js' {
  declare module.exports: $Exports<'npm/test/tap/bitbucket-https-url-with-creds-package'>;
}
declare module 'npm/test/tap/bitbucket-https-url-with-creds.js' {
  declare module.exports: $Exports<'npm/test/tap/bitbucket-https-url-with-creds'>;
}
declare module 'npm/test/tap/bitbucket-shortcut-package.js' {
  declare module.exports: $Exports<'npm/test/tap/bitbucket-shortcut-package'>;
}
declare module 'npm/test/tap/bitbucket-shortcut.js' {
  declare module.exports: $Exports<'npm/test/tap/bitbucket-shortcut'>;
}
declare module 'npm/test/tap/bugs.js' {
  declare module.exports: $Exports<'npm/test/tap/bugs'>;
}
declare module 'npm/test/tap/build-already-built.js' {
  declare module.exports: $Exports<'npm/test/tap/build-already-built'>;
}
declare module 'npm/test/tap/builtin-config.js' {
  declare module.exports: $Exports<'npm/test/tap/builtin-config'>;
}
declare module 'npm/test/tap/bundled-dependencies-nonarray.js' {
  declare module.exports: $Exports<'npm/test/tap/bundled-dependencies-nonarray'>;
}
declare module 'npm/test/tap/cache-add-localdir-fallback.js' {
  declare module.exports: $Exports<'npm/test/tap/cache-add-localdir-fallback'>;
}
declare module 'npm/test/tap/cache-add-unpublished.js' {
  declare module.exports: $Exports<'npm/test/tap/cache-add-unpublished'>;
}
declare module 'npm/test/tap/cache-shasum-fork.js' {
  declare module.exports: $Exports<'npm/test/tap/cache-shasum-fork'>;
}
declare module 'npm/test/tap/cache-shasum.js' {
  declare module.exports: $Exports<'npm/test/tap/cache-shasum'>;
}
declare module 'npm/test/tap/circular-dep.js' {
  declare module.exports: $Exports<'npm/test/tap/circular-dep'>;
}
declare module 'npm/test/tap/config-basic.js' {
  declare module.exports: $Exports<'npm/test/tap/config-basic'>;
}
declare module 'npm/test/tap/config-builtin.js' {
  declare module.exports: $Exports<'npm/test/tap/config-builtin'>;
}
declare module 'npm/test/tap/config-certfile.js' {
  declare module.exports: $Exports<'npm/test/tap/config-certfile'>;
}
declare module 'npm/test/tap/config-credentials.js' {
  declare module.exports: $Exports<'npm/test/tap/config-credentials'>;
}
declare module 'npm/test/tap/config-edit.js' {
  declare module.exports: $Exports<'npm/test/tap/config-edit'>;
}
declare module 'npm/test/tap/config-malformed.js' {
  declare module.exports: $Exports<'npm/test/tap/config-malformed'>;
}
declare module 'npm/test/tap/config-meta.js' {
  declare module.exports: $Exports<'npm/test/tap/config-meta'>;
}
declare module 'npm/test/tap/config-new-cafile.js' {
  declare module.exports: $Exports<'npm/test/tap/config-new-cafile'>;
}
declare module 'npm/test/tap/config-private.js' {
  declare module.exports: $Exports<'npm/test/tap/config-private'>;
}
declare module 'npm/test/tap/config-project.js' {
  declare module.exports: $Exports<'npm/test/tap/config-project'>;
}
declare module 'npm/test/tap/config-save.js' {
  declare module.exports: $Exports<'npm/test/tap/config-save'>;
}
declare module 'npm/test/tap/correct-mkdir.js' {
  declare module.exports: $Exports<'npm/test/tap/correct-mkdir'>;
}
declare module 'npm/test/tap/dedupe-scoped.js' {
  declare module.exports: $Exports<'npm/test/tap/dedupe-scoped'>;
}
declare module 'npm/test/tap/dedupe.js' {
  declare module.exports: $Exports<'npm/test/tap/dedupe'>;
}
declare module 'npm/test/tap/deprecate.js' {
  declare module.exports: $Exports<'npm/test/tap/deprecate'>;
}
declare module 'npm/test/tap/dist-tag.js' {
  declare module.exports: $Exports<'npm/test/tap/dist-tag'>;
}
declare module 'npm/test/tap/false-name.js' {
  declare module.exports: $Exports<'npm/test/tap/false-name'>;
}
declare module 'npm/test/tap/files-and-ignores.js' {
  declare module.exports: $Exports<'npm/test/tap/files-and-ignores'>;
}
declare module 'npm/test/tap/gently-rm-overeager.js' {
  declare module.exports: $Exports<'npm/test/tap/gently-rm-overeager'>;
}
declare module 'npm/test/tap/gently-rm-symlink.js' {
  declare module.exports: $Exports<'npm/test/tap/gently-rm-symlink'>;
}
declare module 'npm/test/tap/get.js' {
  declare module.exports: $Exports<'npm/test/tap/get'>;
}
declare module 'npm/test/tap/gist-short-shortcut-package.js' {
  declare module.exports: $Exports<'npm/test/tap/gist-short-shortcut-package'>;
}
declare module 'npm/test/tap/gist-short-shortcut.js' {
  declare module.exports: $Exports<'npm/test/tap/gist-short-shortcut'>;
}
declare module 'npm/test/tap/gist-shortcut-package.js' {
  declare module.exports: $Exports<'npm/test/tap/gist-shortcut-package'>;
}
declare module 'npm/test/tap/gist-shortcut.js' {
  declare module.exports: $Exports<'npm/test/tap/gist-shortcut'>;
}
declare module 'npm/test/tap/git-cache-locking.js' {
  declare module.exports: $Exports<'npm/test/tap/git-cache-locking'>;
}
declare module 'npm/test/tap/git-cache-no-hooks.js' {
  declare module.exports: $Exports<'npm/test/tap/git-cache-no-hooks'>;
}
declare module 'npm/test/tap/git-dependency-install-link.js' {
  declare module.exports: $Exports<'npm/test/tap/git-dependency-install-link'>;
}
declare module 'npm/test/tap/git-npmignore.js' {
  declare module.exports: $Exports<'npm/test/tap/git-npmignore'>;
}
declare module 'npm/test/tap/git-races.js' {
  declare module.exports: $Exports<'npm/test/tap/git-races'>;
}
declare module 'npm/test/tap/github-shortcut-package.js' {
  declare module.exports: $Exports<'npm/test/tap/github-shortcut-package'>;
}
declare module 'npm/test/tap/github-shortcut.js' {
  declare module.exports: $Exports<'npm/test/tap/github-shortcut'>;
}
declare module 'npm/test/tap/gitlab-shortcut-package.js' {
  declare module.exports: $Exports<'npm/test/tap/gitlab-shortcut-package'>;
}
declare module 'npm/test/tap/gitlab-shortcut.js' {
  declare module.exports: $Exports<'npm/test/tap/gitlab-shortcut'>;
}
declare module 'npm/test/tap/global-prefix-set-in-userconfig.js' {
  declare module.exports: $Exports<'npm/test/tap/global-prefix-set-in-userconfig'>;
}
declare module 'npm/test/tap/graceful-restart.js' {
  declare module.exports: $Exports<'npm/test/tap/graceful-restart'>;
}
declare module 'npm/test/tap/ignore-install-link.js' {
  declare module.exports: $Exports<'npm/test/tap/ignore-install-link'>;
}
declare module 'npm/test/tap/ignore-scripts.js' {
  declare module.exports: $Exports<'npm/test/tap/ignore-scripts'>;
}
declare module 'npm/test/tap/ignore-shrinkwrap.js' {
  declare module.exports: $Exports<'npm/test/tap/ignore-shrinkwrap'>;
}
declare module 'npm/test/tap/init-interrupt.js' {
  declare module.exports: $Exports<'npm/test/tap/init-interrupt'>;
}
declare module 'npm/test/tap/install-at-locally.js' {
  declare module.exports: $Exports<'npm/test/tap/install-at-locally'>;
}
declare module 'npm/test/tap/install-bad-man.js' {
  declare module.exports: $Exports<'npm/test/tap/install-bad-man'>;
}
declare module 'npm/test/tap/install-cli-production.js' {
  declare module.exports: $Exports<'npm/test/tap/install-cli-production'>;
}
declare module 'npm/test/tap/install-cli-unicode.js' {
  declare module.exports: $Exports<'npm/test/tap/install-cli-unicode'>;
}
declare module 'npm/test/tap/install-from-local.js' {
  declare module.exports: $Exports<'npm/test/tap/install-from-local'>;
}
declare module 'npm/test/tap/install-link-scripts.js' {
  declare module.exports: $Exports<'npm/test/tap/install-link-scripts'>;
}
declare module 'npm/test/tap/install-man.js' {
  declare module.exports: $Exports<'npm/test/tap/install-man'>;
}
declare module 'npm/test/tap/install-noargs-dev.js' {
  declare module.exports: $Exports<'npm/test/tap/install-noargs-dev'>;
}
declare module 'npm/test/tap/install-preferglobal-warnings.js' {
  declare module.exports: $Exports<'npm/test/tap/install-preferglobal-warnings'>;
}
declare module 'npm/test/tap/install-save-exact.js' {
  declare module.exports: $Exports<'npm/test/tap/install-save-exact'>;
}
declare module 'npm/test/tap/install-save-local.js' {
  declare module.exports: $Exports<'npm/test/tap/install-save-local'>;
}
declare module 'npm/test/tap/install-save-prefix.js' {
  declare module.exports: $Exports<'npm/test/tap/install-save-prefix'>;
}
declare module 'npm/test/tap/install-scoped-already-installed.js' {
  declare module.exports: $Exports<'npm/test/tap/install-scoped-already-installed'>;
}
declare module 'npm/test/tap/install-scoped-link.js' {
  declare module.exports: $Exports<'npm/test/tap/install-scoped-link'>;
}
declare module 'npm/test/tap/install-scoped-with-peer-dependency.js' {
  declare module.exports: $Exports<'npm/test/tap/install-scoped-with-peer-dependency'>;
}
declare module 'npm/test/tap/install-shrinkwrap-equals-ls.js' {
  declare module.exports: $Exports<'npm/test/tap/install-shrinkwrap-equals-ls'>;
}
declare module 'npm/test/tap/install-with-dev-dep-duplicate.js' {
  declare module.exports: $Exports<'npm/test/tap/install-with-dev-dep-duplicate'>;
}
declare module 'npm/test/tap/invalid-cmd-exit-code.js' {
  declare module.exports: $Exports<'npm/test/tap/invalid-cmd-exit-code'>;
}
declare module 'npm/test/tap/legacy-array-bin.js' {
  declare module.exports: $Exports<'npm/test/tap/legacy-array-bin'>;
}
declare module 'npm/test/tap/legacy-bundled-git.js' {
  declare module.exports: $Exports<'npm/test/tap/legacy-bundled-git'>;
}
declare module 'npm/test/tap/legacy-dir-bin.js' {
  declare module.exports: $Exports<'npm/test/tap/legacy-dir-bin'>;
}
declare module 'npm/test/tap/legacy-ignore-nested-nm.js' {
  declare module.exports: $Exports<'npm/test/tap/legacy-ignore-nested-nm'>;
}
declare module 'npm/test/tap/legacy-missing-bindir.js' {
  declare module.exports: $Exports<'npm/test/tap/legacy-missing-bindir'>;
}
declare module 'npm/test/tap/legacy-no-auth-leak.js' {
  declare module.exports: $Exports<'npm/test/tap/legacy-no-auth-leak'>;
}
declare module 'npm/test/tap/legacy-npm-self-install.js' {
  declare module.exports: $Exports<'npm/test/tap/legacy-npm-self-install'>;
}
declare module 'npm/test/tap/legacy-optional-deps.js' {
  declare module.exports: $Exports<'npm/test/tap/legacy-optional-deps'>;
}
declare module 'npm/test/tap/legacy-platform-all.js' {
  declare module.exports: $Exports<'npm/test/tap/legacy-platform-all'>;
}
declare module 'npm/test/tap/legacy-platform.js' {
  declare module.exports: $Exports<'npm/test/tap/legacy-platform'>;
}
declare module 'npm/test/tap/legacy-private.js' {
  declare module.exports: $Exports<'npm/test/tap/legacy-private'>;
}
declare module 'npm/test/tap/legacy-shrinkwrap.js' {
  declare module.exports: $Exports<'npm/test/tap/legacy-shrinkwrap'>;
}
declare module 'npm/test/tap/legacy-test-package.js' {
  declare module.exports: $Exports<'npm/test/tap/legacy-test-package'>;
}
declare module 'npm/test/tap/legacy-url-dep.js' {
  declare module.exports: $Exports<'npm/test/tap/legacy-url-dep'>;
}
declare module 'npm/test/tap/lifecycle-path.js' {
  declare module.exports: $Exports<'npm/test/tap/lifecycle-path'>;
}
declare module 'npm/test/tap/lifecycle-signal.js' {
  declare module.exports: $Exports<'npm/test/tap/lifecycle-signal'>;
}
declare module 'npm/test/tap/lifecycle.js' {
  declare module.exports: $Exports<'npm/test/tap/lifecycle'>;
}
declare module 'npm/test/tap/link.js' {
  declare module.exports: $Exports<'npm/test/tap/link'>;
}
declare module 'npm/test/tap/locker.js' {
  declare module.exports: $Exports<'npm/test/tap/locker'>;
}
declare module 'npm/test/tap/logout.js' {
  declare module.exports: $Exports<'npm/test/tap/logout'>;
}
declare module 'npm/test/tap/ls-depth-cli.js' {
  declare module.exports: $Exports<'npm/test/tap/ls-depth-cli'>;
}
declare module 'npm/test/tap/ls-depth-unmet.js' {
  declare module.exports: $Exports<'npm/test/tap/ls-depth-unmet'>;
}
declare module 'npm/test/tap/ls-env.js' {
  declare module.exports: $Exports<'npm/test/tap/ls-env'>;
}
declare module 'npm/test/tap/ls-l-depth-0.js' {
  declare module.exports: $Exports<'npm/test/tap/ls-l-depth-0'>;
}
declare module 'npm/test/tap/ls-no-results.js' {
  declare module.exports: $Exports<'npm/test/tap/ls-no-results'>;
}
declare module 'npm/test/tap/map-to-registry.js' {
  declare module.exports: $Exports<'npm/test/tap/map-to-registry'>;
}
declare module 'npm/test/tap/nerf-dart.js' {
  declare module.exports: $Exports<'npm/test/tap/nerf-dart'>;
}
declare module 'npm/test/tap/nested-extraneous.js' {
  declare module.exports: $Exports<'npm/test/tap/nested-extraneous'>;
}
declare module 'npm/test/tap/noargs-install-config-save.js' {
  declare module.exports: $Exports<'npm/test/tap/noargs-install-config-save'>;
}
declare module 'npm/test/tap/npm-api-not-loaded-error.js' {
  declare module.exports: $Exports<'npm/test/tap/npm-api-not-loaded-error'>;
}
declare module 'npm/test/tap/onload.js' {
  declare module.exports: $Exports<'npm/test/tap/onload'>;
}
declare module 'npm/test/tap/optional-metadep-rollback-collision.js' {
  declare module.exports: $Exports<'npm/test/tap/optional-metadep-rollback-collision'>;
}
declare module 'npm/test/tap/outdated-color.js' {
  declare module.exports: $Exports<'npm/test/tap/outdated-color'>;
}
declare module 'npm/test/tap/outdated-depth-deep.js' {
  declare module.exports: $Exports<'npm/test/tap/outdated-depth-deep'>;
}
declare module 'npm/test/tap/outdated-depth-integer.js' {
  declare module.exports: $Exports<'npm/test/tap/outdated-depth-integer'>;
}
declare module 'npm/test/tap/outdated-depth.js' {
  declare module.exports: $Exports<'npm/test/tap/outdated-depth'>;
}
declare module 'npm/test/tap/outdated-git.js' {
  declare module.exports: $Exports<'npm/test/tap/outdated-git'>;
}
declare module 'npm/test/tap/outdated-include-devdependencies.js' {
  declare module.exports: $Exports<'npm/test/tap/outdated-include-devdependencies'>;
}
declare module 'npm/test/tap/outdated-json.js' {
  declare module.exports: $Exports<'npm/test/tap/outdated-json'>;
}
declare module 'npm/test/tap/outdated-local.js' {
  declare module.exports: $Exports<'npm/test/tap/outdated-local'>;
}
declare module 'npm/test/tap/outdated-long.js' {
  declare module.exports: $Exports<'npm/test/tap/outdated-long'>;
}
declare module 'npm/test/tap/outdated-new-versions.js' {
  declare module.exports: $Exports<'npm/test/tap/outdated-new-versions'>;
}
declare module 'npm/test/tap/outdated-notarget.js' {
  declare module.exports: $Exports<'npm/test/tap/outdated-notarget'>;
}
declare module 'npm/test/tap/outdated-private.js' {
  declare module.exports: $Exports<'npm/test/tap/outdated-private'>;
}
declare module 'npm/test/tap/outdated-symlink.js' {
  declare module.exports: $Exports<'npm/test/tap/outdated-symlink'>;
}
declare module 'npm/test/tap/outdated.js' {
  declare module.exports: $Exports<'npm/test/tap/outdated'>;
}
declare module 'npm/test/tap/owner.js' {
  declare module.exports: $Exports<'npm/test/tap/owner'>;
}
declare module 'npm/test/tap/pack-scoped.js' {
  declare module.exports: $Exports<'npm/test/tap/pack-scoped'>;
}
declare module 'npm/test/tap/peer-deps-invalid.js' {
  declare module.exports: $Exports<'npm/test/tap/peer-deps-invalid'>;
}
declare module 'npm/test/tap/peer-deps-toplevel.js' {
  declare module.exports: $Exports<'npm/test/tap/peer-deps-toplevel'>;
}
declare module 'npm/test/tap/peer-deps-without-package-json.js' {
  declare module.exports: $Exports<'npm/test/tap/peer-deps-without-package-json'>;
}
declare module 'npm/test/tap/peer-deps.js' {
  declare module.exports: $Exports<'npm/test/tap/peer-deps'>;
}
declare module 'npm/test/tap/ping.js' {
  declare module.exports: $Exports<'npm/test/tap/ping'>;
}
declare module 'npm/test/tap/prepublish.js' {
  declare module.exports: $Exports<'npm/test/tap/prepublish'>;
}
declare module 'npm/test/tap/prune.js' {
  declare module.exports: $Exports<'npm/test/tap/prune'>;
}
declare module 'npm/test/tap/publish-access-scoped.js' {
  declare module.exports: $Exports<'npm/test/tap/publish-access-scoped'>;
}
declare module 'npm/test/tap/publish-access-unscoped-restricted-fails.js' {
  declare module.exports: $Exports<'npm/test/tap/publish-access-unscoped-restricted-fails'>;
}
declare module 'npm/test/tap/publish-access-unscoped.js' {
  declare module.exports: $Exports<'npm/test/tap/publish-access-unscoped'>;
}
declare module 'npm/test/tap/publish-config.js' {
  declare module.exports: $Exports<'npm/test/tap/publish-config'>;
}
declare module 'npm/test/tap/publish-invalid-semver-tag.js' {
  declare module.exports: $Exports<'npm/test/tap/publish-invalid-semver-tag'>;
}
declare module 'npm/test/tap/publish-scoped.js' {
  declare module.exports: $Exports<'npm/test/tap/publish-scoped'>;
}
declare module 'npm/test/tap/pwd-prefix.js' {
  declare module.exports: $Exports<'npm/test/tap/pwd-prefix'>;
}
declare module 'npm/test/tap/referer.js' {
  declare module.exports: $Exports<'npm/test/tap/referer'>;
}
declare module 'npm/test/tap/registry.js' {
  declare module.exports: $Exports<'npm/test/tap/registry'>;
}
declare module 'npm/test/tap/repo.js' {
  declare module.exports: $Exports<'npm/test/tap/repo'>;
}
declare module 'npm/test/tap/run-script-filter-private.js' {
  declare module.exports: $Exports<'npm/test/tap/run-script-filter-private'>;
}
declare module 'npm/test/tap/run-script.js' {
  declare module.exports: $Exports<'npm/test/tap/run-script'>;
}
declare module 'npm/test/tap/scripts-whitespace-windows.js' {
  declare module.exports: $Exports<'npm/test/tap/scripts-whitespace-windows'>;
}
declare module 'npm/test/tap/search.js' {
  declare module.exports: $Exports<'npm/test/tap/search'>;
}
declare module 'npm/test/tap/semver-doc.js' {
  declare module.exports: $Exports<'npm/test/tap/semver-doc'>;
}
declare module 'npm/test/tap/semver-tag.js' {
  declare module.exports: $Exports<'npm/test/tap/semver-tag'>;
}
declare module 'npm/test/tap/shrinkwrap-dev-dependency.js' {
  declare module.exports: $Exports<'npm/test/tap/shrinkwrap-dev-dependency'>;
}
declare module 'npm/test/tap/shrinkwrap-empty-deps.js' {
  declare module.exports: $Exports<'npm/test/tap/shrinkwrap-empty-deps'>;
}
declare module 'npm/test/tap/shrinkwrap-local-dependency.js' {
  declare module.exports: $Exports<'npm/test/tap/shrinkwrap-local-dependency'>;
}
declare module 'npm/test/tap/shrinkwrap-prod-dependency.js' {
  declare module.exports: $Exports<'npm/test/tap/shrinkwrap-prod-dependency'>;
}
declare module 'npm/test/tap/shrinkwrap-scoped-auth.js' {
  declare module.exports: $Exports<'npm/test/tap/shrinkwrap-scoped-auth'>;
}
declare module 'npm/test/tap/shrinkwrap-shared-dev-dependency.js' {
  declare module.exports: $Exports<'npm/test/tap/shrinkwrap-shared-dev-dependency'>;
}
declare module 'npm/test/tap/sorted-package-json.js' {
  declare module.exports: $Exports<'npm/test/tap/sorted-package-json'>;
}
declare module 'npm/test/tap/spawn-enoent-help.js' {
  declare module.exports: $Exports<'npm/test/tap/spawn-enoent-help'>;
}
declare module 'npm/test/tap/spawn-enoent.js' {
  declare module.exports: $Exports<'npm/test/tap/spawn-enoent'>;
}
declare module 'npm/test/tap/splat-with-only-prerelease-to-latest.js' {
  declare module.exports: $Exports<'npm/test/tap/splat-with-only-prerelease-to-latest'>;
}
declare module 'npm/test/tap/startstop.js' {
  declare module.exports: $Exports<'npm/test/tap/startstop'>;
}
declare module 'npm/test/tap/tag-version-prefix.js' {
  declare module.exports: $Exports<'npm/test/tap/tag-version-prefix'>;
}
declare module 'npm/test/tap/team.js' {
  declare module.exports: $Exports<'npm/test/tap/team'>;
}
declare module 'npm/test/tap/test-run-ls.js' {
  declare module.exports: $Exports<'npm/test/tap/test-run-ls'>;
}
declare module 'npm/test/tap/umask-lifecycle.js' {
  declare module.exports: $Exports<'npm/test/tap/umask-lifecycle'>;
}
declare module 'npm/test/tap/uninstall-package.js' {
  declare module.exports: $Exports<'npm/test/tap/uninstall-package'>;
}
declare module 'npm/test/tap/unpack-foreign-tarball.js' {
  declare module.exports: $Exports<'npm/test/tap/unpack-foreign-tarball'>;
}
declare module 'npm/test/tap/unpublish-config.js' {
  declare module.exports: $Exports<'npm/test/tap/unpublish-config'>;
}
declare module 'npm/test/tap/update-examples.js' {
  declare module.exports: $Exports<'npm/test/tap/update-examples'>;
}
declare module 'npm/test/tap/update-index.js' {
  declare module.exports: $Exports<'npm/test/tap/update-index'>;
}
declare module 'npm/test/tap/update-save.js' {
  declare module.exports: $Exports<'npm/test/tap/update-save'>;
}
declare module 'npm/test/tap/url-dependencies.js' {
  declare module.exports: $Exports<'npm/test/tap/url-dependencies'>;
}
declare module 'npm/test/tap/version-git-not-clean.js' {
  declare module.exports: $Exports<'npm/test/tap/version-git-not-clean'>;
}
declare module 'npm/test/tap/version-lifecycle.js' {
  declare module.exports: $Exports<'npm/test/tap/version-lifecycle'>;
}
declare module 'npm/test/tap/version-message-config.js' {
  declare module.exports: $Exports<'npm/test/tap/version-message-config'>;
}
declare module 'npm/test/tap/version-no-git.js' {
  declare module.exports: $Exports<'npm/test/tap/version-no-git'>;
}
declare module 'npm/test/tap/version-no-package.js' {
  declare module.exports: $Exports<'npm/test/tap/version-no-package'>;
}
declare module 'npm/test/tap/version-no-tags.js' {
  declare module.exports: $Exports<'npm/test/tap/version-no-tags'>;
}
declare module 'npm/test/tap/version-sub-directory.js' {
  declare module.exports: $Exports<'npm/test/tap/version-sub-directory'>;
}
declare module 'npm/test/tap/version-update-shrinkwrap.js' {
  declare module.exports: $Exports<'npm/test/tap/version-update-shrinkwrap'>;
}
declare module 'npm/test/tap/view.js' {
  declare module.exports: $Exports<'npm/test/tap/view'>;
}
declare module 'npm/test/tap/whoami.js' {
  declare module.exports: $Exports<'npm/test/tap/whoami'>;
}
declare module 'npm/test/tap/zz-cleanup.js' {
  declare module.exports: $Exports<'npm/test/tap/zz-cleanup'>;
}
