// flow-typed signature: 89e43ed6416c8021fc6a40e6c8a033bb
// flow-typed version: <<STUB>>/npmignore_v^0.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npmignore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npmignore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npmignore/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npmignore/cli.js' {
  declare module.exports: $Exports<'npmignore/cli'>;
}
declare module 'npmignore/index' {
  declare module.exports: $Exports<'npmignore'>;
}
declare module 'npmignore/index.js' {
  declare module.exports: $Exports<'npmignore'>;
}
