// flow-typed signature: 52a7de4472405771ddb760d72f98f24d
// flow-typed version: <<STUB>>/q_v^1.5.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'q'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'q' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'q/q' {
  declare module.exports: any;
}

declare module 'q/queue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'q/q.js' {
  declare module.exports: $Exports<'q/q'>;
}
declare module 'q/queue.js' {
  declare module.exports: $Exports<'q/queue'>;
}
