// flow-typed signature: af1c5a6147b36da9f41140efc94d089a
// flow-typed version: <<STUB>>/react-fastclick_v^3.0.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-fastclick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-fastclick' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-fastclick/src/index' {
  declare module.exports: any;
}

declare module 'react-fastclick/tests/helpers/render-into-app' {
  declare module.exports: any;
}

declare module 'react-fastclick/tests/helpers/test-setup' {
  declare module.exports: any;
}

declare module 'react-fastclick/tests/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-fastclick/src/index.js' {
  declare module.exports: $Exports<'react-fastclick/src/index'>;
}
declare module 'react-fastclick/tests/helpers/render-into-app.js' {
  declare module.exports: $Exports<'react-fastclick/tests/helpers/render-into-app'>;
}
declare module 'react-fastclick/tests/helpers/test-setup.js' {
  declare module.exports: $Exports<'react-fastclick/tests/helpers/test-setup'>;
}
declare module 'react-fastclick/tests/index.test.js' {
  declare module.exports: $Exports<'react-fastclick/tests/index.test'>;
}
