// flow-typed signature: 36111dd4f2b282baa566f14aec59d7e9
// flow-typed version: <<STUB>>/react-images_v^0.5.17/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-images'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-images' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-images/dist/react-images.es' {
  declare module.exports: any;
}

declare module 'react-images/dist/react-images' {
  declare module.exports: any;
}

declare module 'react-images/dist/react-images.min' {
  declare module.exports: any;
}

declare module 'react-images/examples/dist/app' {
  declare module.exports: any;
}

declare module 'react-images/examples/dist/common' {
  declare module.exports: any;
}

declare module 'react-images/examples/src/app' {
  declare module.exports: any;
}

declare module 'react-images/examples/src/components/DownloadButton/icon' {
  declare module.exports: any;
}

declare module 'react-images/examples/src/components/DownloadButton/index' {
  declare module.exports: any;
}

declare module 'react-images/examples/src/components/Gallery' {
  declare module.exports: any;
}

declare module 'react-images/examples/src/components/Spinner' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Arrow' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Container' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Footer' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Header' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Icon' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/PaginatedThumbnails' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/PassContext' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Portal' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Spinner' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Thumbnail' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Thumbnails' {
  declare module.exports: any;
}

declare module 'react-images/lib/icons/arrowLeft' {
  declare module.exports: any;
}

declare module 'react-images/lib/icons/arrowRight' {
  declare module.exports: any;
}

declare module 'react-images/lib/icons/close' {
  declare module.exports: any;
}

declare module 'react-images/lib/Lightbox' {
  declare module.exports: any;
}

declare module 'react-images/lib/theme' {
  declare module.exports: any;
}

declare module 'react-images/lib/utils/bindFunctions' {
  declare module.exports: any;
}

declare module 'react-images/lib/utils/canUseDom' {
  declare module.exports: any;
}

declare module 'react-images/lib/utils/deepMerge' {
  declare module.exports: any;
}

declare module 'react-images/package-scripts' {
  declare module.exports: any;
}

declare module 'react-images/rollup.config' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Arrow' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Container' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Footer' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Header' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Icon' {
  declare module.exports: any;
}

declare module 'react-images/src/components/PaginatedThumbnails' {
  declare module.exports: any;
}

declare module 'react-images/src/components/PassContext' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Portal' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Spinner' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Thumbnail' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Thumbnails' {
  declare module.exports: any;
}

declare module 'react-images/src/icons/arrowLeft' {
  declare module.exports: any;
}

declare module 'react-images/src/icons/arrowRight' {
  declare module.exports: any;
}

declare module 'react-images/src/icons/close' {
  declare module.exports: any;
}

declare module 'react-images/src/Lightbox' {
  declare module.exports: any;
}

declare module 'react-images/src/theme' {
  declare module.exports: any;
}

declare module 'react-images/src/utils/bindFunctions' {
  declare module.exports: any;
}

declare module 'react-images/src/utils/canUseDom' {
  declare module.exports: any;
}

declare module 'react-images/src/utils/deepMerge' {
  declare module.exports: any;
}

declare module 'react-images/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-images/dist/react-images.es.js' {
  declare module.exports: $Exports<'react-images/dist/react-images.es'>;
}
declare module 'react-images/dist/react-images.js' {
  declare module.exports: $Exports<'react-images/dist/react-images'>;
}
declare module 'react-images/dist/react-images.min.js' {
  declare module.exports: $Exports<'react-images/dist/react-images.min'>;
}
declare module 'react-images/examples/dist/app.js' {
  declare module.exports: $Exports<'react-images/examples/dist/app'>;
}
declare module 'react-images/examples/dist/common.js' {
  declare module.exports: $Exports<'react-images/examples/dist/common'>;
}
declare module 'react-images/examples/src/app.js' {
  declare module.exports: $Exports<'react-images/examples/src/app'>;
}
declare module 'react-images/examples/src/components/DownloadButton/icon.js' {
  declare module.exports: $Exports<'react-images/examples/src/components/DownloadButton/icon'>;
}
declare module 'react-images/examples/src/components/DownloadButton/index.js' {
  declare module.exports: $Exports<'react-images/examples/src/components/DownloadButton/index'>;
}
declare module 'react-images/examples/src/components/Gallery.js' {
  declare module.exports: $Exports<'react-images/examples/src/components/Gallery'>;
}
declare module 'react-images/examples/src/components/Spinner.js' {
  declare module.exports: $Exports<'react-images/examples/src/components/Spinner'>;
}
declare module 'react-images/lib/components/Arrow.js' {
  declare module.exports: $Exports<'react-images/lib/components/Arrow'>;
}
declare module 'react-images/lib/components/Container.js' {
  declare module.exports: $Exports<'react-images/lib/components/Container'>;
}
declare module 'react-images/lib/components/Footer.js' {
  declare module.exports: $Exports<'react-images/lib/components/Footer'>;
}
declare module 'react-images/lib/components/Header.js' {
  declare module.exports: $Exports<'react-images/lib/components/Header'>;
}
declare module 'react-images/lib/components/Icon.js' {
  declare module.exports: $Exports<'react-images/lib/components/Icon'>;
}
declare module 'react-images/lib/components/PaginatedThumbnails.js' {
  declare module.exports: $Exports<'react-images/lib/components/PaginatedThumbnails'>;
}
declare module 'react-images/lib/components/PassContext.js' {
  declare module.exports: $Exports<'react-images/lib/components/PassContext'>;
}
declare module 'react-images/lib/components/Portal.js' {
  declare module.exports: $Exports<'react-images/lib/components/Portal'>;
}
declare module 'react-images/lib/components/Spinner.js' {
  declare module.exports: $Exports<'react-images/lib/components/Spinner'>;
}
declare module 'react-images/lib/components/Thumbnail.js' {
  declare module.exports: $Exports<'react-images/lib/components/Thumbnail'>;
}
declare module 'react-images/lib/components/Thumbnails.js' {
  declare module.exports: $Exports<'react-images/lib/components/Thumbnails'>;
}
declare module 'react-images/lib/icons/arrowLeft.js' {
  declare module.exports: $Exports<'react-images/lib/icons/arrowLeft'>;
}
declare module 'react-images/lib/icons/arrowRight.js' {
  declare module.exports: $Exports<'react-images/lib/icons/arrowRight'>;
}
declare module 'react-images/lib/icons/close.js' {
  declare module.exports: $Exports<'react-images/lib/icons/close'>;
}
declare module 'react-images/lib/Lightbox.js' {
  declare module.exports: $Exports<'react-images/lib/Lightbox'>;
}
declare module 'react-images/lib/theme.js' {
  declare module.exports: $Exports<'react-images/lib/theme'>;
}
declare module 'react-images/lib/utils/bindFunctions.js' {
  declare module.exports: $Exports<'react-images/lib/utils/bindFunctions'>;
}
declare module 'react-images/lib/utils/canUseDom.js' {
  declare module.exports: $Exports<'react-images/lib/utils/canUseDom'>;
}
declare module 'react-images/lib/utils/deepMerge.js' {
  declare module.exports: $Exports<'react-images/lib/utils/deepMerge'>;
}
declare module 'react-images/package-scripts.js' {
  declare module.exports: $Exports<'react-images/package-scripts'>;
}
declare module 'react-images/rollup.config.js' {
  declare module.exports: $Exports<'react-images/rollup.config'>;
}
declare module 'react-images/src/components/Arrow.js' {
  declare module.exports: $Exports<'react-images/src/components/Arrow'>;
}
declare module 'react-images/src/components/Container.js' {
  declare module.exports: $Exports<'react-images/src/components/Container'>;
}
declare module 'react-images/src/components/Footer.js' {
  declare module.exports: $Exports<'react-images/src/components/Footer'>;
}
declare module 'react-images/src/components/Header.js' {
  declare module.exports: $Exports<'react-images/src/components/Header'>;
}
declare module 'react-images/src/components/Icon.js' {
  declare module.exports: $Exports<'react-images/src/components/Icon'>;
}
declare module 'react-images/src/components/PaginatedThumbnails.js' {
  declare module.exports: $Exports<'react-images/src/components/PaginatedThumbnails'>;
}
declare module 'react-images/src/components/PassContext.js' {
  declare module.exports: $Exports<'react-images/src/components/PassContext'>;
}
declare module 'react-images/src/components/Portal.js' {
  declare module.exports: $Exports<'react-images/src/components/Portal'>;
}
declare module 'react-images/src/components/Spinner.js' {
  declare module.exports: $Exports<'react-images/src/components/Spinner'>;
}
declare module 'react-images/src/components/Thumbnail.js' {
  declare module.exports: $Exports<'react-images/src/components/Thumbnail'>;
}
declare module 'react-images/src/components/Thumbnails.js' {
  declare module.exports: $Exports<'react-images/src/components/Thumbnails'>;
}
declare module 'react-images/src/icons/arrowLeft.js' {
  declare module.exports: $Exports<'react-images/src/icons/arrowLeft'>;
}
declare module 'react-images/src/icons/arrowRight.js' {
  declare module.exports: $Exports<'react-images/src/icons/arrowRight'>;
}
declare module 'react-images/src/icons/close.js' {
  declare module.exports: $Exports<'react-images/src/icons/close'>;
}
declare module 'react-images/src/Lightbox.js' {
  declare module.exports: $Exports<'react-images/src/Lightbox'>;
}
declare module 'react-images/src/theme.js' {
  declare module.exports: $Exports<'react-images/src/theme'>;
}
declare module 'react-images/src/utils/bindFunctions.js' {
  declare module.exports: $Exports<'react-images/src/utils/bindFunctions'>;
}
declare module 'react-images/src/utils/canUseDom.js' {
  declare module.exports: $Exports<'react-images/src/utils/canUseDom'>;
}
declare module 'react-images/src/utils/deepMerge.js' {
  declare module.exports: $Exports<'react-images/src/utils/deepMerge'>;
}
declare module 'react-images/webpack.config.js' {
  declare module.exports: $Exports<'react-images/webpack.config'>;
}
