// flow-typed signature: 1f6a593b3ca1a021b205a4fb953b7927
// flow-typed version: <<STUB>>/react-photo-gallery_v^6.0.25/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-photo-gallery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-photo-gallery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-photo-gallery/__test__/Gallery.test' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/__test__/jestsetup' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/__test__/Photo.test' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/__test__/rafShim' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/__test__/test-photo-data' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/__test__/utils.test' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/dist/react-photo-gallery.es' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/dist/react-photo-gallery' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/dist/react-photo-gallery.min' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/examples/src/app' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/examples/src/ExampleBasic' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/examples/src/ExampleCustomComponentSelection' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/examples/src/ExampleDynamicLoading' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/examples/src/ExampleWithLightbox' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/examples/src/icons/checkmark' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/examples/src/SelectedImage' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/jest.config' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/lib/Gallery' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/lib/Photo' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/lib/utils' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/package-scripts' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/rollup.config' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/src/Gallery' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/src/Photo' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/src/utils' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-photo-gallery/__test__/Gallery.test.js' {
  declare module.exports: $Exports<'react-photo-gallery/__test__/Gallery.test'>;
}
declare module 'react-photo-gallery/__test__/jestsetup.js' {
  declare module.exports: $Exports<'react-photo-gallery/__test__/jestsetup'>;
}
declare module 'react-photo-gallery/__test__/Photo.test.js' {
  declare module.exports: $Exports<'react-photo-gallery/__test__/Photo.test'>;
}
declare module 'react-photo-gallery/__test__/rafShim.js' {
  declare module.exports: $Exports<'react-photo-gallery/__test__/rafShim'>;
}
declare module 'react-photo-gallery/__test__/test-photo-data.js' {
  declare module.exports: $Exports<'react-photo-gallery/__test__/test-photo-data'>;
}
declare module 'react-photo-gallery/__test__/utils.test.js' {
  declare module.exports: $Exports<'react-photo-gallery/__test__/utils.test'>;
}
declare module 'react-photo-gallery/dist/react-photo-gallery.es.js' {
  declare module.exports: $Exports<'react-photo-gallery/dist/react-photo-gallery.es'>;
}
declare module 'react-photo-gallery/dist/react-photo-gallery.js' {
  declare module.exports: $Exports<'react-photo-gallery/dist/react-photo-gallery'>;
}
declare module 'react-photo-gallery/dist/react-photo-gallery.min.js' {
  declare module.exports: $Exports<'react-photo-gallery/dist/react-photo-gallery.min'>;
}
declare module 'react-photo-gallery/examples/src/app.js' {
  declare module.exports: $Exports<'react-photo-gallery/examples/src/app'>;
}
declare module 'react-photo-gallery/examples/src/ExampleBasic.js' {
  declare module.exports: $Exports<'react-photo-gallery/examples/src/ExampleBasic'>;
}
declare module 'react-photo-gallery/examples/src/ExampleCustomComponentSelection.js' {
  declare module.exports: $Exports<'react-photo-gallery/examples/src/ExampleCustomComponentSelection'>;
}
declare module 'react-photo-gallery/examples/src/ExampleDynamicLoading.js' {
  declare module.exports: $Exports<'react-photo-gallery/examples/src/ExampleDynamicLoading'>;
}
declare module 'react-photo-gallery/examples/src/ExampleWithLightbox.js' {
  declare module.exports: $Exports<'react-photo-gallery/examples/src/ExampleWithLightbox'>;
}
declare module 'react-photo-gallery/examples/src/icons/checkmark.js' {
  declare module.exports: $Exports<'react-photo-gallery/examples/src/icons/checkmark'>;
}
declare module 'react-photo-gallery/examples/src/SelectedImage.js' {
  declare module.exports: $Exports<'react-photo-gallery/examples/src/SelectedImage'>;
}
declare module 'react-photo-gallery/jest.config.js' {
  declare module.exports: $Exports<'react-photo-gallery/jest.config'>;
}
declare module 'react-photo-gallery/lib/Gallery.js' {
  declare module.exports: $Exports<'react-photo-gallery/lib/Gallery'>;
}
declare module 'react-photo-gallery/lib/Photo.js' {
  declare module.exports: $Exports<'react-photo-gallery/lib/Photo'>;
}
declare module 'react-photo-gallery/lib/utils.js' {
  declare module.exports: $Exports<'react-photo-gallery/lib/utils'>;
}
declare module 'react-photo-gallery/package-scripts.js' {
  declare module.exports: $Exports<'react-photo-gallery/package-scripts'>;
}
declare module 'react-photo-gallery/rollup.config.js' {
  declare module.exports: $Exports<'react-photo-gallery/rollup.config'>;
}
declare module 'react-photo-gallery/src/Gallery.js' {
  declare module.exports: $Exports<'react-photo-gallery/src/Gallery'>;
}
declare module 'react-photo-gallery/src/Photo.js' {
  declare module.exports: $Exports<'react-photo-gallery/src/Photo'>;
}
declare module 'react-photo-gallery/src/utils.js' {
  declare module.exports: $Exports<'react-photo-gallery/src/utils'>;
}
declare module 'react-photo-gallery/webpack.config.js' {
  declare module.exports: $Exports<'react-photo-gallery/webpack.config'>;
}
