// flow-typed signature: e60c10d8cf353f3052c5cef86029dd4b
// flow-typed version: <<STUB>>/react-share_v^2.3.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-share'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-share' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-share/es/EmailIcon' {
  declare module.exports: any;
}

declare module 'react-share/es/EmailShareButton' {
  declare module.exports: any;
}

declare module 'react-share/es/FacebookIcon' {
  declare module.exports: any;
}

declare module 'react-share/es/FacebookShareButton' {
  declare module.exports: any;
}

declare module 'react-share/es/FacebookShareCount' {
  declare module.exports: any;
}

declare module 'react-share/es/GooglePlusIcon' {
  declare module.exports: any;
}

declare module 'react-share/es/GooglePlusShareButton' {
  declare module.exports: any;
}

declare module 'react-share/es/GooglePlusShareCount' {
  declare module.exports: any;
}

declare module 'react-share/es/index' {
  declare module.exports: any;
}

declare module 'react-share/es/LinkedinIcon' {
  declare module.exports: any;
}

declare module 'react-share/es/LinkedinShareButton' {
  declare module.exports: any;
}

declare module 'react-share/es/LinkedinShareCount' {
  declare module.exports: any;
}

declare module 'react-share/es/LivejournalIcon' {
  declare module.exports: any;
}

declare module 'react-share/es/LivejournalShareButton' {
  declare module.exports: any;
}

declare module 'react-share/es/MailruIcon' {
  declare module.exports: any;
}

declare module 'react-share/es/MailruShareButton' {
  declare module.exports: any;
}

declare module 'react-share/es/OKIcon' {
  declare module.exports: any;
}

declare module 'react-share/es/OKShareButton' {
  declare module.exports: any;
}

declare module 'react-share/es/OKShareCount' {
  declare module.exports: any;
}

declare module 'react-share/es/PinterestIcon' {
  declare module.exports: any;
}

declare module 'react-share/es/PinterestShareButton' {
  declare module.exports: any;
}

declare module 'react-share/es/PinterestShareCount' {
  declare module.exports: any;
}

declare module 'react-share/es/RedditIcon' {
  declare module.exports: any;
}

declare module 'react-share/es/RedditShareButton' {
  declare module.exports: any;
}

declare module 'react-share/es/RedditShareCount' {
  declare module.exports: any;
}

declare module 'react-share/es/TelegramIcon' {
  declare module.exports: any;
}

declare module 'react-share/es/TelegramShareButton' {
  declare module.exports: any;
}

declare module 'react-share/es/TumblrIcon' {
  declare module.exports: any;
}

declare module 'react-share/es/TumblrShareButton' {
  declare module.exports: any;
}

declare module 'react-share/es/TumblrShareCount' {
  declare module.exports: any;
}

declare module 'react-share/es/TwitterIcon' {
  declare module.exports: any;
}

declare module 'react-share/es/TwitterShareButton' {
  declare module.exports: any;
}

declare module 'react-share/es/utils/createShareButton' {
  declare module.exports: any;
}

declare module 'react-share/es/utils/iconFactory' {
  declare module.exports: any;
}

declare module 'react-share/es/utils/ieDetection' {
  declare module.exports: any;
}

declare module 'react-share/es/utils/objectToGetParams' {
  declare module.exports: any;
}

declare module 'react-share/es/utils/shareCountFactory' {
  declare module.exports: any;
}

declare module 'react-share/es/ViberIcon' {
  declare module.exports: any;
}

declare module 'react-share/es/ViberShareButton' {
  declare module.exports: any;
}

declare module 'react-share/es/VKIcon' {
  declare module.exports: any;
}

declare module 'react-share/es/VKShareButton' {
  declare module.exports: any;
}

declare module 'react-share/es/VKShareCount' {
  declare module.exports: any;
}

declare module 'react-share/es/WhatsappIcon' {
  declare module.exports: any;
}

declare module 'react-share/es/WhatsappShareButton' {
  declare module.exports: any;
}

declare module 'react-share/es/WorkplaceIcon' {
  declare module.exports: any;
}

declare module 'react-share/es/WorkplaceShareButton' {
  declare module.exports: any;
}

declare module 'react-share/lib/EmailIcon' {
  declare module.exports: any;
}

declare module 'react-share/lib/EmailShareButton' {
  declare module.exports: any;
}

declare module 'react-share/lib/FacebookIcon' {
  declare module.exports: any;
}

declare module 'react-share/lib/FacebookShareButton' {
  declare module.exports: any;
}

declare module 'react-share/lib/FacebookShareCount' {
  declare module.exports: any;
}

declare module 'react-share/lib/GooglePlusIcon' {
  declare module.exports: any;
}

declare module 'react-share/lib/GooglePlusShareButton' {
  declare module.exports: any;
}

declare module 'react-share/lib/GooglePlusShareCount' {
  declare module.exports: any;
}

declare module 'react-share/lib/index' {
  declare module.exports: any;
}

declare module 'react-share/lib/LinkedinIcon' {
  declare module.exports: any;
}

declare module 'react-share/lib/LinkedinShareButton' {
  declare module.exports: any;
}

declare module 'react-share/lib/LinkedinShareCount' {
  declare module.exports: any;
}

declare module 'react-share/lib/LivejournalIcon' {
  declare module.exports: any;
}

declare module 'react-share/lib/LivejournalShareButton' {
  declare module.exports: any;
}

declare module 'react-share/lib/MailruIcon' {
  declare module.exports: any;
}

declare module 'react-share/lib/MailruShareButton' {
  declare module.exports: any;
}

declare module 'react-share/lib/OKIcon' {
  declare module.exports: any;
}

declare module 'react-share/lib/OKShareButton' {
  declare module.exports: any;
}

declare module 'react-share/lib/OKShareCount' {
  declare module.exports: any;
}

declare module 'react-share/lib/PinterestIcon' {
  declare module.exports: any;
}

declare module 'react-share/lib/PinterestShareButton' {
  declare module.exports: any;
}

declare module 'react-share/lib/PinterestShareCount' {
  declare module.exports: any;
}

declare module 'react-share/lib/RedditIcon' {
  declare module.exports: any;
}

declare module 'react-share/lib/RedditShareButton' {
  declare module.exports: any;
}

declare module 'react-share/lib/RedditShareCount' {
  declare module.exports: any;
}

declare module 'react-share/lib/TelegramIcon' {
  declare module.exports: any;
}

declare module 'react-share/lib/TelegramShareButton' {
  declare module.exports: any;
}

declare module 'react-share/lib/TumblrIcon' {
  declare module.exports: any;
}

declare module 'react-share/lib/TumblrShareButton' {
  declare module.exports: any;
}

declare module 'react-share/lib/TumblrShareCount' {
  declare module.exports: any;
}

declare module 'react-share/lib/TwitterIcon' {
  declare module.exports: any;
}

declare module 'react-share/lib/TwitterShareButton' {
  declare module.exports: any;
}

declare module 'react-share/lib/utils/createShareButton' {
  declare module.exports: any;
}

declare module 'react-share/lib/utils/iconFactory' {
  declare module.exports: any;
}

declare module 'react-share/lib/utils/ieDetection' {
  declare module.exports: any;
}

declare module 'react-share/lib/utils/objectToGetParams' {
  declare module.exports: any;
}

declare module 'react-share/lib/utils/shareCountFactory' {
  declare module.exports: any;
}

declare module 'react-share/lib/ViberIcon' {
  declare module.exports: any;
}

declare module 'react-share/lib/ViberShareButton' {
  declare module.exports: any;
}

declare module 'react-share/lib/VKIcon' {
  declare module.exports: any;
}

declare module 'react-share/lib/VKShareButton' {
  declare module.exports: any;
}

declare module 'react-share/lib/VKShareCount' {
  declare module.exports: any;
}

declare module 'react-share/lib/WhatsappIcon' {
  declare module.exports: any;
}

declare module 'react-share/lib/WhatsappShareButton' {
  declare module.exports: any;
}

declare module 'react-share/lib/WorkplaceIcon' {
  declare module.exports: any;
}

declare module 'react-share/lib/WorkplaceShareButton' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-share/es/EmailIcon.js' {
  declare module.exports: $Exports<'react-share/es/EmailIcon'>;
}
declare module 'react-share/es/EmailShareButton.js' {
  declare module.exports: $Exports<'react-share/es/EmailShareButton'>;
}
declare module 'react-share/es/FacebookIcon.js' {
  declare module.exports: $Exports<'react-share/es/FacebookIcon'>;
}
declare module 'react-share/es/FacebookShareButton.js' {
  declare module.exports: $Exports<'react-share/es/FacebookShareButton'>;
}
declare module 'react-share/es/FacebookShareCount.js' {
  declare module.exports: $Exports<'react-share/es/FacebookShareCount'>;
}
declare module 'react-share/es/GooglePlusIcon.js' {
  declare module.exports: $Exports<'react-share/es/GooglePlusIcon'>;
}
declare module 'react-share/es/GooglePlusShareButton.js' {
  declare module.exports: $Exports<'react-share/es/GooglePlusShareButton'>;
}
declare module 'react-share/es/GooglePlusShareCount.js' {
  declare module.exports: $Exports<'react-share/es/GooglePlusShareCount'>;
}
declare module 'react-share/es/index.js' {
  declare module.exports: $Exports<'react-share/es/index'>;
}
declare module 'react-share/es/LinkedinIcon.js' {
  declare module.exports: $Exports<'react-share/es/LinkedinIcon'>;
}
declare module 'react-share/es/LinkedinShareButton.js' {
  declare module.exports: $Exports<'react-share/es/LinkedinShareButton'>;
}
declare module 'react-share/es/LinkedinShareCount.js' {
  declare module.exports: $Exports<'react-share/es/LinkedinShareCount'>;
}
declare module 'react-share/es/LivejournalIcon.js' {
  declare module.exports: $Exports<'react-share/es/LivejournalIcon'>;
}
declare module 'react-share/es/LivejournalShareButton.js' {
  declare module.exports: $Exports<'react-share/es/LivejournalShareButton'>;
}
declare module 'react-share/es/MailruIcon.js' {
  declare module.exports: $Exports<'react-share/es/MailruIcon'>;
}
declare module 'react-share/es/MailruShareButton.js' {
  declare module.exports: $Exports<'react-share/es/MailruShareButton'>;
}
declare module 'react-share/es/OKIcon.js' {
  declare module.exports: $Exports<'react-share/es/OKIcon'>;
}
declare module 'react-share/es/OKShareButton.js' {
  declare module.exports: $Exports<'react-share/es/OKShareButton'>;
}
declare module 'react-share/es/OKShareCount.js' {
  declare module.exports: $Exports<'react-share/es/OKShareCount'>;
}
declare module 'react-share/es/PinterestIcon.js' {
  declare module.exports: $Exports<'react-share/es/PinterestIcon'>;
}
declare module 'react-share/es/PinterestShareButton.js' {
  declare module.exports: $Exports<'react-share/es/PinterestShareButton'>;
}
declare module 'react-share/es/PinterestShareCount.js' {
  declare module.exports: $Exports<'react-share/es/PinterestShareCount'>;
}
declare module 'react-share/es/RedditIcon.js' {
  declare module.exports: $Exports<'react-share/es/RedditIcon'>;
}
declare module 'react-share/es/RedditShareButton.js' {
  declare module.exports: $Exports<'react-share/es/RedditShareButton'>;
}
declare module 'react-share/es/RedditShareCount.js' {
  declare module.exports: $Exports<'react-share/es/RedditShareCount'>;
}
declare module 'react-share/es/TelegramIcon.js' {
  declare module.exports: $Exports<'react-share/es/TelegramIcon'>;
}
declare module 'react-share/es/TelegramShareButton.js' {
  declare module.exports: $Exports<'react-share/es/TelegramShareButton'>;
}
declare module 'react-share/es/TumblrIcon.js' {
  declare module.exports: $Exports<'react-share/es/TumblrIcon'>;
}
declare module 'react-share/es/TumblrShareButton.js' {
  declare module.exports: $Exports<'react-share/es/TumblrShareButton'>;
}
declare module 'react-share/es/TumblrShareCount.js' {
  declare module.exports: $Exports<'react-share/es/TumblrShareCount'>;
}
declare module 'react-share/es/TwitterIcon.js' {
  declare module.exports: $Exports<'react-share/es/TwitterIcon'>;
}
declare module 'react-share/es/TwitterShareButton.js' {
  declare module.exports: $Exports<'react-share/es/TwitterShareButton'>;
}
declare module 'react-share/es/utils/createShareButton.js' {
  declare module.exports: $Exports<'react-share/es/utils/createShareButton'>;
}
declare module 'react-share/es/utils/iconFactory.js' {
  declare module.exports: $Exports<'react-share/es/utils/iconFactory'>;
}
declare module 'react-share/es/utils/ieDetection.js' {
  declare module.exports: $Exports<'react-share/es/utils/ieDetection'>;
}
declare module 'react-share/es/utils/objectToGetParams.js' {
  declare module.exports: $Exports<'react-share/es/utils/objectToGetParams'>;
}
declare module 'react-share/es/utils/shareCountFactory.js' {
  declare module.exports: $Exports<'react-share/es/utils/shareCountFactory'>;
}
declare module 'react-share/es/ViberIcon.js' {
  declare module.exports: $Exports<'react-share/es/ViberIcon'>;
}
declare module 'react-share/es/ViberShareButton.js' {
  declare module.exports: $Exports<'react-share/es/ViberShareButton'>;
}
declare module 'react-share/es/VKIcon.js' {
  declare module.exports: $Exports<'react-share/es/VKIcon'>;
}
declare module 'react-share/es/VKShareButton.js' {
  declare module.exports: $Exports<'react-share/es/VKShareButton'>;
}
declare module 'react-share/es/VKShareCount.js' {
  declare module.exports: $Exports<'react-share/es/VKShareCount'>;
}
declare module 'react-share/es/WhatsappIcon.js' {
  declare module.exports: $Exports<'react-share/es/WhatsappIcon'>;
}
declare module 'react-share/es/WhatsappShareButton.js' {
  declare module.exports: $Exports<'react-share/es/WhatsappShareButton'>;
}
declare module 'react-share/es/WorkplaceIcon.js' {
  declare module.exports: $Exports<'react-share/es/WorkplaceIcon'>;
}
declare module 'react-share/es/WorkplaceShareButton.js' {
  declare module.exports: $Exports<'react-share/es/WorkplaceShareButton'>;
}
declare module 'react-share/lib/EmailIcon.js' {
  declare module.exports: $Exports<'react-share/lib/EmailIcon'>;
}
declare module 'react-share/lib/EmailShareButton.js' {
  declare module.exports: $Exports<'react-share/lib/EmailShareButton'>;
}
declare module 'react-share/lib/FacebookIcon.js' {
  declare module.exports: $Exports<'react-share/lib/FacebookIcon'>;
}
declare module 'react-share/lib/FacebookShareButton.js' {
  declare module.exports: $Exports<'react-share/lib/FacebookShareButton'>;
}
declare module 'react-share/lib/FacebookShareCount.js' {
  declare module.exports: $Exports<'react-share/lib/FacebookShareCount'>;
}
declare module 'react-share/lib/GooglePlusIcon.js' {
  declare module.exports: $Exports<'react-share/lib/GooglePlusIcon'>;
}
declare module 'react-share/lib/GooglePlusShareButton.js' {
  declare module.exports: $Exports<'react-share/lib/GooglePlusShareButton'>;
}
declare module 'react-share/lib/GooglePlusShareCount.js' {
  declare module.exports: $Exports<'react-share/lib/GooglePlusShareCount'>;
}
declare module 'react-share/lib/index.js' {
  declare module.exports: $Exports<'react-share/lib/index'>;
}
declare module 'react-share/lib/LinkedinIcon.js' {
  declare module.exports: $Exports<'react-share/lib/LinkedinIcon'>;
}
declare module 'react-share/lib/LinkedinShareButton.js' {
  declare module.exports: $Exports<'react-share/lib/LinkedinShareButton'>;
}
declare module 'react-share/lib/LinkedinShareCount.js' {
  declare module.exports: $Exports<'react-share/lib/LinkedinShareCount'>;
}
declare module 'react-share/lib/LivejournalIcon.js' {
  declare module.exports: $Exports<'react-share/lib/LivejournalIcon'>;
}
declare module 'react-share/lib/LivejournalShareButton.js' {
  declare module.exports: $Exports<'react-share/lib/LivejournalShareButton'>;
}
declare module 'react-share/lib/MailruIcon.js' {
  declare module.exports: $Exports<'react-share/lib/MailruIcon'>;
}
declare module 'react-share/lib/MailruShareButton.js' {
  declare module.exports: $Exports<'react-share/lib/MailruShareButton'>;
}
declare module 'react-share/lib/OKIcon.js' {
  declare module.exports: $Exports<'react-share/lib/OKIcon'>;
}
declare module 'react-share/lib/OKShareButton.js' {
  declare module.exports: $Exports<'react-share/lib/OKShareButton'>;
}
declare module 'react-share/lib/OKShareCount.js' {
  declare module.exports: $Exports<'react-share/lib/OKShareCount'>;
}
declare module 'react-share/lib/PinterestIcon.js' {
  declare module.exports: $Exports<'react-share/lib/PinterestIcon'>;
}
declare module 'react-share/lib/PinterestShareButton.js' {
  declare module.exports: $Exports<'react-share/lib/PinterestShareButton'>;
}
declare module 'react-share/lib/PinterestShareCount.js' {
  declare module.exports: $Exports<'react-share/lib/PinterestShareCount'>;
}
declare module 'react-share/lib/RedditIcon.js' {
  declare module.exports: $Exports<'react-share/lib/RedditIcon'>;
}
declare module 'react-share/lib/RedditShareButton.js' {
  declare module.exports: $Exports<'react-share/lib/RedditShareButton'>;
}
declare module 'react-share/lib/RedditShareCount.js' {
  declare module.exports: $Exports<'react-share/lib/RedditShareCount'>;
}
declare module 'react-share/lib/TelegramIcon.js' {
  declare module.exports: $Exports<'react-share/lib/TelegramIcon'>;
}
declare module 'react-share/lib/TelegramShareButton.js' {
  declare module.exports: $Exports<'react-share/lib/TelegramShareButton'>;
}
declare module 'react-share/lib/TumblrIcon.js' {
  declare module.exports: $Exports<'react-share/lib/TumblrIcon'>;
}
declare module 'react-share/lib/TumblrShareButton.js' {
  declare module.exports: $Exports<'react-share/lib/TumblrShareButton'>;
}
declare module 'react-share/lib/TumblrShareCount.js' {
  declare module.exports: $Exports<'react-share/lib/TumblrShareCount'>;
}
declare module 'react-share/lib/TwitterIcon.js' {
  declare module.exports: $Exports<'react-share/lib/TwitterIcon'>;
}
declare module 'react-share/lib/TwitterShareButton.js' {
  declare module.exports: $Exports<'react-share/lib/TwitterShareButton'>;
}
declare module 'react-share/lib/utils/createShareButton.js' {
  declare module.exports: $Exports<'react-share/lib/utils/createShareButton'>;
}
declare module 'react-share/lib/utils/iconFactory.js' {
  declare module.exports: $Exports<'react-share/lib/utils/iconFactory'>;
}
declare module 'react-share/lib/utils/ieDetection.js' {
  declare module.exports: $Exports<'react-share/lib/utils/ieDetection'>;
}
declare module 'react-share/lib/utils/objectToGetParams.js' {
  declare module.exports: $Exports<'react-share/lib/utils/objectToGetParams'>;
}
declare module 'react-share/lib/utils/shareCountFactory.js' {
  declare module.exports: $Exports<'react-share/lib/utils/shareCountFactory'>;
}
declare module 'react-share/lib/ViberIcon.js' {
  declare module.exports: $Exports<'react-share/lib/ViberIcon'>;
}
declare module 'react-share/lib/ViberShareButton.js' {
  declare module.exports: $Exports<'react-share/lib/ViberShareButton'>;
}
declare module 'react-share/lib/VKIcon.js' {
  declare module.exports: $Exports<'react-share/lib/VKIcon'>;
}
declare module 'react-share/lib/VKShareButton.js' {
  declare module.exports: $Exports<'react-share/lib/VKShareButton'>;
}
declare module 'react-share/lib/VKShareCount.js' {
  declare module.exports: $Exports<'react-share/lib/VKShareCount'>;
}
declare module 'react-share/lib/WhatsappIcon.js' {
  declare module.exports: $Exports<'react-share/lib/WhatsappIcon'>;
}
declare module 'react-share/lib/WhatsappShareButton.js' {
  declare module.exports: $Exports<'react-share/lib/WhatsappShareButton'>;
}
declare module 'react-share/lib/WorkplaceIcon.js' {
  declare module.exports: $Exports<'react-share/lib/WorkplaceIcon'>;
}
declare module 'react-share/lib/WorkplaceShareButton.js' {
  declare module.exports: $Exports<'react-share/lib/WorkplaceShareButton'>;
}
