// flow-typed signature: c191ee4cb7ff7b066a663b1b7e53d045
// flow-typed version: <<STUB>>/react-activity_v^1.1.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-activity'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-activity' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-activity/dist/react-activity' {
  declare module.exports: any;
}

declare module 'react-activity/lib/activityIndicator' {
  declare module.exports: any;
}

declare module 'react-activity/lib/Bounce/Bounce' {
  declare module.exports: any;
}

declare module 'react-activity/lib/Bounce/index' {
  declare module.exports: any;
}

declare module 'react-activity/lib/Digital/Digital' {
  declare module.exports: any;
}

declare module 'react-activity/lib/Digital/index' {
  declare module.exports: any;
}

declare module 'react-activity/lib/Dots/Dots' {
  declare module.exports: any;
}

declare module 'react-activity/lib/Dots/index' {
  declare module.exports: any;
}

declare module 'react-activity/lib/index' {
  declare module.exports: any;
}

declare module 'react-activity/lib/Levels/index' {
  declare module.exports: any;
}

declare module 'react-activity/lib/Levels/Levels' {
  declare module.exports: any;
}

declare module 'react-activity/lib/Sentry/index' {
  declare module.exports: any;
}

declare module 'react-activity/lib/Sentry/Sentry' {
  declare module.exports: any;
}

declare module 'react-activity/lib/Spinner/index' {
  declare module.exports: any;
}

declare module 'react-activity/lib/Spinner/Spinner' {
  declare module.exports: any;
}

declare module 'react-activity/lib/Squares/index' {
  declare module.exports: any;
}

declare module 'react-activity/lib/Squares/Squares' {
  declare module.exports: any;
}

declare module 'react-activity/lib/Windmill/index' {
  declare module.exports: any;
}

declare module 'react-activity/lib/Windmill/Windmill' {
  declare module.exports: any;
}

declare module 'react-activity/src/activityIndicator' {
  declare module.exports: any;
}

declare module 'react-activity/src/Bounce/Bounce' {
  declare module.exports: any;
}

declare module 'react-activity/src/Bounce/index' {
  declare module.exports: any;
}

declare module 'react-activity/src/Digital/Digital' {
  declare module.exports: any;
}

declare module 'react-activity/src/Digital/index' {
  declare module.exports: any;
}

declare module 'react-activity/src/Dots/Dots' {
  declare module.exports: any;
}

declare module 'react-activity/src/Dots/index' {
  declare module.exports: any;
}

declare module 'react-activity/src/index' {
  declare module.exports: any;
}

declare module 'react-activity/src/Levels/index' {
  declare module.exports: any;
}

declare module 'react-activity/src/Levels/Levels' {
  declare module.exports: any;
}

declare module 'react-activity/src/Sentry/index' {
  declare module.exports: any;
}

declare module 'react-activity/src/Sentry/Sentry' {
  declare module.exports: any;
}

declare module 'react-activity/src/Spinner/index' {
  declare module.exports: any;
}

declare module 'react-activity/src/Spinner/Spinner' {
  declare module.exports: any;
}

declare module 'react-activity/src/Squares/index' {
  declare module.exports: any;
}

declare module 'react-activity/src/Squares/Squares' {
  declare module.exports: any;
}

declare module 'react-activity/src/Windmill/index' {
  declare module.exports: any;
}

declare module 'react-activity/src/Windmill/Windmill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-activity/dist/react-activity.js' {
  declare module.exports: $Exports<'react-activity/dist/react-activity'>;
}
declare module 'react-activity/lib/activityIndicator.js' {
  declare module.exports: $Exports<'react-activity/lib/activityIndicator'>;
}
declare module 'react-activity/lib/Bounce/Bounce.js' {
  declare module.exports: $Exports<'react-activity/lib/Bounce/Bounce'>;
}
declare module 'react-activity/lib/Bounce/index.js' {
  declare module.exports: $Exports<'react-activity/lib/Bounce/index'>;
}
declare module 'react-activity/lib/Digital/Digital.js' {
  declare module.exports: $Exports<'react-activity/lib/Digital/Digital'>;
}
declare module 'react-activity/lib/Digital/index.js' {
  declare module.exports: $Exports<'react-activity/lib/Digital/index'>;
}
declare module 'react-activity/lib/Dots/Dots.js' {
  declare module.exports: $Exports<'react-activity/lib/Dots/Dots'>;
}
declare module 'react-activity/lib/Dots/index.js' {
  declare module.exports: $Exports<'react-activity/lib/Dots/index'>;
}
declare module 'react-activity/lib/index.js' {
  declare module.exports: $Exports<'react-activity/lib/index'>;
}
declare module 'react-activity/lib/Levels/index.js' {
  declare module.exports: $Exports<'react-activity/lib/Levels/index'>;
}
declare module 'react-activity/lib/Levels/Levels.js' {
  declare module.exports: $Exports<'react-activity/lib/Levels/Levels'>;
}
declare module 'react-activity/lib/Sentry/index.js' {
  declare module.exports: $Exports<'react-activity/lib/Sentry/index'>;
}
declare module 'react-activity/lib/Sentry/Sentry.js' {
  declare module.exports: $Exports<'react-activity/lib/Sentry/Sentry'>;
}
declare module 'react-activity/lib/Spinner/index.js' {
  declare module.exports: $Exports<'react-activity/lib/Spinner/index'>;
}
declare module 'react-activity/lib/Spinner/Spinner.js' {
  declare module.exports: $Exports<'react-activity/lib/Spinner/Spinner'>;
}
declare module 'react-activity/lib/Squares/index.js' {
  declare module.exports: $Exports<'react-activity/lib/Squares/index'>;
}
declare module 'react-activity/lib/Squares/Squares.js' {
  declare module.exports: $Exports<'react-activity/lib/Squares/Squares'>;
}
declare module 'react-activity/lib/Windmill/index.js' {
  declare module.exports: $Exports<'react-activity/lib/Windmill/index'>;
}
declare module 'react-activity/lib/Windmill/Windmill.js' {
  declare module.exports: $Exports<'react-activity/lib/Windmill/Windmill'>;
}
declare module 'react-activity/src/activityIndicator.js' {
  declare module.exports: $Exports<'react-activity/src/activityIndicator'>;
}
declare module 'react-activity/src/Bounce/Bounce.js' {
  declare module.exports: $Exports<'react-activity/src/Bounce/Bounce'>;
}
declare module 'react-activity/src/Bounce/index.js' {
  declare module.exports: $Exports<'react-activity/src/Bounce/index'>;
}
declare module 'react-activity/src/Digital/Digital.js' {
  declare module.exports: $Exports<'react-activity/src/Digital/Digital'>;
}
declare module 'react-activity/src/Digital/index.js' {
  declare module.exports: $Exports<'react-activity/src/Digital/index'>;
}
declare module 'react-activity/src/Dots/Dots.js' {
  declare module.exports: $Exports<'react-activity/src/Dots/Dots'>;
}
declare module 'react-activity/src/Dots/index.js' {
  declare module.exports: $Exports<'react-activity/src/Dots/index'>;
}
declare module 'react-activity/src/index.js' {
  declare module.exports: $Exports<'react-activity/src/index'>;
}
declare module 'react-activity/src/Levels/index.js' {
  declare module.exports: $Exports<'react-activity/src/Levels/index'>;
}
declare module 'react-activity/src/Levels/Levels.js' {
  declare module.exports: $Exports<'react-activity/src/Levels/Levels'>;
}
declare module 'react-activity/src/Sentry/index.js' {
  declare module.exports: $Exports<'react-activity/src/Sentry/index'>;
}
declare module 'react-activity/src/Sentry/Sentry.js' {
  declare module.exports: $Exports<'react-activity/src/Sentry/Sentry'>;
}
declare module 'react-activity/src/Spinner/index.js' {
  declare module.exports: $Exports<'react-activity/src/Spinner/index'>;
}
declare module 'react-activity/src/Spinner/Spinner.js' {
  declare module.exports: $Exports<'react-activity/src/Spinner/Spinner'>;
}
declare module 'react-activity/src/Squares/index.js' {
  declare module.exports: $Exports<'react-activity/src/Squares/index'>;
}
declare module 'react-activity/src/Squares/Squares.js' {
  declare module.exports: $Exports<'react-activity/src/Squares/Squares'>;
}
declare module 'react-activity/src/Windmill/index.js' {
  declare module.exports: $Exports<'react-activity/src/Windmill/index'>;
}
declare module 'react-activity/src/Windmill/Windmill.js' {
  declare module.exports: $Exports<'react-activity/src/Windmill/Windmill'>;
}
