// flow-typed signature: 44b00e39a472d43dac28db9177d72fa5
// flow-typed version: <<STUB>>/ttag_v^1.1.0-0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ttag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ttag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ttag/dist/config' {
  declare module.exports: any;
}

declare module 'ttag/dist/index' {
  declare module.exports: any;
}

declare module 'ttag/dist/mock' {
  declare module.exports: any;
}

declare module 'ttag/dist/ttag' {
  declare module.exports: any;
}

declare module 'ttag/dist/ttag.min' {
  declare module.exports: any;
}

declare module 'ttag/dist/utils' {
  declare module.exports: any;
}

declare module 'ttag/dist/validation' {
  declare module.exports: any;
}

declare module 'ttag/loader' {
  declare module.exports: any;
}

declare module 'ttag/src/config' {
  declare module.exports: any;
}

declare module 'ttag/src/index' {
  declare module.exports: any;
}

declare module 'ttag/src/mock' {
  declare module.exports: any;
}

declare module 'ttag/src/utils' {
  declare module.exports: any;
}

declare module 'ttag/src/validation' {
  declare module.exports: any;
}

declare module 'ttag/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ttag/dist/config.js' {
  declare module.exports: $Exports<'ttag/dist/config'>;
}
declare module 'ttag/dist/index.js' {
  declare module.exports: $Exports<'ttag/dist/index'>;
}
declare module 'ttag/dist/mock.js' {
  declare module.exports: $Exports<'ttag/dist/mock'>;
}
declare module 'ttag/dist/ttag.js' {
  declare module.exports: $Exports<'ttag/dist/ttag'>;
}
declare module 'ttag/dist/ttag.min.js' {
  declare module.exports: $Exports<'ttag/dist/ttag.min'>;
}
declare module 'ttag/dist/utils.js' {
  declare module.exports: $Exports<'ttag/dist/utils'>;
}
declare module 'ttag/dist/validation.js' {
  declare module.exports: $Exports<'ttag/dist/validation'>;
}
declare module 'ttag/loader.js' {
  declare module.exports: $Exports<'ttag/loader'>;
}
declare module 'ttag/src/config.js' {
  declare module.exports: $Exports<'ttag/src/config'>;
}
declare module 'ttag/src/index.js' {
  declare module.exports: $Exports<'ttag/src/index'>;
}
declare module 'ttag/src/mock.js' {
  declare module.exports: $Exports<'ttag/src/mock'>;
}
declare module 'ttag/src/utils.js' {
  declare module.exports: $Exports<'ttag/src/utils'>;
}
declare module 'ttag/src/validation.js' {
  declare module.exports: $Exports<'ttag/src/validation'>;
}
declare module 'ttag/webpack.config.js' {
  declare module.exports: $Exports<'ttag/webpack.config'>;
}
