// flow-typed signature: 9ffd50c438fb6c51e08df2e603cb6d1f
// flow-typed version: <<STUB>>/wdio_v^2.0.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wdio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wdio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wdio/example' {
  declare module.exports: any;
}

declare module 'wdio/wdio' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wdio/example.js' {
  declare module.exports: $Exports<'wdio/example'>;
}
declare module 'wdio/wdio.js' {
  declare module.exports: $Exports<'wdio/wdio'>;
}
