// flow-typed signature: e8cbf6c05641d3f9e310e6a159f78a30
// flow-typed version: <<STUB>>/webworkify-webpack_v^2.0.4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webworkify-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webworkify-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webworkify-webpack/example/common-js-worker' {
  declare module.exports: any;
}

declare module 'webworkify-webpack/example/es6-worker' {
  declare module.exports: any;
}

declare module 'webworkify-webpack/example/main' {
  declare module.exports: any;
}

declare module 'webworkify-webpack/example/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webworkify-webpack/example/common-js-worker.js' {
  declare module.exports: $Exports<'webworkify-webpack/example/common-js-worker'>;
}
declare module 'webworkify-webpack/example/es6-worker.js' {
  declare module.exports: $Exports<'webworkify-webpack/example/es6-worker'>;
}
declare module 'webworkify-webpack/example/main.js' {
  declare module.exports: $Exports<'webworkify-webpack/example/main'>;
}
declare module 'webworkify-webpack/example/webpack.config.js' {
  declare module.exports: $Exports<'webworkify-webpack/example/webpack.config'>;
}
declare module 'webworkify-webpack/index' {
  declare module.exports: $Exports<'webworkify-webpack'>;
}
declare module 'webworkify-webpack/index.js' {
  declare module.exports: $Exports<'webworkify-webpack'>;
}
