// flow-typed signature: 72e31766181a4737ef385f638dd2481a
// flow-typed version: <<STUB>>/wicg-focus-ring_vhttps://github.com/dakeyras7/focus-ring#include-enter-keydown/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wicg-focus-ring'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wicg-focus-ring' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wicg-focus-ring/dist/focus-ring' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/rollup.config' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/src/focus-ring' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wicg-focus-ring/dist/focus-ring.js' {
  declare module.exports: $Exports<'wicg-focus-ring/dist/focus-ring'>;
}
declare module 'wicg-focus-ring/rollup.config.js' {
  declare module.exports: $Exports<'wicg-focus-ring/rollup.config'>;
}
declare module 'wicg-focus-ring/src/focus-ring.js' {
  declare module.exports: $Exports<'wicg-focus-ring/src/focus-ring'>;
}
