export { default as elevatorBrokenBig } from './elevatorBrokenBig'
export { default as elevatorUnknownBig } from './elevatorUnknownBig'
export { default as elevatorWorkingBig } from './elevatorWorkingBig'
export { default as escalatorBrokenBig } from './escalatorBrokenBig'
export { default as escalatorUnknownBig } from './escalatorUnknownBig'
export { default as escalatorWorkingBig } from './escalatorWorkingBig'
