import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://feature-a11ymap.wheelmap.tech/onboarding?q=');
  await page.getByRole('button', { name: 'Okay, let’s go!' }).click();
  await page.getByRole('button', { name: 'I’m in!' }).click();
  await page.goto('https://feature-a11ymap.wheelmap.tech/');
  await page.getByPlaceholder('Search for place or address').click();
  await page.getByPlaceholder('Search for place or address').fill('g');
  await page.goto('https://feature-a11ymap.wheelmap.tech/?q=g');
  await page.getByPlaceholder('Search for place or address').fill('gr');
  await page.goto('https://feature-a11ymap.wheelmap.tech/?q=gr');
  await page.getByPlaceholder('Search for place or address').fill('gre');
  await page.goto('https://feature-a11ymap.wheelmap.tech/?q=gre');
  await page.getByPlaceholder('Search for place or address').fill('grei');
  await page.goto('https://feature-a11ymap.wheelmap.tech/?q=grei');
  await page.getByPlaceholder('Search for place or address').fill('greif');
  await page.goto('https://feature-a11ymap.wheelmap.tech/?q=greif');
  await page.getByPlaceholder('Search for place or address').fill('greifs');
  await page.goto('https://feature-a11ymap.wheelmap.tech/?q=greifs');
  await page.getByPlaceholder('Search for place or address').fill('greifsw');
  await page.goto('https://feature-a11ymap.wheelmap.tech/?q=greifsw');
  await page.getByPlaceholder('Search for place or address').fill('greifswa');
  await page.goto('https://feature-a11ymap.wheelmap.tech/?q=greifswa');
  await page.getByPlaceholder('Search for place or address').fill('greifswal');
  await page.goto('https://feature-a11ymap.wheelmap.tech/?q=greifswal');
  await page.getByPlaceholder('Search for place or address').fill('greifswald');
  await page.goto('https://feature-a11ymap.wheelmap.tech/?q=greifswald');
  await page.getByPlaceholder('Search for place or address').fill('greifswalde');
  await page.goto('https://feature-a11ymap.wheelmap.tech/?q=greifswalde');
  await page.getByPlaceholder('Search for place or address').fill('greifswalder');
  await page.goto('https://feature-a11ymap.wheelmap.tech/?q=greifswalder');
  await page.getByPlaceholder('Search for place or address').fill('greifswalder ');
  await page.goto('https://feature-a11ymap.wheelmap.tech/?q=greifswalder+');
  await page.getByRole('link', { name: 'Greifswalder Straße Restaurant Fußgängertunnel Greifswalder Straße, 10407' }).click();
  await page.getByRole('link', { name: 'Add new image' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Select image' }).click();
  await page.getByRole('button', { name: 'Select image' }).setInputFiles('1000015934.jpg');
  await page.getByRole('button', { name: 'Upload image' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
});