export const pathsToConsumedTagKeys: [string, RegExp][] = [
  ["wheelchair_accessibility.wheelchair", /^wheelchair$/],
  [
    "wheelchair_accessibility.description",
    /^wheelchair:description(?:[:\w-]+)?$/,
  ],
  ["location.indoor", /^indoor$/],
  ["location.level", /^level$/],
  ["location.level_ref", /^level:ref$/],
  ["location.room", /^room$/],
  ["location.building_part", /^building:part$/],
  ["building_object.type", /^building$/],
  ["look.$1_$1", /^(building|roof):(colour|material|levels)|height$/],
  ["building_object.$1", /^building:([\w_]+)$/],
  ["building_object.$1_level", /^(min|max)_level$/],
  ["payment.$1", /^payment:([\w_]+)$/],
  ["payment.$1.$2", /^payment:([\w_]+):([\w_]+)$/],
  ["payment.description.$1", /^description:payment:([\w_]+)$/],
  ["payment.description", /^description:payment$/],
  ["payment.fee", /^fee$/],
  ["payment.fee_$1", /^fee:([\w_]+)$/],
  ["payment.self_checkout", /^self_checkout$/],
  ["payment.charge", /^charge$/],
  ["payment.charge.$1", /^charge:([\w_]+)$/],
  ["payment.charge.$1", /^([\w_]+):charge$/],
  ["diet.$1", /^diet:([\w_]+)$/],
  ["diet.cuisine", /^cuisine$/],
  ["stay.$1", /^(.*)_?seating$/],
  ["stay.takeaway", /^takeaway$/],
  ["stay.reservation", /^reservation$/],
  ["stay.delivery", /^delivery$/],
  ["stay.offered", /^delivery$/],
  ["stay.partner", /^delivery:partner$/],
  ["stay.smoking", /^smoking$/],
  ["stay.smoking_$1", /^smoking:([\w_]+)$/],
  ["stay.air_conditioning", /^air_conditioning$/],
  ["internet.access", /^internet_access$/],
  ["internet.$1", /^internet_access:([\w_]+)$/],
  ["ramp.$1", /^ramp:([\w_]+)$/],
  ["handrail.$1", /^handrail:([\w_]+)$/],
  ["restrooms.changing_table.$1", /^changing_table:([\w_]+)$/],
  ["restrooms.changing_table", /^changing_table$/],
  ["entrance.door", /^door$/],
  ["entrance.automatic_door", /^automatic_door$/],
  ["entrance.door:$1", /^door:([\w_]+)$/],
  ["entrance.$1.door.automatic", /^automatic_door:([\w_]+)$/],
  ["entrance.step_count", /^step_count$/],
  ["entrance.step_height", /^wheelchair:step_height$/],
  ["entrance.width", /^wheelchair:entrance_width$/],
  ["audience.name", /^access$/],
  ["audience.$1", /^access:([\w_]+)$/],
  ["audience.$1", /^min_age|max_age$/],
  ["health.healthcare", /^healthcare$/],
  ["health.speciality", /^healthcare:speciality$/],
  ["health.dispensing", /^dispensing$/],
  ["capacities.$1", /^capacity:([\w_]+)$/],
  ["capacities.capacity:total", /^capacity$/],
  [
    "audience.$1",
    /^(unisex|male|female|child|gay|lgbtq|men|women|gay|lgbtq|queer|community_centre:for|baby)$/,
  ],
  [
    "audience.$1.$2",
    /^(unisex|male|female|child|gay|lgbtq|men|women|gay|lgbtq|queer):(.*)$/,
  ],
  ["audience.$1", /^(social_facility|community_centre):for$/],
  ["audience.centralkey", /^centralkey$/],
  ["audience.$1", /^provided_for:(\w+)$/],
  ["audience.blind", /^blind$/],
  ["operator.$1", /^operator:([\w_]+)$/],
  ["restrooms.$1", /^toilets:([\w_]+)$/],
  ["restrooms.toilets", /^toilets$/],
  ["payment.fee:urinal", /^fee:urinal$/],
  ["information.tactile_writing.$1.$2", /^tactile_writing:([\w_]+):([\w_]+)$/],
  ["information.speech_output.$1", /^speech_output:([\w_]+)$/],
  ["information.speech_input.$1", /^speech_input:([\w_]+)$/],
  ["information.braille", /^braille$/],
  ["socket.$1.count", /^socket:([\w_]+)$/],
  ["socket.$1.$2", /^socket:([\w_]+):([\w_]+)$/],
  ["sidewalk.sidewalk:$1", /^sidewalk:([\w_]+)$/],
  ["sidewalk.sidewalk:$1.$2", /^sidewalk:([\w_]+):([\w_]+)$/],
  ["crossing.1", /^crossing$/],
  ["crossing.$1", /^crossing:([\w_]+)$/],
  ["description.$1", /^description:([\w_]+)$/],
  [
    "means_of_transport.$1",
    /^(train|tram|subway|coach|ferry|subway|bus|taxi|share_taxi|minibus|light_rail|tourist_bus|trolleybus|monorail)$/,
  ],
  [
    "amenities.$1",
    /^(bin|shelter|lit|bench|tactile_paving|compressed_air|power_supply|sanitary_dump_station)$/,
  ],
  ["service.bike_$1", /^service:bicycle:([\w_]+)$/],
  ["playground_structure.type", /^playground$/],
  ["playground_structure.$1", /^playground:([\w_]+)$/],
  ["left.$1.$2", /^([\w_]+):left:([\w_]+)$/],
  ["left.$1", /^([\w_]+):left$/],
  ["right.$1.$2", /^([\w_]+):right:([\w_]+)$/],
  ["right.$1", /^([\w_]+):right$/],
  ["both.$1.$2", /^([\w_]+):both:([\w_]+)$/],
  ["both.$1", /^([\w_]+):both$/],
  ["ground.surface", /^surface$/],
  ["ground.surface.$1", /^surface:([\w_]+)$/],
  ["ground.kerb", /^kerb$/],
  ["ground.kerb_$1", /^kerb:([\w_]+)$/],
  ["passenger_information.display", /^passenger_information_display$/],
  ["passenger_information.departures_board", /^departures_board$/],
  ["passenger_information.$1", /^passenger_information_display:([\w_]+)$/],
  ["$1", /(.*)/], // Should be last
];
