# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

languages([
  'en-US',
  'de-DE',
  'da',
  'el',
  'fr-FR',
  'es-ES',
  'ja',
  'ru',
  'sv',
])