// flow-typed signature: 8a00f08ecc22e11a3061393f667b3e00
// flow-typed version: <<STUB>>/@sozialhelden/focus-trap-react_v^5.0.0-react-component-compat/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sozialhelden/focus-trap-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sozialhelden/focus-trap-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sozialhelden/focus-trap-react/dist/focus-trap-react' {
  declare module.exports: any;
}

declare module '@sozialhelden/focus-trap-react/src/focus-trap-react' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sozialhelden/focus-trap-react/dist/focus-trap-react.js' {
  declare module.exports: $Exports<'@sozialhelden/focus-trap-react/dist/focus-trap-react'>;
}
declare module '@sozialhelden/focus-trap-react/src/focus-trap-react.js' {
  declare module.exports: $Exports<'@sozialhelden/focus-trap-react/src/focus-trap-react'>;
}
