// flow-typed signature: d1e054669a0065c05f180d3bfc494b1b
// flow-typed version: <<STUB>>/@zeit/next-sass_v^1.0.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@zeit/next-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@zeit/next-sass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@zeit/next-sass/index' {
  declare module.exports: $Exports<'@zeit/next-sass'>;
}
declare module '@zeit/next-sass/index.js' {
  declare module.exports: $Exports<'@zeit/next-sass'>;
}
